const byId=id=>document.getElementById(id);let profile=null,profileError=null,tabletData={units:[],training:[],calendar:[],announcements:[]};
window.addEventListener('message',event=>{const m=event.data;if(m.type==='visible')byId('tablet').classList.toggle('hidden',!m.visible);if(m.type==='profile'){profile=m.data&&m.data.player?m.data.player:null;profileError=m.data&&!m.data.ok?m.data.error:null;renderProfile();}if(m.type==='tabletData'){tabletData=m.data||tabletData;renderData();}if(m.type==='reportResult'&&m.data&&m.data.ok){byId('reportedName').value='';byId('reportSubject').value='';byId('reportDetails').value='';}if(m.type==='notice'||m.type==='reportResult')showNotice(m.data&&m.data.ok?'Operation completed':(m.data&&m.data.error)||'Request failed');});
document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('main > section').forEach(s=>s.classList.add('hidden'));byId(button.dataset.page).classList.remove('hidden');document.querySelectorAll('.tablet-tabs [data-page]').forEach(tab=>{const selected=tab.dataset.page===button.dataset.page;tab.classList.toggle('active',selected);if(selected)tab.setAttribute('aria-current','page');else tab.removeAttribute('aria-current');});}));
async function send(action,data){try{const response=await fetch('https://'+GetParentResourceName()+'/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})});if(!response.ok)throw new Error('NUI callback failed');return true;}catch{showNotice('Cannot contact the Community Hub resource. Restart communityhub and check the client console.');return false;}}
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML;}
function renderProfile(){updateChatAccess();byId('connection').textContent=profile?'Account linked':profileError?'Unavailable':'Not linked';byId('connection').classList.toggle('linked',!!profile);if(!profile){byId('status').textContent=profileError||'FiveM account not linked.';byId('linkBox').classList.remove('hidden');byId('profileContent').textContent='Generate a linking code on the Community Hub website.';return;}byId('status').textContent='Authenticated · '+(profile.display_name||'Member');byId('department').textContent=profile.department_name||'Unassigned';byId('rank').textContent=profile.rank_name||profile.role;byId('callsign').textContent=profile.callsign||'—';byId('linkBox').classList.add('hidden');byId('profileContent').innerHTML='<div class="record"><b>'+esc(profile.display_name||'')+'</b><span>'+esc(profile.department_name||'No department')+' · '+esc(profile.rank_name||profile.role)+'</span><span>Certifications: '+esc((profile.certifications||[]).join(', ')||'None')+'</span></div>';}
function renderData(){const units=tabletData.units||[];byId('unitCount').textContent=units.length;byId('unitsList').innerHTML=units.length?units.map(u=>'<div class="record"><b>'+esc(u.callsign||'UNIT')+' · '+esc(u.player_name||'Unknown')+'</b><span>'+esc(u.department||'Unassigned')+' · '+esc(u.rank_name||'Member')+'</span><em>'+esc(u.duty_status||'available')+'</em></div>').join(''):'<p>No active units.</p>';byId('trainingList').innerHTML='<h3>Upcoming Training</h3>'+((tabletData.training||[]).map(t=>'<div class="record"><b>'+esc(t.title)+'</b><span>'+esc(new Date(t.start_at).toLocaleString())+' · '+esc(t.location||'TBA')+'</span></div>').join('')||'<p>No upcoming training.</p>');byId('calendarList').innerHTML='<h3>Community Calendar</h3>'+((tabletData.calendar||[]).map(e=>'<div class="record"><b>'+esc(e.title)+'</b><span>'+esc(new Date(e.start_at).toLocaleString())+' · '+esc(e.event_type||'event')+'</span></div>').join('')||'<p>No upcoming events.</p>');byId('announcementList').innerHTML=(tabletData.announcements||[]).map(a=>'<div class="record '+esc(a.priority)+'"><b>'+esc(a.title)+'</b><span>'+esc(a.message)+'</span></div>').join('')||'<p>No current announcements.</p>';}
function showNotice(text){byId('notice').textContent=text;byId('notice').style.display='block';setTimeout(()=>byId('notice').style.display='none',3500);}setInterval(()=>{byId('clock').textContent=new Date().toLocaleTimeString();},1000);
byId('close').onclick=()=>send('close');byId('clockIn').onclick=()=>send('clockIn');byId('clockOut').onclick=()=>send('clockOut');byId('link').onclick=()=>send('link',{code:byId('linkCode').value});byId('submitReport').onclick=()=>{send('report',{report_type:byId('reportType').value,reported_name:byId('reportedName').value,subject:byId('reportSubject').value,details:byId('reportDetails').value});};document.addEventListener('keyup',e=>{if(e.key==='Escape')send('close');});
const adminRoles=['admin','management','owner'];let chatPending=false;
function canChat(){return !!profile&&adminRoles.includes(profile.role);}
function updateChatAccess(){byId('adminChatNav').classList.toggle('hidden',!canChat());if(!canChat()){byId('chatMessages').textContent='';byId('chatMessage').value='';if(!byId('adminChat').classList.contains('hidden')){byId('home').classList.remove('hidden');document.querySelectorAll('.tablet-tabs [data-page]').forEach(tab=>{const selected=tab.dataset.page==='home';tab.classList.toggle('active',selected);if(selected)tab.setAttribute('aria-current','page');else tab.removeAttribute('aria-current');});}byId('adminChat').classList.add('hidden');}}
window.addEventListener('message',event=>{const m=event.data;
 if(m.type==='gameClock')byId('gameClock').textContent='Game '+String(m.hours).padStart(2,'0')+':'+String(m.minutes).padStart(2,'0');
 if(m.type==='clockHistory'&&m.data&&m.data.ok){const onDuty=!!m.data.active||m.data.sessions.some(p=>p.status==='active');byId('clockIn').disabled=onDuty;byId('clockOut').disabled=!onDuty;byId('clockHistory').innerHTML=m.data.sessions.map(p=>'<div class="record"><b>'+esc(p.status==='active'?'On duty':'Completed')+' · '+esc(p.server_name||'Community')+'</b><span>'+esc(new Date(p.clocked_in_at).toLocaleString())+' → '+esc(p.clocked_out_at?new Date(p.clocked_out_at).toLocaleString():'Ongoing')+'</span><span>'+Math.floor(p.duration_seconds/3600)+'h '+Math.floor(p.duration_seconds%3600/60)+'m</span></div>').join('')||'<p>No patrol sessions yet.</p>';}
 if(m.type==='visible'&&!m.visible){byId('chatMessages').textContent='';chatPending=false;byId('chatSend').disabled=false;}
 if(m.type==='chatData'){if(m.data&&m.data.wasSend){chatPending=false;byId('chatSend').disabled=false;}if(!m.data||!m.data.ok){byId('chatMessages').textContent='';showNotice(m.data&&m.data.error||'Admin chat unavailable');return;}if(!canChat()||byId('tablet').classList.contains('hidden'))return;const feed=byId('chatMessages');const nearBottom=feed.scrollHeight-feed.scrollTop-feed.clientHeight<60;feed.innerHTML=m.data.messages.map(c=>'<div class="record"><b>'+esc(c.display_name||c.discord_username||'Admin')+'</b><span>'+esc(new Date(c.created_at).toLocaleString())+'</span><p>'+esc(c.message)+'</p></div>').join('')||'<p>No admin messages yet.</p>';if(nearBottom)feed.scrollTop=feed.scrollHeight;if(m.data.sent)byId('chatMessage').value='';}
});
byId('adminChatNav').addEventListener('click',()=>{if(canChat())send('chatRead');});
byId('chatSend').onclick=async()=>{if(!canChat()||chatPending)return;const message=byId('chatMessage').value.trim();if(!message||message.length>1000){showNotice('Enter a message between 1 and 1000 characters.');return;}chatPending=true;byId('chatSend').disabled=true;if(!await send('chatSend',{message})){chatPending=false;byId('chatSend').disabled=false;}};
setInterval(()=>{if(canChat()&&!byId('tablet').classList.contains('hidden')&&!byId('adminChat').classList.contains('hidden'))send('chatRead');},5000);
