(() => {
  const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
  let visible=false,identity=null,epoch=0,createBusy=false;
  const versions={news:0,rules:0,support:0,thread:0},drafts=new Map();
  const active=page=>visible&&!$(page).classList.contains('hidden');
  const request=async(kind,data)=>{const response=await window.communityHubRpc(kind,data);if(!response.ok)throw Error(response.error||'Request failed.');return response;};
  const capture=page=>({epoch,version:++versions[page]});
  const valid=(page,token)=>epoch===token.epoch&&versions[page]===token.version&&active(page==='thread'?'support':page);
  const date=value=>new Date(value).toLocaleDateString();
  function entry(title,meta,body){const article=el('article');article.className='hub-entry';article.append(el('h3',title),el('small',meta));if(body){const text=el('p',body);text.className='hub-text';article.append(text);}return article;}
  async function news(){const token=capture('news');$('newsStatus').textContent='Loading news…';$('newsArticle').classList.add('hidden');
    try{const data=await request('newsRead',{q:$('newsQuery').value});if(!valid('news',token))return;$('newsList').replaceChildren(...data.posts.map(p=>{const a=entry(p.title,p.category+' · '+date(p.published_at),p.summary);const b=el('button','Read update');b.className='secondary';b.onclick=()=>readPost(p.id);a.append(b);return a;}));$('newsStatus').textContent=data.posts.length?'':'No published updates match this search.';}
    catch(e){if(valid('news',token))$('newsStatus').textContent=e.message;}
  }
  async function readPost(id){const token=capture('news');$('newsStatus').textContent='Loading update…';try{const data=await request('newsPost',{post_id:id});if(!valid('news',token))return;const p=data.post,back=el('button','Back to news');back.className='secondary';back.onclick=()=>{$('newsArticle').classList.add('hidden');$('newsList').classList.remove('hidden');};$('newsArticle').replaceChildren(back,entry(p.title,p.category+' · '+date(p.published_at),p.body));$('newsList').classList.add('hidden');$('newsArticle').classList.remove('hidden');$('newsStatus').textContent='';}catch(e){if(valid('news',token))$('newsStatus').textContent=e.message;}}
  async function rules(){const token=capture('rules');$('rulesStatus').textContent='Loading rules…';try{const data=await request('rulesRead',{q:$('rulesQuery').value});if(!valid('rules',token))return;const groups=[];for(const category of new Set(data.rules.map(r=>r.category))){const section=el('section');section.append(el('h3',category));for(const r of data.rules.filter(r=>r.category===category)){const details=el('details');details.className='hub-rule';details.open=!!$('rulesQuery').value;const body=el('p',r.body);body.className='hub-text';details.append(el('summary',r.title),body,el('small','Updated '+date(r.updated_at)));section.append(details);}groups.push(section);}$('rulesList').replaceChildren(...groups);$('rulesStatus').textContent=data.rules.length?'':'No published rules match this search.';}catch(e){if(valid('rules',token))$('rulesStatus').textContent=e.message;}}
  async function tickets(){const token=capture('support');$('supportStatus').textContent='Loading your tickets…';try{const data=await request('ticketsRead',{});if(!valid('support',token))return;$('ticketList').replaceChildren(...data.tickets.map(t=>{const a=entry('#'+t.id+' · '+t.subject,t.category+' · '+t.status.replaceAll('_',' ')+' · '+date(t.updated_at));const b=el('button','Open conversation');b.className='secondary';b.onclick=()=>thread(t.id);a.append(b);return a;}));$('supportStatus').textContent=data.tickets.length?'':'You have no support tickets yet.';}catch(e){if(valid('support',token)){$('ticketList').replaceChildren();$('ticketThread').replaceChildren();$('ticketThread').classList.add('hidden');$('supportStatus').textContent=e.message;}}}
  async function thread(id){const token=capture('thread');$('supportStatus').textContent='Loading conversation…';try{const data=await request('ticketsRead',{ticket_id:id});if(!valid('thread',token))return;const t=data.ticket,back=el('button','Close conversation');back.className='secondary';back.onclick=()=>{versions.thread++;$('ticketThread').classList.add('hidden');};const parts=[back,entry('#'+t.id+' · '+t.subject,t.status.replaceAll('_',' '))];for(const m of data.messages)parts.push(entry(m.display_name||'Former member',(m.is_staff?'Support staff':'Member')+' · '+new Date(m.created_at).toLocaleString(),m.message));
    if(t.status!=='closed'){const form=el('form'),label=el('label','Reply'),input=el('textarea'),button=el('button','Send reply');input.required=true;input.maxLength=10000;input.value=drafts.get(id)||'';input.id='ticketReply';input.oninput=()=>drafts.set(id,input.value);label.htmlFor=input.id;button.type='submit';form.append(label,input,button);let busy=false;form.onsubmit=async e=>{e.preventDefault();if(busy||!form.reportValidity())return;busy=true;button.disabled=true;try{await request('ticketReply',{ticket_id:id,message:input.value});if(!valid('thread',token))return;drafts.delete(id);$('supportStatus').textContent='Reply sent.';await thread(id);}catch(error){if(valid('thread',token))$('supportStatus').textContent=error.message;}finally{busy=false;button.disabled=false;}};parts.push(form);}else parts.push(el('p','This ticket is closed. Support staff can reopen it on the website.'));
    $('ticketThread').replaceChildren(...parts);$('ticketThread').classList.remove('hidden');$('supportStatus').textContent='';
  }catch(e){if(valid('thread',token))$('supportStatus').textContent=e.message;}}
  $('newsSearch').onsubmit=e=>{e.preventDefault();$('newsList').classList.remove('hidden');news();};$('rulesSearch').onsubmit=e=>{e.preventDefault();rules();};$('ticketRefresh').onclick=tickets;
  $('ticketCreateForm').onsubmit=async e=>{e.preventDefault();const form=e.target;if(createBusy||!form.reportValidity())return;createBusy=true;const token={epoch},button=form.querySelector('button[type=submit]');button.disabled=true;$('supportStatus').textContent='Submitting ticket…';try{const data=await request('ticketCreate',{subject:$('ticketSubject').value,category:$('ticketCategory').value,message:$('ticketMessage').value});if(token.epoch!==epoch)return;form.reset();$('supportStatus').textContent='Ticket #'+data.ticket_id+' created.';if(active('support')){await tickets();await thread(data.ticket_id);}}catch(error){if(token.epoch===epoch)$('supportStatus').textContent=error.message;}finally{createBusy=false;button.disabled=false;}};
  const load={news,rules,support:tickets};for(const page of Object.keys(load))document.querySelector('.tablet-tabs [data-page="'+page+'"]').addEventListener('click',()=>{if(active(page)){if(page==='news')$('newsList').classList.remove('hidden');load[page]();}});
  function clearPrivate(){epoch++;drafts.clear();$('ticketList').replaceChildren();$('ticketThread').replaceChildren();$('ticketThread').classList.add('hidden');$('ticketCreateForm').reset();$('supportStatus').textContent='';}
  window.addEventListener('message',event=>{const m=event.data;if(m.type==='profile'){const next=m.data?.player?.id||null;if(identity!==next){identity=next;clearPrivate();if(active('support'))tickets();}}if(m.type==='visible'){visible=!!m.visible;if(!visible){epoch++;$('ticketList').replaceChildren();$('ticketThread').replaceChildren();$('ticketThread').classList.add('hidden');}else for(const page of Object.keys(load))if(active(page))load[page]();}});
})();
