window.CommunityOperations={mount(root,transport){const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];let state=null,busy=false,revision=0;const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};const notice=text=>$('[data-ops-notice]').textContent=text;
 async function action(data){if(busy)return;busy=true;all('button').forEach(b=>b.disabled=true);try{const response=await transport.action(data);if(!response.ok)throw Error(response.error);notice('Saved.');await refresh();return true;}catch(e){notice(e.message||'Action unavailable.');return false;}finally{busy=false;all('button').forEach(b=>b.disabled=false);}}
 function tab(name){all('[data-ops-page]').forEach(e=>e.hidden=e.dataset.opsPage!==name);all('[data-ops-tab]').forEach(e=>{if(e.dataset.opsTab===name)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current');});}all('[data-ops-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.opsTab));tab('dispatch');
 const map=CommunityPostalMap.mount($('[data-ops-map]'),{url:transport.postalUrl,onRoute:transport.routeAllowed?postal_code=>action({action:'routePostal',postal_code}):null});
 const button=(label,fn)=>{const b=node('button',label);b.type='button';b.onclick=fn;return b;};
 function render(data){state=data;all('[data-ops-command]').forEach(e=>e.hidden=!data.can_manage);if($('[data-ops-tab=reports]'))$('[data-ops-tab=reports]').hidden=!data.can_review;$('[data-ops-tab=dispatch]').hidden=!data.features.dispatch;$('[data-ops-tab=cad]').hidden=!data.features.cad;if((!data.features.dispatch&&!$('[data-ops-page=dispatch]').hidden)||(!data.features.cad&&!$('[data-ops-page=cad]').hidden)||(!data.can_review&&$('[data-ops-page=reports]')&&!$('[data-ops-page=reports]').hidden))tab(data.features.dispatch?'dispatch':data.features.cad?'cad':'reports');
  const calls=data.calls.filter(c=>c.status==='open');const callNodes=calls.map(c=>{const e=node('article',undefined,'ops-record '+(c.panic_user_id?'panic':''));e.append(node('strong',c.priority+' · #'+c.id+' · '+c.title),node('small',(c.location||'Location not provided')+' · Postal '+(c.postal_code||'unavailable')),node('p',c.description||''));const assigned=data.assignments.filter(a=>a.call_id===c.id&&a.status!=='cleared');e.append(node('small',assigned.map(a=>(a.callsign||a.display_name)+' · '+a.status.replaceAll('_',' ')).join(' / ')||'No assigned units'));const actions=node('div',undefined,'ops-actions');for(const [label,status]of [['Respond','enroute'],['On scene','on_scene'],['Clear','cleared']])actions.append(button(label,()=>action({action:'respond',call_id:c.id,status})));if(transport.routeAllowed&&c.position_x!==null&&c.position_y!==null)actions.append(button('Route',()=>action({action:'route',call_id:c.id})));if(data.can_manage){const select=node('select');select.append(new Option('Select an active unit',''));data.units.filter(u=>u.user_id).forEach(u=>select.append(new Option(u.callsign||u.player_name,u.user_id)));actions.append(select,button('Assign',()=>select.value&&action({action:'assign',call_id:c.id,user_id:select.value})),button('Close call',()=>action({action:'closeCall',call_id:c.id})));}e.append(actions);return e;});$('[data-ops-calls]').replaceChildren(...(callNodes.length?callNodes:[node('p','No active calls.','ops-muted')]));
  $('[data-ops-units]').replaceChildren(...data.units.map(u=>{const p=node('p',(u.callsign||u.player_name)+' · '+(u.department||'Unassigned')+' · '+u.duty_status+' · Postal '+(u.postal_code||'unavailable'),'ops-muted');if(u.position_x===null||u.position_y===null)p.append(' · GPS unavailable');return p;}));
  map.update(data);
  $('[data-ops-bolos]').replaceChildren(...(data.bolos.length?data.bolos.map(b=>{const e=node('article',undefined,'ops-record');e.append(node('strong','#'+b.id+' · '+b.title),node('p',b.description),node('small',[b.person_name,b.plate].filter(Boolean).join(' · ')));if(data.can_manage)e.append(button('Close BOLO',()=>action({action:'closeBolo',bolo_id:b.id})));return e;}):[node('p','No active BOLOs.','ops-muted')]));
  if($('[data-ops-reports]'))$('[data-ops-reports]').replaceChildren(...data.reports.map(r=>{const e=node('article',undefined,'ops-record');e.append(node('strong','#'+r.id+' · '+r.subject),node('p',r.details),node('small',r.status));const select=node('select');['open','under_review','actioned','closed'].forEach(s=>select.append(new Option(s.replaceAll('_',' '),s)));select.value=r.status;e.append(select,button('Update report',()=>action({action:'reportStatus',report_id:r.id,status:select.value})));return e;}));
  $('[data-ops-history]').replaceChildren(...data.calls.filter(c=>c.status==='closed').map(c=>node('p','#'+c.id+' · '+c.title+' · closed','ops-muted')),...data.events.map(e=>node('p','#'+e.call_id+' · '+(e.display_name||'Member')+' · '+e.event+' · '+new Date(e.created_at).toLocaleString(),'ops-muted')));transport.onState?.(data);}
 async function refresh(){const current=++revision;try{const data=await transport.read();if(current!==revision)return;if(!data.ok)throw Error(data.error);render(data);notice('Updated '+new Date().toLocaleTimeString());}catch(e){if(current!==revision)return;state=null;all('[data-ops-command]').forEach(n=>n.hidden=true);for(const selector of ['[data-ops-calls]','[data-ops-units]','[data-ops-bolos]','[data-ops-reports]','[data-ops-history]','[data-ops-search-results]'])$(selector)?.replaceChildren();map.clear();transport.onUnavailable?.();notice(e.message||'Operations unavailable.');}}all('[data-ops-form]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.action=form.dataset.opsForm;if(await action(data))form.reset();});$('[data-ops-search]').onsubmit=async e=>{e.preventDefault();try{const data=await transport.search(new FormData(e.target).get('q'));if(!data.ok){$('[data-ops-search-results]').replaceChildren();throw Error(data.error);}$('[data-ops-search-results]').replaceChildren(...data.people.map(p=>{const e=node('article',undefined,'ops-record');e.append(node('strong','Person #'+p.id+' · '+p.name),node('small','DOB '+(p.dob?new Date(p.dob).toLocaleDateString():'Unknown')+' · License '+p.license_status),node('p',p.notes||''));return e;}),...data.vehicles.map(v=>{const e=node('article',undefined,'ops-record');e.append(node('strong','Vehicle #'+v.id+' · '+v.plate+' · '+v.model),node('small',(v.color||'')+' · Owner '+(v.owner_name||'Unknown')),node('p',v.notes||''));return e;}));if(!data.people.length&&!data.vehicles.length)$('[data-ops-search-results]').append(node('p','No matching records.','ops-muted'));}catch(e){notice(e.message);}};return {refresh,action};}};
