window.CommunityPostalMap={mount(svg,options={}){const root=svg.parentElement,ns='http://www.w3.org/2000/svg';let postals=[],units=[],calls=[],selected=null,view={x:0,y:2500,width:18000},pan=null;const $=s=>root.querySelector(s);const message=text=>{const n=$('[data-postal-status]');if(n)n.textContent=text;};
const mark=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));if(text!==undefined)n.textContent=text;svg.append(n);return n;};const bounds=()=>({left:view.x-view.width/2,bottom:view.y-view.width*.7/2,height:view.width*.7});
function project(x,y){const b=bounds();return [(x-b.left)/view.width*600,420-(y-b.bottom)/b.height*420];}
function render(){svg.replaceChildren();for(let x=0;x<=600;x+=60)mark('line',{x1:x,y1:0,x2:x,y2:420});for(let y=0;y<=420;y+=42)mark('line',{x1:0,y1:y,x2:600,y2:y});for(const p of postals){const [x,y]=project(p.x,p.y);if(x<0||x>600||y<20||y>400)continue;const dot=mark('circle',{cx:x,cy:y,r:selected?.code===p.code?5:2,class:'postal-point'});const title=document.createElementNS(ns,'title');title.textContent='Postal '+p.code;dot.append(title);if(view.width<=4500||selected?.code===p.code)mark('text',{x:x+4,y:y-4,class:'postal-code'},p.code);dot.addEventListener('click',()=>select(p));}
for(const p of [...units.map(u=>({...u,label:u.callsign||u.player_name})),...calls.filter(c=>c.status==='open').map(c=>({...c,label:'#'+c.id,call:true}))]){if(!Number.isFinite(p.position_x)||!Number.isFinite(p.position_y))continue;const [x,y]=project(p.position_x,p.position_y);if(x<0||x>600||y<0||y>420)continue;const dot=mark('circle',{cx:x,cy:y,r:p.call?7:5,class:p.call?'call-marker':'unit-marker'});const title=document.createElementNS(ns,'title');title.textContent=p.label+' · Postal '+(p.postal_code||CommunityPostals.nearest(postals,p.position_x,p.position_y)?.code||'unavailable');dot.append(title);mark('text',{x:x+8,y:y-8,class:'unit-label'},p.label);}
mark('text',{x:10,y:16,class:'map-axis'},'North ↑ · nearest-postal');mark('text',{x:10,y:412,class:'map-axis'},'Zoom '+Math.round(18000/view.width*100)+'% · Drag to pan · '+postals.length+' postals');}
function select(p){selected=p;view={x:p.x,y:p.y,width:1600};const input=$('[data-postal-search]');if(input)input.value=p.code;const route=$('[data-postal-route]');if(route)route.disabled=false;message('Postal '+p.code+' · X '+Math.round(p.x)+' / Y '+Math.round(p.y));render();}
function find(){const p=CommunityPostals.byCode(postals,$('[data-postal-search]')?.value);if(p)select(p);else message(postals.length?'Postal not found.':'Postal data is not available yet.');}
const findButton=$('[data-postal-find]');if(findButton)findButton.onclick=find;const input=$('[data-postal-search]');if(input)input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();find();}});
for(const [selector,factor]of [['[data-postal-zoom-in]',.6],['[data-postal-zoom-out]',1/.6]]){const b=$(selector);if(b)b.onclick=()=>{view.width=Math.max(400,Math.min(30000,view.width*factor));render();};}const reset=$('[data-postal-reset]');if(reset)reset.onclick=()=>{view={x:0,y:2500,width:18000};selected=null;message('Find a postal or zoom in to show its number.');render();};
const route=$('[data-postal-route]');if(route){route.hidden=!options.onRoute;route.disabled=true;route.onclick=()=>{if(selected)options.onRoute(selected.code);};}
svg.style.touchAction='none';svg.addEventListener('pointerdown',e=>{if(e.target.tagName==='circle')return;pan={x:e.clientX,y:e.clientY,view:{...view}};svg.setPointerCapture(e.pointerId);});svg.addEventListener('pointermove',e=>{if(!pan)return;const rect=svg.getBoundingClientRect();view.x=pan.view.x-(e.clientX-pan.x)/rect.width*view.width;view.y=pan.view.y+(e.clientY-pan.y)/rect.height*view.width*.7;render();});svg.addEventListener('pointerup',()=>pan=null);svg.addEventListener('pointercancel',()=>pan=null);
fetch(options.url||'/data/postals.json').then(r=>{if(!r.ok)throw Error('Postal map unavailable');return r.json();}).then(rows=>{postals=CommunityPostals.normalize(rows);if(!postals.length)throw Error('Postal map is empty');message('Find a postal or zoom in to show its number.');render();}).catch(e=>message(e.message));render();return {update(data){units=data.units||[];calls=data.calls||[];render();},clear(){units=[];calls=[];render();}};
}};
