require('dotenv').config();
const express=require('express');
const session=require('express-session');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const path=require('path');
const fs=require('fs');
const pool=require('./src/db');
const app=express();
const PORT=Number(process.env.PORT||3020);
const uploadDir=path.resolve(process.env.UPLOAD_DIR||'storage/uploads'); fs.mkdirSync(uploadDir,{recursive:true});
app.set('view engine','ejs'); app.set('views',path.join(__dirname,'views'));
app.use(helmet({contentSecurityPolicy:false}));
app.use(rateLimit({windowMs:15*60*1000,limit:500}));
app.use(express.urlencoded({extended:true})); app.use(express.json()); app.use(express.static(path.join(__dirname,'public')));
app.use(session({secret:process.env.SESSION_SECRET||'change-this',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*12}}));
app.use((req,res,next)=>{res.locals.user=req.session.user||null;next();});
app.get('/',async(req,res)=>{let stats={applications:0,reports:0,events:0,documents:0};try{const [[a],[r],[e],[d]]=await Promise.all([pool.query('SELECT COUNT(*) count FROM applications'),pool.query('SELECT COUNT(*) count FROM reports'),pool.query('SELECT COUNT(*) count FROM calendar_events WHERE start_at>=NOW()'),pool.query('SELECT COUNT(*) count FROM documents')]);stats={applications:a[0].count,reports:r[0].count,events:e[0].count,documents:d[0].count};}catch{}res.render('index',{stats});});
app.use('/auth',require('./src/routes/auth'));
app.use('/account',require('./src/routes/account'));
app.use('/applications',require('./src/routes/applications'));
app.use('/reports',require('./src/routes/reports'));
app.use('/calendar',require('./src/routes/calendar'));
app.use('/documents',require('./src/routes/documents'));
app.use('/admin',require('./src/routes/admin'));
app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:true});}catch(e){res.status(503).json({ok:false,database:false});}});
app.use((req,res)=>res.status(404).render('message',{title:'Page not found',message:'The page you requested could not be found.'}));
app.listen(PORT,()=>console.log(`[Community Hub] http://127.0.0.1:${PORT}`));