const express=require('express');
const bcrypt=require('bcrypt');
const crypto=require('crypto');
const axios=require('axios');
const pool=require('../db');
const router=express.Router();

function requireAuth(req,res,next){if(!req.session.user)return res.redirect('/auth/login');next();}
function safeUser(row){return {id:row.id,username:row.username,display_name:row.display_name,email:row.email,discord_id:row.discord_id,avatar_url:row.avatar_url,role:row.role};}

router.get('/login',(req,res)=>res.render('auth/login',{error:req.query.error||null}));
router.get('/register',(req,res)=>res.render('auth/register',{error:null}));
router.post('/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase();const username=String(req.body.username||'').trim();const password=String(req.body.password||'');if(!email||!username||password.length<8)return res.status(400).render('auth/register',{error:'Enter a username, valid email and password of at least 8 characters.'});const [exists]=await pool.query('SELECT id FROM users WHERE email=? LIMIT 1',[email]);if(exists.length)return res.status(409).render('auth/register',{error:'An account with that email already exists.'});const hash=await bcrypt.hash(password,12);const [result]=await pool.query('INSERT INTO users(username,display_name,email,password_hash,email_verified) VALUES(?,?,?,?,0)',[username,username,email,hash]);const [rows]=await pool.query('SELECT * FROM users WHERE id=?',[result.insertId]);req.session.user=safeUser(rows[0]);res.redirect('/account');}catch(e){console.error(e);res.status(500).render('auth/register',{error:'Unable to create the account.'});}});
router.post('/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase();const password=String(req.body.password||'');const [rows]=await pool.query('SELECT * FROM users WHERE email=? AND is_active=1 LIMIT 1',[email]);if(!rows.length||!rows[0].password_hash||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).render('auth/login',{error:'Invalid email or password.'});req.session.user=safeUser(rows[0]);res.redirect('/account');}catch(e){console.error(e);res.status(500).render('auth/login',{error:'Unable to sign in.'});}});

function beginDiscord(req,res,mode){if(!process.env.DISCORD_CLIENT_ID||!process.env.DISCORD_CALLBACK_URL)return res.redirect('/auth/login?error=Discord+OAuth+is+not+configured');const state=crypto.randomBytes(24).toString('hex');req.session.discordOAuth={state,mode};const p=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,redirect_uri:process.env.DISCORD_CALLBACK_URL,response_type:'code',scope:'identify email',state,prompt:'consent'});res.redirect(`https://discord.com/oauth2/authorize?${p}`);}
router.get('/discord',(req,res)=>beginDiscord(req,res,'login'));
router.get('/discord/link',requireAuth,(req,res)=>beginDiscord(req,res,'link'));
router.get('/discord/callback',async(req,res)=>{try{const pending=req.session.discordOAuth;if(!pending||!req.query.state||req.query.state!==pending.state||!req.query.code)return res.redirect('/auth/login?error=Discord+authentication+failed');delete req.session.discordOAuth;const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code:String(req.query.code),redirect_uri:process.env.DISCORD_CALLBACK_URL});const token=await axios.post('https://discord.com/api/oauth2/token',body,{headers:{'Content-Type':'application/x-www-form-urlencoded'}});const profile=(await axios.get('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${token.data.access_token}`}})).data;const avatar=profile.avatar?`https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.png`:null;
if(pending.mode==='link'){const [used]=await pool.query('SELECT id FROM users WHERE discord_id=? AND id<>? LIMIT 1',[profile.id,req.session.user.id]);if(used.length)return res.redirect('/account?error=That+Discord+account+is+already+linked');await pool.query('UPDATE users SET discord_id=?,discord_username=?,avatar_url=? WHERE id=?',[profile.id,profile.username,avatar,req.session.user.id]);const [rows]=await pool.query('SELECT * FROM users WHERE id=?',[req.session.user.id]);req.session.user=safeUser(rows[0]);return res.redirect('/account?linked=1');}
const [existing]=await pool.query('SELECT * FROM users WHERE discord_id=? LIMIT 1',[profile.id]);let user;if(existing.length){user=existing[0];}else{const email=profile.email?String(profile.email).toLowerCase():null;let byEmail=[];if(email)[byEmail]=await pool.query('SELECT * FROM users WHERE email=? LIMIT 1',[email]);if(byEmail.length){await pool.query('UPDATE users SET discord_id=?,discord_username=?,avatar_url=? WHERE id=?',[profile.id,profile.username,avatar,byEmail[0].id]);[user]=(await pool.query('SELECT * FROM users WHERE id=?',[byEmail[0].id]))[0];}else{const [result]=await pool.query('INSERT INTO users(discord_id,discord_username,username,display_name,avatar_url,email,email_verified) VALUES(?,?,?,?,?,?,?)',[profile.id,profile.username,profile.username,profile.global_name||profile.username,avatar,email,profile.verified?1:0]);[user]=(await pool.query('SELECT * FROM users WHERE id=?',[result.insertId]))[0];}}
req.session.user=safeUser(user);res.redirect('/account');}catch(e){console.error('[Discord OAuth]',e.response?.data||e);res.redirect('/auth/login?error=Discord+authentication+failed');}});
router.post('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/')));
module.exports=router;