const router=require('express').Router();const crypto=require('crypto');const db=require('../db');const {requireRoles}=require('../middleware/auth');router.use(requireRoles(['admin','management','owner']));
router.get('/live',async(req,res)=>{const [[stats]]=await db.query("SELECT COUNT(*) patrols,COALESCE(SUM(TIMESTAMPDIFF(MINUTE,clocked_in_at,COALESCE(clocked_out_at,NOW()))),0) patrol_minutes,COUNT(DISTINCT user_id) unique_members FROM patrol_sessions WHERE clocked_in_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");res.set('Cache-Control','no-store');res.json({ok:true,...await require('../services/fivemStatus').snapshot(),stats:{patrols:stats.patrols,patrol_hours:Math.round(stats.patrol_minutes/60)+'h',unique_members:stats.unique_members}});});
router.get('/',async(req,res)=>{const [servers]=await db.query('SELECT * FROM fivem_servers ORDER BY id');const [keys]=await db.query('SELECT k.id,k.name,k.key_prefix,k.is_active,k.last_used_at,k.created_at,s.name server_name FROM fivem_api_keys k LEFT JOIN fivem_servers s ON s.id=k.server_id ORDER BY k.created_at DESC');const [announcements]=await db.query('SELECT * FROM fivem_announcements ORDER BY created_at DESC LIMIT 25');const [[stats]]=await db.query("SELECT COUNT(*) patrols,COALESCE(SUM(TIMESTAMPDIFF(MINUTE,clocked_in_at,COALESCE(clocked_out_at,NOW()))),0) patrol_minutes,COUNT(DISTINCT user_id) unique_members FROM patrol_sessions WHERE clocked_in_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)");res.render('admin/fivem',{servers,keys,announcements,stats,newApiKey:req.session.newFivemApiKey||null});delete req.session.newFivemApiKey;});
const {validate}=require('../services/fivemServerConfig');
function configurationError(res,e,next){if(e.code==='ER_DUP_ENTRY')return res.status(409).render('message',{title:'Server key already exists',message:'Choose a unique server key for each FiveM server.'});if(e.status)return res.status(e.status).render('message',{title:'Check server configuration',message:e.message});next(e);}
router.post('/servers',async(req,res,next)=>{try{const c=validate(req.body,true);await db.query('INSERT INTO fivem_servers(name,server_key,hostname,max_players,framework,connect_url,restart_schedule,is_enabled) VALUES(?,?,?,?,?,?,?,?)',[c.name,c.server_key,c.hostname,c.max_players,c.framework,c.connect_url,c.restart_schedule,c.is_enabled]);res.redirect('/admin/fivem#servers');}catch(e){configurationError(res,e,next);}});
router.post('/servers/:id',async(req,res,next)=>{try{if(!/^[1-9][0-9]*$/.test(req.params.id))return res.status(400).render('message',{title:'Invalid server',message:'Select a configured server.'});const c=validate(req.body);const [result]=await db.query('UPDATE fivem_servers SET name=?,hostname=?,max_players=?,framework=?,connect_url=?,restart_schedule=?,is_enabled=? WHERE id=?',[c.name,c.hostname,c.max_players,c.framework,c.connect_url,c.restart_schedule,c.is_enabled,req.params.id]);if(!result.affectedRows)return res.status(404).render('message',{title:'Server not found',message:'This server no longer exists.'});res.redirect('/admin/fivem#servers');}catch(e){configurationError(res,e,next);}});
router.post('/api-keys',async(req,res,next)=>{try{const raw='ch_fivem_'+crypto.randomBytes(32).toString('hex');const hash=crypto.createHash('sha256').update(raw).digest('hex');const prefix=raw.slice(0,16);await db.query('INSERT INTO fivem_api_keys(name,key_prefix,key_hash,server_id,created_by) VALUES(?,?,?,?,?)',[req.body.name||'FiveM Server',prefix,hash,req.body.server_id||null,req.session.user.id]);req.session.newFivemApiKey=raw;res.redirect('/admin/fivem');}catch(e){next(e);}});
router.post('/api-keys/:id/revoke',async(req,res,next)=>{try{await db.query('UPDATE fivem_api_keys SET is_active=0 WHERE id=?',[req.params.id]);res.redirect('/admin/fivem');}catch(e){next(e);}});
router.post('/announcements',async(req,res,next)=>{try{await db.query('INSERT INTO fivem_announcements(title,message,priority,is_active,created_by,expires_at) VALUES(?,?,?,?,?,?)',[req.body.title,req.body.message,['important','critical'].includes(req.body.priority)?req.body.priority:'info',1,req.session.user.id,req.body.expires_at||null]);res.redirect('/admin/fivem');}catch(e){next(e);}});module.exports=router;