const router=require('express').Router();const db=require('../db');const {requireAuth,requireRoles,DEPARTMENT_HEAD_ROLES}=require('../middleware/auth');const ROLES=[...new Set([...(DEPARTMENT_HEAD_ROLES||[]),'staff','admin','management','owner'])];router.use(requireAuth,requireRoles(ROLES));function slug(v){return String(v||'course').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,180)||'course';}
router.get('/',async(req,res,next)=>{try{const [courses]=await db.query(`SELECT c.*,d.name department_name,(SELECT COUNT(*) FROM lms_modules m WHERE m.course_id=c.id) module_count,(SELECT COUNT(*) FROM lms_enrollments e WHERE e.course_id=c.id) enrollment_count FROM lms_courses c LEFT JOIN departments d ON d.id=c.department_id ORDER BY c.updated_at DESC`);const [departments]=await db.query('SELECT id,name FROM departments WHERE is_active=1 ORDER BY name');const [certifications]=await db.query('SELECT id,name FROM certifications ORDER BY name');res.render('lms/admin',{courses,departments,certifications});}catch(e){next(e);}});
router.post('/courses',async(req,res,next)=>{try{const title=String(req.body.title||'').trim();if(!title)return res.status(400).send('Course title is required');let s=slug(req.body.slug||title);const [[exists]]=await db.query('SELECT id FROM lms_courses WHERE slug=?',[s]);if(exists)s=`${s}-${Date.now().toString().slice(-6)}`;const [r]=await db.query(`INSERT INTO lms_courses(department_id,title,slug,description,status,passing_score,estimated_minutes,certification_id,certificate_valid_days,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`,[req.body.department_id||null,title,s,String(req.body.description||'').trim()||null,'draft',req.body.passing_score||null,req.body.estimated_minutes||null,req.body.certification_id||null,req.body.certificate_valid_days||null,req.session.user.id]);res.redirect(`/lms/admin/courses/${r.insertId}`);}catch(e){next(e);}});
router.get('/courses/:id',async(req,res,next)=>{try{const [[course]]=await db.query('SELECT * FROM lms_courses WHERE id=?',[req.params.id]);if(!course)return res.status(404).send('Course not found');const [modules]=await db.query('SELECT * FROM lms_modules WHERE course_id=? ORDER BY sort_order,id',[course.id]);const [lessons]=modules.length?await db.query(`SELECT * FROM lms_lessons WHERE module_id IN (${modules.map(()=>'?').join(',')}) ORDER BY sort_order,id`,modules.map(m=>m.id)):[[]];const assessments={};for(const l of lessons.filter(l=>l.lesson_type==='quiz'))assessments[l.id]=await require('../services/lms').assessment(db,l.id,true);const [certifications]=await db.query('SELECT id,name FROM certifications ORDER BY name');res.render('lms/builder',{course,modules,lessons,assessments,certifications});}catch(e){next(e);}});
router.post('/courses/:id/settings',async(req,res,next)=>{try{await require('../services/lmsAuthoring').settings(req.params.id,req.body);res.redirect('/lms/admin/courses/'+req.params.id);}catch(e){if(e.status)return res.status(e.status).render('message',{title:'Course settings',message:e.message});next(e);}});
router.post('/courses/:courseId/lessons/:lessonId/questions',async(req,res,next)=>{try{await require('../services/lmsAuthoring').addQuestion(req.params.courseId,req.params.lessonId,req.body);res.redirect('/lms/admin/courses/'+req.params.courseId);}catch(e){if(e.status)return res.status(e.status).render('message',{title:'Assessment setup',message:e.message});next(e);}});
async function structure(req,res,next,moduleId){try{await require('../services/lmsAuthoring').addStructure(req.params.courseId||req.params.id,moduleId,req.body);res.redirect('/lms/admin/courses/'+(req.params.courseId||req.params.id));}catch(e){if(e.status)return res.status(e.status).render('message',{title:'Course materials',message:e.message});next(e);}}
router.post('/courses/:id/modules',(req,res,next)=>structure(req,res,next,null));
router.post('/courses/:courseId/modules/:moduleId/lessons',(req,res,next)=>structure(req,res,next,req.params.moduleId));
module.exports=router;
