const router=require('express').Router();const db=require('../db');const {requireRoles}=require('../middleware/auth');
const MANAGE=['department_command','staff','admin','management','owner'];router.use(requireRoles(MANAGE));
router.get('/',async(req,res)=>{const [departments]=await db.query('SELECT d.*,u.display_name head_name FROM departments d LEFT JOIN users u ON u.id=d.department_head_user_id ORDER BY d.name');const [loa]=await db.query("SELECT l.*,u.display_name,u.discord_username FROM loa_requests l JOIN users u ON u.id=l.user_id WHERE l.status='pending' ORDER BY l.created_at");const [certs]=await db.query('SELECT c.*,d.name department_name FROM certifications c LEFT JOIN departments d ON d.id=c.department_id ORDER BY c.name');const [audit]=await db.query('SELECT a.*,u.display_name FROM audit_logs_v2 a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 50');res.render('admin/management',{departments,loa,certs,audit});});
router.post('/departments',requireRoles(['admin','management','owner']),async(req,res,next)=>{try{const slug=String(req.body.slug||req.body.name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');await db.query('INSERT INTO departments(name,slug,description,is_active,discord_role_id,recruit_discord_role_id,member_discord_role_id) VALUES(?,?,?,1,?,?,?)',[req.body.name,slug,req.body.description||null,req.body.discord_role_id||null,req.body.recruit_discord_role_id||null,req.body.member_discord_role_id||null]);await audit(req,'department.create','department',null,{name:req.body.name});res.redirect('/admin/management');}catch(e){next(e);}});
router.post('/departments/:id/ranks',async(req,res,next)=>{try{await db.query('INSERT INTO department_ranks(department_id,name,sort_order,discord_role_id,is_command) VALUES(?,?,?,?,?)',[req.params.id,req.body.name,Number(req.body.sort_order||0),req.body.discord_role_id||null,req.body.is_command?1:0]);await audit(req,'department.rank.create','department',req.params.id,{rank:req.body.name});res.redirect('/admin/management');}catch(e){next(e);}});
router.post('/certifications',async(req,res,next)=>{try{await db.query('INSERT INTO certifications(department_id,name,description,expires_after_days) VALUES(?,?,?,?)',[req.body.department_id||null,req.body.name,req.body.description||null,req.body.expires_after_days||null]);res.redirect('/admin/management');}catch(e){next(e);}});
router.post('/certifications/:certId/award',async(req,res,next)=>{try{const [[c]]=await db.query('SELECT expires_after_days,name FROM certifications WHERE id=?',[req.params.certId]);if(!c)return res.status(404).send('Certification not found');await db.query('INSERT INTO user_certifications(user_id,certification_id,awarded_by,expires_at,notes) VALUES(?,?,?,IF(? IS NULL,NULL,DATE_ADD(NOW(),INTERVAL ? DAY)),?) ON DUPLICATE KEY UPDATE awarded_by=VALUES(awarded_by),awarded_at=NOW(),expires_at=VALUES(expires_at),notes=VALUES(notes)',[req.body.user_id,req.params.certId,req.session.user.id,c.expires_after_days,c.expires_after_days,req.body.notes||null]);await notify(req.body.user_id,`Certification awarded: ${c.name}`,'A certification was added to your personnel file.',`/personnel/${req.body.user_id}`);res.redirect(`/personnel/${req.body.user_id}`);}catch(e){next(e);}});
router.post('/loa/:id',async(req,res,next)=>{try{const status=['approved','denied'].includes(req.body.status)?req.body.status:null;if(!status)return res.status(400).send('Invalid status');const [[l]]=await db.query('SELECT user_id FROM loa_requests WHERE id=?',[req.params.id]);await db.query('UPDATE loa_requests SET status=?,reviewed_by=?,review_note=? WHERE id=?',[status,req.session.user.id,req.body.review_note||null,req.params.id]);if(l&&status==='approved')await db.query("UPDATE users SET member_status='loa' WHERE id=?",[l.user_id]);if(l)await notify(l.user_id,`LOA ${status}`,req.body.review_note||`Your LOA request was ${status}.`,'/personnel/me/loa');await audit(req,'loa.review','loa',req.params.id,{status});res.redirect('/admin/management');}catch(e){next(e);}});
router.post('/discipline/:userId',requireRoles(['staff','admin','management','owner']),async(req,res,next)=>{try{const allowed=['verbal_warning','written_warning','strike','suspension','removal','commendation','note'];if(!allowed.includes(req.body.record_type))return res.status(400).send('Invalid record type');await db.query('INSERT INTO disciplinary_records(user_id,record_type,reason,action_taken,issued_by) VALUES(?,?,?,?,?)',[req.params.userId,req.body.record_type,req.body.reason,req.body.action_taken||null,req.session.user.id]);await audit(req,'discipline.create','user',req.params.userId,{type:req.body.record_type});res.redirect(`/personnel/${req.params.userId}`);}catch(e){next(e);}});
router.get('/notifications',async(req,res)=>{const [notifications]=await db.query('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100',[req.session.user.id]);res.render('notifications/index',{notifications});});
router.post('/notifications/:id/read',async(req,res)=>{await db.query('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?',[req.params.id,req.session.user.id]);res.redirect(req.body.return_url||'/admin/management/notifications');});
async function notify(userId,title,message,url){await db.query('INSERT INTO notifications(user_id,title,message,url) VALUES(?,?,?,?)',[userId,title,message,url]);}
async function audit(req,action,type,id,metadata){try{await db.query('INSERT INTO audit_logs_v2(user_id,action,entity_type,entity_id,metadata_json,ip_address) VALUES(?,?,?,?,?,?)',[req.session.user.id,action,type,id,metadata?JSON.stringify(metadata):null,req.ip]);}catch{}}
module.exports=router;