const router=require('express').Router(),db=require('../db'),crypto=require('crypto'),multer=require('multer'),content=require('../services/publicContent'),branding=require('../services/branding');const {requireRoles}=require('../middleware/auth');
const fail=(res,status,message)=>res.status(status).render('message',{title:'Website content',message});
const admin=async(req,res,next)=>{try{const [[user]]=await db.query('SELECT role,is_active FROM users WHERE id=?',[req.session.user.id]);if(!user?.is_active||!['admin','management','owner'].includes(user.role))return fail(res,403,'Administrator access is required.');next();}catch(e){next(e);}};
const guards=[requireRoles(['admin','management','owner']),admin];
const token=req=>req.session.websiteContentToken||(req.session.websiteContentToken=crypto.randomBytes(32).toString('hex'));
const csrf=(req,res,next)=>{const a=Buffer.from(String(req.body._csrf||'')),b=Buffer.from(req.session.websiteContentToken||'');if(!b.length||a.length!==b.length||!crypto.timingSafeEqual(a,b))return fail(res,403,'Your editing session expired. Reload Website content and try again.');next();};
const imageUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:4*1024*1024,files:1,fields:8}}).single('image');
const upload=(req,res,next)=>imageUpload(req,res,e=>{if(e)return fail(res,e.code==='LIMIT_FILE_SIZE'?413:400,'Choose one PNG, JPEG or WebP image up to 4 MB.');next();});
router.get('/home',async(req,res,next)=>{try{res.render('index',{stats:await stats()});}catch(e){next(e);}});
async function stats(){const counts=await Promise.all([db.query('SELECT COUNT(*) count FROM applications'),db.query('SELECT COUNT(*) count FROM reports'),db.query('SELECT COUNT(*) count FROM calendar_events WHERE start_at>=NOW()'),db.query('SELECT COUNT(*) count FROM documents WHERE deleted_at IS NULL')]);return Object.fromEntries(['applications','reports','events','documents'].map((k,i)=>[k,counts[i][0][0].count]));}
router.get('/about',(req,res)=>res.render('public/about'));
router.get('/gallery',async(req,res,next)=>{try{const [images]=await db.query('SELECT id,title,caption,sha256 FROM community_gallery WHERE is_removed=0 AND is_published=1 ORDER BY sort_order,id DESC');res.render('public/gallery',{images});}catch(e){next(e);}});
router.get('/gallery/image/:id',async(req,res,next)=>{try{if(!/^\d+$/.test(req.params.id))return res.sendStatus(404);const [[image]]=await db.query('SELECT file_data,mime_type,sha256 FROM community_gallery WHERE id=? AND is_removed=0 AND is_published=1',[req.params.id]);if(!image)return res.sendStatus(404);res.set({'Content-Type':image.mime_type,'X-Content-Type-Options':'nosniff','Cache-Control':'public, max-age=0, must-revalidate','ETag':'"'+image.sha256+'"'});res.send(image.file_data);}catch(e){next(e);}});
router.get('/admin/website',...guards,async(req,res,next)=>{try{const [images]=await db.query('SELECT id,title,caption,sort_order,is_published,is_removed FROM community_gallery ORDER BY is_removed,sort_order,id DESC');res.render('admin/website',{content:await content.load(),images,csrf:token(req)});}catch(e){next(e);}});
router.get('/admin/website/gallery/:id/image',...guards,async(req,res,next)=>{try{if(!/^\d+$/.test(req.params.id))return res.sendStatus(404);const [[image]]=await db.query('SELECT file_data,mime_type FROM community_gallery WHERE id=?',[req.params.id]);if(!image)return res.sendStatus(404);res.set({'Content-Type':image.mime_type,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'});res.send(image.file_data);}catch(e){next(e);}});
router.post('/admin/website',...guards,csrf,async(req,res,next)=>{let value;try{value=content.validate(req.body);}catch(e){return fail(res,400,e.message);}try{await db.query('INSERT INTO site_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)',['public_website_content',JSON.stringify(value)]);res.redirect('/admin/website');}catch(e){next(e);}});
function imageFields(body){if(typeof body.title!=='string'||!body.title.trim()||body.title.trim().length>160||typeof body.caption!=='string'||body.caption.length>2000)throw Error('Provide an image title up to 160 characters and a caption up to 2,000.');const order=Number(body.sort_order||0);if(!Number.isInteger(order)||Math.abs(order)>100000)throw Error('Use a whole-number display order between -100000 and 100000.');return [body.title.trim(),body.caption.trim(),order,body.is_published==='on'?1:0];}
router.post('/admin/website/gallery',...guards,upload,csrf,async(req,res,next)=>{let values,mime;try{values=imageFields(req.body);mime=req.file&&branding.imageType(req.file.buffer);if(!mime)throw Error('Choose a PNG, JPEG or WebP image up to 4 MB.');}catch(e){return fail(res,400,e.message);}try{await db.query('INSERT INTO community_gallery(title,caption,sort_order,is_published,file_data,mime_type,sha256,created_by) VALUES(?,?,?,?,?,?,?,?)',[...values,req.file.buffer,mime,crypto.createHash('sha256').update(req.file.buffer).digest('hex'),req.session.user.id]);res.redirect('/admin/website#gallery-editor');}catch(e){next(e);}});
router.post('/admin/website/gallery/:id/:action',...guards,csrf,async(req,res,next)=>{if(!/^\d+$/.test(req.params.id))return res.sendStatus(404);try{const [[image]]=await db.query('SELECT id FROM community_gallery WHERE id=?',[req.params.id]);if(!image)return res.sendStatus(404);if(req.params.action==='save'){let values;try{values=imageFields(req.body);}catch(e){return fail(res,400,e.message);}await db.query('UPDATE community_gallery SET title=?,caption=?,sort_order=?,is_published=? WHERE id=?',[...values,req.params.id]);}else if(['remove','restore'].includes(req.params.action)){await db.query('UPDATE community_gallery SET is_removed=? WHERE id=?',[req.params.action==='remove'?1:0,req.params.id]);}else return res.sendStatus(404);res.redirect('/admin/website#gallery-editor');}catch(e){next(e);}});
module.exports=router;
