const db=require('../db'),{isGuildMember}=require('./discord'),branding=require('./branding'),identity=require('./applicationIdentity');
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
async function actor(license){const [[user]]=await db.query('SELECT id,discord_id,discord_username,is_active FROM users WHERE fivem_license=?',[license]);if(!user||!user.is_active)fail('Link your Community Hub account first.',403);return user;}
async function gate(){if(!await branding.enabled('applications'))fail('In-game applications are disabled by administrators.',403);}
async function catalog(license){await gate();const user=await actor(license);const [forms]=await db.query('SELECT id,title,slug,description FROM application_forms WHERE is_open=1 ORDER BY sort_order,title');const [history]=await db.query('SELECT a.id,a.status,a.submitted_at,f.title FROM applications a JOIN application_forms f ON f.id=a.form_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT 30',[user.id]);return {ok:true,forms,history};}
async function form(license,id){await gate();const user=await actor(license);const [[form]]=await db.query('SELECT id,title,slug,description FROM application_forms WHERE id=? AND is_open=1',[id]);if(!form)fail('This application is closed or unavailable.',404);const [questions]=await db.query('SELECT * FROM application_questions WHERE form_id=? ORDER BY sort_order,id',[id]);return {ok:true,form,questions:identity.questionsFor(questions,user)};}
function answersFor(questions,answers){return questions.map(q=>{let value=answers['q_'+q.id];let options=[];try{options=Array.isArray(q.options_json)?q.options_json:JSON.parse(q.options_json||'[]');}catch{}if(!Array.isArray(options))options=[];
 if(q.question_type==='checkbox'){value=value===undefined?[]:Array.isArray(value)?value:[value];if(value.some(v=>typeof v!=='string'||!options.includes(v)))fail('Choose valid options for '+q.label);value=[...new Set(value)].join(', ');}else{if(value!==undefined&&typeof value!=='string')fail('Invalid answer for '+q.label);value=(value||'').trim();if(value&&['select','radio'].includes(q.question_type)&&!options.includes(value))fail('Choose a valid option for '+q.label);if(value&&q.question_type==='number'&&!Number.isFinite(Number(value)))fail('Enter a number for '+q.label);if(value&&q.question_type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value))fail('Enter a valid date for '+q.label);if(value&&q.question_type==='url'){try{if(!['http:','https:'].includes(new URL(value).protocol))fail('Invalid URL');}catch{fail('Enter a valid web address for '+q.label);}}}
 if(q.is_required&&!value)fail('Answer the required question: '+q.label);if(value.length>10000)fail('Answer is too long: '+q.label);return {id:q.id,value};});}
async function submitUser(userId,slug,answers,tablet=false,requestKey=null){if(tablet)await gate();if(!answers||typeof answers!=='object'||Array.isArray(answers))fail('Invalid application answers.');if(requestKey!==null&&(typeof requestKey!=='string'||!/^[a-zA-Z0-9_-]{16,64}$/.test(requestKey)))fail('Invalid submission reference.');const [[actor]]=await db.query('SELECT id,discord_id,discord_username,is_active FROM users WHERE id=?',[userId]);if(!actor?.is_active||!actor?.discord_id)fail('A linked Discord account is required.',403);let member;try{member=await isGuildMember(actor.discord_id);}catch{fail('Discord membership check unavailable. Please try again shortly.',503);}if(!member)fail('Join the community Discord server before applying.',403);
 const conn=await db.getConnection();try{await conn.beginTransaction();const [[current]]=await conn.query('SELECT id,discord_id,discord_username,is_active FROM users WHERE id=? FOR UPDATE',[userId]);if(!current?.is_active||current.discord_id!==actor.discord_id)fail('Your account changed. Refresh and try again.',403);if(tablet){const [[flag]]=await conn.query('SELECT setting_value FROM site_settings WHERE setting_key=? FOR UPDATE',['tablet_applications_enabled']);if(flag?.setting_value!=='1')fail('In-game applications are disabled by administrators.',403);}
 const [[form]]=await conn.query('SELECT * FROM application_forms WHERE slug=? AND is_open=1 FOR UPDATE',[slug]);if(!form)fail('This application is closed or unavailable.',404);
 if(requestKey){const [[existing]]=await conn.query('SELECT id,form_id FROM applications WHERE user_id=? AND submission_key=?',[userId,requestKey]);if(existing){if(existing.form_id!==form.id)fail('Submission reference belongs to another form.',409);await conn.commit();return {ok:true,application_id:existing.id};}}
 if(Number(form.cooldown_days)>0){const [[recent]]=await conn.query('SELECT id FROM applications WHERE user_id=? AND form_id=? AND submitted_at>DATE_SUB(NOW(),INTERVAL ? DAY) LIMIT 1',[userId,form.id,Number(form.cooldown_days)]);if(recent)fail('This application has a '+form.cooldown_days+' day submission cooldown.',409);}
 const [questions]=await conn.query('SELECT * FROM application_questions WHERE form_id=? ORDER BY sort_order,id',[form.id]);const validated=answersFor(questions,identity.answersFor(questions,answers,current));const [result]=await conn.query("INSERT INTO applications(form_id,user_id,status,submitted_at,submission_key) VALUES(?,?,'submitted',NOW(),?)",[form.id,userId,requestKey]);for(const answer of validated)await conn.query('INSERT INTO application_answers(application_id,question_id,answer_text) VALUES(?,?,?)',[result.insertId,answer.id,answer.value]);await conn.query("INSERT INTO application_status_history(application_id,status,note,changed_by) VALUES(?,'submitted',?,?)",[result.insertId,tablet?'Application submitted in-game':'Application submitted',userId]);await conn.commit();return {ok:true,application_id:result.insertId};
 }catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function submit(license,data){const user=await actor(license);return submitUser(user.id,data.slug,data.answers,true,data.request_key);}
module.exports={catalog,form,submit,submitUser,answersFor};
