const db=require('../db');
async function load(){const safe=async(sql,args=[])=>{try{const [rows]=await db.query(sql,args);return rows;}catch(e){if(['ER_NO_SUCH_TABLE','ER_BAD_FIELD_ERROR'].includes(e.code))return[];throw e;}};const [loa,activity,probation,certs,training,recruits,servers,applications,reports]=await Promise.all([
safe(`SELECT l.id,l.user_id,l.start_date,l.end_date,l.reason,l.created_at,u.display_name,u.discord_username,u.callsign,d.name department_name FROM loa_requests l JOIN users u ON u.id=l.user_id LEFT JOIN departments d ON d.id=u.department_id WHERE l.status='pending' ORDER BY l.created_at LIMIT 8`),
safe(`SELECT u.id,u.display_name,u.discord_username,u.callsign,u.rank_name,d.name department_name,sp.activity_status,sp.activity_requirement_minutes,FLOOR(COALESCE(SUM(TIMESTAMPDIFF(SECOND,p.clocked_in_at,COALESCE(p.clocked_out_at,NOW()))),0)/60) patrol_minutes FROM users u JOIN staff_profiles sp ON sp.user_id=u.id LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN patrol_sessions p ON p.user_id=u.id AND p.clocked_in_at>=DATE_SUB(NOW(),INTERVAL 7 DAY) WHERE u.member_status IN('recruit','active') AND sp.activity_status<>'exempt' AND sp.activity_requirement_minutes IS NOT NULL GROUP BY u.id,u.display_name,u.discord_username,u.callsign,u.rank_name,d.name,sp.activity_status,sp.activity_requirement_minutes HAVING patrol_minutes<sp.activity_requirement_minutes ORDER BY (patrol_minutes/sp.activity_requirement_minutes) ASC LIMIT 10`),
safe(`SELECT u.id,u.display_name,u.discord_username,u.callsign,d.name department_name,sp.probation_ends_at FROM staff_profiles sp JOIN users u ON u.id=sp.user_id LEFT JOIN departments d ON d.id=u.department_id WHERE sp.probation_status IN('active','extended') AND sp.probation_ends_at IS NOT NULL AND sp.probation_ends_at<=DATE_ADD(NOW(),INTERVAL 14 DAY) ORDER BY sp.probation_ends_at LIMIT 8`),
safe(`SELECT u.id,u.display_name,u.discord_username,u.callsign,c.name certification_name,uc.expires_at FROM user_certifications uc JOIN users u ON u.id=uc.user_id JOIN certifications c ON c.id=uc.certification_id WHERE uc.expires_at IS NOT NULL AND uc.expires_at<=DATE_ADD(NOW(),INTERVAL 30 DAY) ORDER BY uc.expires_at LIMIT 10`),
safe(`SELECT t.id,t.title,t.start_at,d.name department_name,(SELECT COUNT(*) FROM training_registrations r WHERE r.training_id=t.id AND r.status='registered') roster_count FROM training_sessions t LEFT JOIN departments d ON d.id=t.department_id WHERE t.start_at BETWEEN NOW() AND DATE_ADD(NOW(),INTERVAL 7 DAY) ORDER BY t.start_at LIMIT 8`),
safe(`SELECT u.id,u.display_name,u.discord_username,u.callsign,d.name department_name,r.stage,r.created_at FROM recruit_pipeline r JOIN users u ON u.id=r.user_id LEFT JOIN departments d ON d.id=u.department_id WHERE r.id=(SELECT MAX(r2.id) FROM recruit_pipeline r2 WHERE r2.user_id=r.user_id) AND r.stage IN('accepted','recruit','training','evaluation') ORDER BY r.created_at LIMIT 10`),
safe(`SELECT id,name,current_players,max_players,last_heartbeat_at,IF(last_heartbeat_at>DATE_SUB(NOW(),INTERVAL 90 SECOND),1,0) live FROM fivem_servers WHERE is_enabled=1 ORDER BY name`),
safe(`SELECT COUNT(*) count FROM applications WHERE status IN('submitted','pending','under_review')`),
safe(`SELECT COUNT(*) count FROM reports WHERE status IN('open','pending','under_review')`)]);
const counts={loa:loa.length,activity:activity.length,probation:probation.length,certifications:certs.length,training:training.length,recruits:recruits.length,applications:Number(applications[0]?.count||0),reports:Number(reports[0]?.count||0),serversDown:servers.filter(s=>!Number(s.live)).length,players:servers.filter(s=>Number(s.live)).reduce((n,s)=>n+Number(s.current_players||0),0)};return{counts,loa,activity,probation,certifications:certs,training,recruits,servers};}
module.exports={load};