const db=require('../db'),branding=require('./branding'),postals=require('./postals');const COMMAND=['department_command','staff','admin','management','owner'],ADMINS=['admin','management','owner'];
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const eligible=u=>u.is_active!==0&&u.is_active!==false&&(COMMAND.includes(u.role)||(['recruit','member','reviewer'].includes(u.role)&&!!u.department_id));
async function actor(identity){const byLicense=typeof identity==='string';const [[u]]=await db.query('SELECT id,role,department_id,is_active,display_name,callsign FROM users WHERE '+(byLicense?'fivem_license':'id')+'=?',[identity]);if(!u||!eligible(u))fail('Operations require department membership or an authorized staff role.',403);return u;}
async function server(key){const [[s]]=await db.query('SELECT id,name FROM fivem_servers WHERE server_key=? AND is_enabled=1',[key||'primary']);if(!s)fail('Server not configured or disabled.',404);return s;}
async function state(identity,key){const u=await actor(identity),s=await server(key),brand=await branding.load();const [calls]=brand.features.dispatch?await db.query("SELECT c.*,p.display_name creator_name FROM fivem_calls c LEFT JOIN users p ON p.id=c.created_by WHERE c.server_id=? AND (c.status='open' OR c.closed_at>DATE_SUB(NOW(),INTERVAL 1 DAY)) ORDER BY FIELD(c.status,'open','closed'),FIELD(c.priority,'P1','P2','P3'),c.id DESC LIMIT 100",[s.id]):[[]];const [assignments]=brand.features.dispatch?await db.query('SELECT a.*,u.callsign,u.display_name FROM fivem_call_units a JOIN fivem_calls c ON c.id=a.call_id JOIN users u ON u.id=a.user_id WHERE c.server_id=? AND c.status=\'open\'',[s.id]):[[]];const [units]=brand.features.dispatch?await db.query("SELECT a.user_id,a.callsign,a.player_name,a.department,a.duty_status,a.position_x,a.position_y,a.position_z FROM fivem_active_units a JOIN users u ON u.id=a.user_id WHERE a.server_id=? AND a.last_seen_at>DATE_SUB(NOW(),INTERVAL 90 SECOND) AND a.duty_status<>'off_duty' AND u.is_active=1 AND (u.role IN ('department_command','staff','admin','management','owner') OR (u.role IN ('recruit','member','reviewer') AND u.department_id IS NOT NULL))",[s.id]):[[]];const [bolos]=brand.features.cad?await db.query("SELECT b.*,p.name person_name,v.plate FROM cad_bolos b LEFT JOIN cad_people p ON p.id=b.person_id LEFT JOIN cad_vehicles v ON v.id=b.vehicle_id WHERE b.status='active' ORDER BY b.id DESC LIMIT 100"):[[]];const [reports]=ADMINS.includes(u.role)?await db.query("SELECT id,subject,details,status,created_at FROM fivem_reports WHERE server_id=? ORDER BY id DESC LIMIT 50",[s.id]):[[]];const [events]=brand.features.dispatch?await db.query('SELECT e.*,u.display_name FROM fivem_call_events e JOIN fivem_calls c ON c.id=e.call_id LEFT JOIN users u ON u.id=e.actor_id WHERE c.server_id=? ORDER BY e.id DESC LIMIT 40',[s.id]):[[]];return {ok:true,user_id:u.id,can_manage:COMMAND.includes(u.role),can_review:ADMINS.includes(u.role),features:brand.features,server:s,calls:calls.map(c=>({...c,postal_code:c.postal_code||postals.nearest(c.position_x,c.position_y)?.code||null})),assignments,units:units.map(u=>({...u,postal_code:postals.nearest(u.position_x,u.position_y)?.code||null})),bolos,reports,events};}
async function search(identity,text){await actor(identity);if(!await branding.enabled('cad'))fail('CAD is disabled by administrators.',403);const q='%'+String(text||'').trim().slice(0,100)+'%';if(q==='%%')return {ok:true,people:[],vehicles:[]};const [people]=await db.query('SELECT * FROM cad_people WHERE name LIKE ? ORDER BY name LIMIT 30',[q]);const [vehicles]=await db.query('SELECT v.*,p.name owner_name FROM cad_vehicles v LEFT JOIN cad_people p ON p.id=v.owner_id WHERE v.plate LIKE ? OR v.model LIKE ? OR p.name LIKE ? ORDER BY v.plate LIMIT 30',[q,q,q]);return {ok:true,people,vehicles};}
function text(value,max,label,required=true){const v=typeof value==='string'?value.trim():'';if((required&&!v)||v.length>max)fail('Enter a valid '+label+'.');return v;}
function id(value){if(!Number.isSafeInteger(Number(value))||Number(value)<1)fail('Invalid record reference.');return Number(value);}
function coords(data){const pair=['position_x','position_y'].map(k=>{if(data[k]===undefined||data[k]===null||data[k]==='')return null;const n=Number(data[k]);if(!Number.isFinite(n)||Math.abs(n)>20000)fail('Invalid coordinates.');return n;});if((pair[0]===null)!==(pair[1]===null))fail('Provide both GPS coordinates.');return pair;}
async function action(identity,key,data){const u=await actor(identity),s=await server(key),name=data.action;if(!['createCall','panic','assign','respond','closeCall','route','createPerson','createVehicle','createBolo','closeBolo','reportStatus','routePostal'].includes(name))fail('Unknown operations action.');const management=['createCall','assign','closeCall','createPerson','createVehicle','createBolo','closeBolo'];if(management.includes(name)&&!COMMAND.includes(u.role))fail('This action requires command or staff access.',403);if(name==='reportStatus'&&!ADMINS.includes(u.role))fail('Report review requires administrator access.',403);
 const feature=['createPerson','createVehicle','createBolo','closeBolo'].includes(name)?'cad':name==='panic'?'panic':name==='reportStatus'?null:'dispatch';if(feature&&!await branding.enabled(feature))fail('This feature is disabled by administrators.',403);if(name==='panic'&&!await branding.enabled('dispatch'))fail('Dispatch is disabled by administrators.',403);
 const conn=await db.getConnection();try{await conn.beginTransaction();const [[current]]=await conn.query('SELECT id,role,department_id,is_active FROM users WHERE id=? FOR UPDATE',[u.id]);if(!current||!eligible(current)||(management.includes(name)&&!COMMAND.includes(current.role))||(name==='reportStatus'&&!ADMINS.includes(current.role)))fail('Your permissions have changed.',403);const needed=name==='panic'?['dispatch','panic']:feature?[feature]:[];for(const f of branding.FLAGS.filter(f=>needed.includes(f))){const [[flag]]=await conn.query('SELECT setting_value FROM site_settings WHERE setting_key=? FOR UPDATE',['tablet_'+f+'_enabled']);if(flag?.setting_value!=='1')fail('This feature is disabled by administrators.',403);}let result={ok:true};let callId;
 if(name==='createCall'||name==='panic'){let prior;if(name==='panic'){const [[p]]=await conn.query("SELECT id FROM fivem_calls WHERE server_id=? AND panic_user_id=? AND status='open'",[s.id,u.id]);prior=p;}if(prior){callId=prior.id;}else{let [x,y]=coords(data);if(name==='createCall'&&data.postal_code){const postal=postals.byCode(data.postal_code);if(!postal)fail('Postal not found.');if(x===null&&y===null){x=postal.x;y=postal.y;}}const postalCode=postals.nearest(x,y)?.code||null;const title=name==='panic'?'Panic · '+(u.callsign||u.display_name):text(data.title,160,'call title');const priority=name==='panic'?'P1':data.priority;if(!['P1','P2','P3'].includes(priority))fail('Invalid priority.');const [row]=await conn.query('INSERT INTO fivem_calls(server_id,title,description,location,priority,position_x,position_y,postal_code,created_by,panic_user_id,panic_open) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[s.id,title,text(data.description,5000,'description',false),text(data.location,255,'location',false),priority,x,y,postalCode,u.id,name==='panic'?u.id:null,name==='panic'?1:null]);callId=row.insertId;}result.call_id=callId;}
 else if(['assign','respond','closeCall','route'].includes(name)){callId=id(data.call_id);const [[call]]=await conn.query("SELECT * FROM fivem_calls WHERE id=? AND server_id=? AND status='open' FOR UPDATE",[callId,s.id]);if(!call)fail('This call is closed or unavailable.',404);
  if(name==='route'){if(call.position_x===null||call.position_y===null)fail('This call has no GPS coordinates.');result.waypoint={x:call.position_x,y:call.position_y};}
  else if(name==='closeCall')await conn.query("UPDATE fivem_calls SET status='closed',closed_at=NOW(),panic_open=NULL WHERE id=?",[callId]);
  else{let target=u.id;let status=data.status||'enroute';if(name==='assign'){target=id(data.user_id);const [[unit]]=await conn.query('SELECT user_id FROM fivem_active_units WHERE user_id=? AND server_id=? AND last_seen_at>DATE_SUB(NOW(),INTERVAL 90 SECOND)',[target,s.id]);if(!unit)fail('This unit is no longer active.',404);const [[targetUser]]=await conn.query('SELECT role,department_id,is_active FROM users WHERE id=?',[target]);if(!targetUser||!eligible(targetUser))fail('This unit is not authorized for dispatch.',403);status='assigned';}if(!['assigned','enroute','on_scene','cleared'].includes(status))fail('Invalid response status.');await conn.query('INSERT INTO fivem_call_units(call_id,user_id,status) VALUES(?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),updated_at=NOW()',[callId,target,status]);}
 }
 else if(name==='routePostal'){const postal=postals.byCode(data.postal_code);if(!postal)fail('Postal not found.',404);result.waypoint={x:postal.x,y:postal.y};result.postal_code=postal.code;}
 else if(name==='createPerson'){const license=['valid','suspended','revoked','unknown'].includes(data.license_status)?data.license_status:'unknown';const dob=data.dob?text(data.dob,10,'date of birth'):null;if(dob&&(!/^\d{4}-\d{2}-\d{2}$/.test(dob)||!Number.isFinite(Date.parse(dob))||new Date(dob).toISOString().slice(0,10)!==dob))fail('Invalid date of birth.');await conn.query('INSERT INTO cad_people(name,dob,license_status,notes,created_by) VALUES(?,?,?,?,?)',[text(data.name,160,'person name'),dob,license,text(data.notes,5000,'notes',false),u.id]);}
 else if(name==='createVehicle')await conn.query('INSERT INTO cad_vehicles(plate,model,color,owner_id,notes,created_by) VALUES(?,?,?,?,?,?)',[text(data.plate,16,'plate').toUpperCase(),text(data.model,120,'vehicle model'),text(data.color,80,'color',false),data.owner_id?id(data.owner_id):null,text(data.notes,5000,'notes',false),u.id]);
 else if(name==='createBolo')await conn.query('INSERT INTO cad_bolos(title,description,person_id,vehicle_id,created_by) VALUES(?,?,?,?,?)',[text(data.title,160,'BOLO title'),text(data.description,5000,'BOLO description'),data.person_id?id(data.person_id):null,data.vehicle_id?id(data.vehicle_id):null,u.id]);
 else if(name==='closeBolo')await conn.query("UPDATE cad_bolos SET status='closed' WHERE id=?",[id(data.bolo_id)]);
 else if(name==='reportStatus'){if(!['open','under_review','actioned','closed'].includes(data.status))fail('Invalid report status.');const [[report]]=await conn.query('SELECT id FROM fivem_reports WHERE id=? AND server_id=? FOR UPDATE',[id(data.report_id),s.id]);if(!report)fail('Report unavailable on this server.',404);await conn.query('UPDATE fivem_reports SET status=?,assigned_to=? WHERE id=? AND server_id=?',[data.status,u.id,id(data.report_id),s.id]);}
 else fail('Unknown operations action.');
 if(callId&&name!=='route')await conn.query('INSERT INTO fivem_call_events(call_id,actor_id,event) VALUES(?,?,?)',[callId,u.id,name+(data.status?' · '+data.status:'')]);await conn.commit();return result;
 }catch(e){await conn.rollback();if(['ER_DUP_ENTRY','ER_NO_REFERENCED_ROW_2'].includes(e.code))fail('Duplicate record or invalid linked person/vehicle.');throw e;}finally{conn.release();}}
async function reports(identity,key){const user=await actor(identity);if(!ADMINS.includes(user.role))fail('Report submissions require administrator access.',403);const s=await server(key);const [reports]=await db.query('SELECT r.id,r.report_type,r.subject,r.details,r.status,r.created_at,r.postal_code,u.display_name reporter_name FROM fivem_reports r LEFT JOIN users u ON u.id=r.reporter_user_id WHERE r.server_id=? ORDER BY r.id DESC LIMIT 100',[s.id]);return {ok:true,reports};}
module.exports={reports,actor,state,search,action,eligible,COMMAND};
