const db=require('../db');
const DEFAULTS={description:'A connected FiveM roleplay community. Explore our departments, events and community stories.',public_url:'',hero_title:'A community built for meaningful roleplay.',hero_body:'Find your department. Build your skills. Stay connected to the people and operations that make your community.',side_title:'From your first application to your next patrol.',highlights:'Apply and find your place\nTrain with your department\nTake part in live operations',section_title:'Our community',section_body:'Meet new people, create memorable stories and find your place in our community.',cta_title:'Your next chapter starts here.',cta_body:'Connect your Discord account and join the community workspace.',cta_label:'Continue with Discord',cta_url:'/auth/login',about_title:'About our community',about_body:'We bring players together through meaningful roleplay, shared training and community events.',gallery_title:'Community gallery',gallery_body:'Stories and moments from our community.',show_stats:true,show_resources:true,show_section:true,show_cta:true};
const LIMITS={description:500,public_url:500,hero_title:160,hero_body:2000,side_title:160,highlights:600,section_title:160,section_body:5000,cta_title:160,cta_body:2000,cta_label:80,cta_url:500,about_title:160,about_body:12000,gallery_title:160,gallery_body:2000};
function origin(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.origin:null;}catch{return null;}}
function link(value){if(/^\/(?!\/)/.test(value)&&!/[\\\s]/.test(value))return true;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
function validate(body){const result={};for(const [key,max] of Object.entries(LIMITS)){if(typeof body[key]!=='string'||body[key].trim().length>max)throw Error('Check the length of '+key.replaceAll('_',' ')+'.');result[key]=body[key].trim();}for(const key of ['hero_title','side_title','cta_title','cta_label','about_title','gallery_title'])if(!result[key])throw Error('Titles and button labels cannot be empty.');if(result.public_url&&!origin(result.public_url))throw Error('Enter a valid HTTP or HTTPS website address.');if(result.public_url)result.public_url=origin(result.public_url);if(!link(result.cta_url))throw Error('Use a website path beginning with / or an HTTPS button link.');if(result.highlights.split(/\r?\n/).filter(Boolean).length>3)throw Error('Use at most three highlight lines.');for(const key of ['show_stats','show_resources','show_section','show_cta'])result[key]=body[key]==='on';return result;}
async function load(){const [[row]]=await db.query("SELECT setting_value FROM site_settings WHERE setting_key='public_website_content'");let data={};try{data=JSON.parse(row?.setting_value||'{}');}catch{}const result={...DEFAULTS};for(const key of Object.keys(DEFAULTS))if(typeof data[key]===typeof DEFAULTS[key])result[key]=data[key];return result;}
function metadata(content,name,version,route='/'){const base=origin(content.public_url)||origin(process.env.BASE_URL)||'http://localhost:3020';return {title:route==='/about'?content.about_title+' · '+name:route==='/gallery'?content.gallery_title+' · '+name:name,description:content.description,url:(()=>{const u=new URL(base);u.pathname=route==='/home'?'/':route;return u.href;})(),image:new URL('/branding/icon?v='+encodeURIComponent(version||'default'),base).href};}
module.exports={DEFAULTS,LIMITS,load,validate,metadata,origin,link};
