const db=require('../db');

async function apply({trainingId,userId,completionHistoryId,resultStatus,score,actorId}){
  if(resultStatus!=='passed')return [];
  const [rules]=await db.query(`SELECT r.*,c.name certification_name,c.expires_after_days FROM training_certification_rules r LEFT JOIN certifications c ON c.id=r.certification_id WHERE r.training_id=? AND r.is_enabled=1 ORDER BY r.id`,[trainingId]);
  const results=[];
  for(const rule of rules){
    if(rule.minimum_score!==null&&(score===null||Number(score)<Number(rule.minimum_score))){await log(rule,trainingId,userId,completionHistoryId,'skipped',`Minimum score ${rule.minimum_score} not met.`);results.push({rule:rule.id,status:'skipped'});continue;}
    try{
      if(rule.certification_id){const expires=rule.expires_after_days?new Date(Date.now()+Number(rule.expires_after_days)*86400000):null;await db.query(`INSERT INTO user_certifications(user_id,certification_id,awarded_by,awarded_at,expires_at,notes) VALUES(?,?,?,NOW(),?,?) ON DUPLICATE KEY UPDATE awarded_by=VALUES(awarded_by),awarded_at=NOW(),expires_at=VALUES(expires_at),notes=VALUES(notes)`,[userId,rule.certification_id,actorId||null,expires,`Awarded automatically after passing training #${trainingId}`]);await log(rule,trainingId,userId,completionHistoryId,'awarded',`Awarded ${rule.certification_name||'certification'}.`,rule.certification_id);results.push({rule:rule.id,status:'awarded',certification:rule.certification_name});}
      if(rule.advance_recruit_stage){const [[u]]=await db.query('SELECT department_id FROM users WHERE id=?',[userId]);await db.query('INSERT INTO recruit_pipeline(user_id,department_id,stage,notes,changed_by) VALUES(?,?,?,?,?)',[userId,u?.department_id||null,rule.advance_recruit_stage,`Advanced automatically after passing training #${trainingId}`,actorId||null]);if(rule.advance_recruit_stage==='recruit')await db.query("UPDATE users SET role='recruit',member_status='recruit' WHERE id=?",[userId]);if(rule.advance_recruit_stage==='member')await db.query("UPDATE users SET role='member',member_status='active',joined_department_at=COALESCE(joined_department_at,NOW()) WHERE id=?",[userId]);await log(rule,trainingId,userId,completionHistoryId,'progressed',`Recruit pipeline advanced to ${rule.advance_recruit_stage}.`);results.push({rule:rule.id,status:'progressed',stage:rule.advance_recruit_stage});}
      if(Number(rule.complete_probation)){await db.query("UPDATE staff_profiles SET probation_status='completed',probation_ends_at=COALESCE(probation_ends_at,NOW()),updated_by=? WHERE user_id=?",[actorId||null,userId]);await db.query("INSERT INTO staff_actions(user_id,action_type,reason,performed_by) VALUES(?,'probation_complete',?,?)",[userId,`Completed automatically after passing training #${trainingId}`,actorId||null]);await log(rule,trainingId,userId,completionHistoryId,'completed_probation','Probation marked completed.');results.push({rule:rule.id,status:'completed_probation'});}
      if(Number(rule.notify_member)){const parts=[];if(rule.certification_id)parts.push(`${rule.certification_name||'Certification'} awarded`);if(rule.advance_recruit_stage)parts.push(`progressed to ${rule.advance_recruit_stage.replaceAll('_',' ')}`);if(Number(rule.complete_probation))parts.push('probation completed');if(parts.length)await db.query('INSERT INTO notifications(user_id,title,message,url) VALUES(?,?,?,?)',[userId,'Training progression',parts.join(' · '),`/personnel/${userId}`]);}
    }catch(error){await log(rule,trainingId,userId,completionHistoryId,'failed',String(error.message).slice(0,500),rule.certification_id);results.push({rule:rule.id,status:'failed',error:error.message});}
  }
  return results;
}
async function log(rule,trainingId,userId,completionHistoryId,status,detail,certificationId=null){await db.query('INSERT INTO training_rule_execution_log(rule_id,training_id,user_id,completion_history_id,certification_id,result_status,detail) VALUES(?,?,?,?,?,?,?)',[rule.id,trainingId,userId,completionHistoryId||null,certificationId||null,status,detail||null]);}
module.exports={apply};
