const assert=require('node:assert/strict'),path=require('path'),crypto=require('crypto'),express=require('express');const dbPath=require.resolve('../src/db');let sqlRole='admin',active=1,writes=[];
const query=async(sql,args=[])=>{if(sql.includes('SELECT role'))return [[{role:sqlRole,is_active:active}]];if(sql.includes('SELECT setting_key'))return [[{setting_key:'community_name',setting_value:'Test community'}]];if(sql.includes('SELECT file_data'))return [[{}]];writes.push({sql,args});return [{affectedRows:1}];};require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:{query,getConnection:async()=>({query,beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release(){}})}};
const app=express();app.use(express.urlencoded({extended:true}));app.use((req,res,next)=>{req.session={user:req.get('x-role')==='guest'?null:{id:1,role:req.get('x-role')||'admin'}};res.render=(view,data)=>res.json({view,...data});next();});app.use('/admin/appearance',require('../src/routes/appearance'));
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8ZsAAAAASUVORK5CYII=','base64');
const server=app.listen(0,'127.0.0.1',async()=>{const base='http://127.0.0.1:'+server.address().port+'/admin/appearance';const upload=async(bytes,role='admin')=>{const form=new FormData();form.append('logo',new Blob([bytes]),'logo.png');return fetch(base+'/logo',{method:'POST',body:form,headers:{'x-role':role},redirect:'manual'});};try{
for(const role of ['applicant','recruit','member','reviewer','department_command','staff']){assert.equal((await upload(png,role)).status,403);}assert.equal((await upload(png,'guest')).status,302);assert.equal(writes.length,0);
sqlRole='member';assert.equal((await upload(png,'admin')).status,403);assert.equal(writes.length,0);sqlRole='admin';active=0;assert.equal((await upload(png)).status,403);active=1;
assert.equal((await upload(Buffer.from('<svg>unsafe</svg>'))).status,400);assert.equal((await upload(Buffer.alloc(256*1024+1))).status,413);assert.equal(writes.length,0);
for(const role of ['admin','management','owner']){sqlRole=role;assert.equal((await upload(png,role)).status,302);}assert.equal(writes.length,3);assert(writes[0].args[0].equals(png));assert.equal(writes[0].args[2],crypto.createHash('sha256').update(png).digest('hex'));
sqlRole='admin';const response=await fetch(base+'/features',{method:'POST',body:new URLSearchParams({applications:'on',hud:'on'}),headers:{'x-role':'admin'},redirect:'manual'});assert.equal(response.status,302);const featureWrites=writes.filter(w=>w.sql.startsWith('INSERT'));assert.equal(featureWrites.length,5);assert.deepEqual(featureWrites.map(w=>w.args[1]),['1','0','0','1','0']);
assert.equal((await fetch(base+'/logo/remove',{method:'POST',redirect:'manual'})).status,302);assert(writes.at(-1).sql.includes('file_data=NULL'));
console.log('Passed: current SQL admin roles, stale-session demotion, inactive accounts, image signatures/size, SQL bytes/checksum, all feature switches and logo removal.');
}catch(e){console.error(e);process.exitCode=1;}finally{server.close();}});
