const assert=require('node:assert/strict'),path=require('path'),fs=require('fs');process.env.MAX_UPLOAD_MB=String(1/1024);
const docs=new Map([[1,{id:1,title:'Original <file>',original_name:'original.html',stored_name:'retained',mime_type:'text/html',file_size:12,file_data:Buffer.from('<b>file</b>'),database_stored:1,deleted_at:null}]]);let role='admin',mutations=0,nextId=2,packet=64000000;
const connection={beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release(){},async query(sql,args){if(sql.includes('max_allowed_packet'))return [[{packet_size:packet}]];if(sql.startsWith('INSERT INTO documents')){const id=nextId++;docs.set(id,{id,title:args[1],original_name:args[2],stored_name:args[3],mime_type:args[4],file_size:args[5],database_stored:1,deleted_at:null});mutations++;return [{insertId:id}];}if(sql.includes('INSERT INTO document_contents')){docs.get(args[0]).file_data=args[1];mutations++;return [{}];}throw Error('Unexpected connection query');}};
const database={getConnection:async()=>connection,async query(sql,args){if(sql.startsWith('UPDATE documents')){const removing=sql.includes('NOW()'),doc=docs.get(Number(args.at(-1)));if(!doc||(removing?!!doc.deleted_at:!doc.deleted_at))return [{affectedRows:0}];doc.deleted_at=removing?new Date():null;doc.deleted_by=removing?args[0]:null;mutations++;return [{affectedRows:1}];}if(sql.includes('WHERE d.id=?')){assert(sql.includes('deleted_at IS NULL'));const doc=docs.get(Number(args[0]));return [[doc&&!doc.deleted_at?doc:undefined]];}if(sql.includes('document_folders ORDER'))return [[]];if(sql.includes('SELECT id,title'))return [[...docs.values()].filter(d=>d.deleted_at)];if(sql.includes('SELECT d.*')){assert(sql.includes('deleted_at IS NULL'));return [[...docs.values()].filter(d=>!d.deleted_at)];}throw Error('Unexpected query: '+sql);}};
const dbPath=require.resolve('../src/db');require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:database};const express=require('express');const app=express();app.use(express.urlencoded({extended:true}));app.set('views',path.resolve(__dirname,'../views'));app.set('view engine','ejs');app.use((req,res,next)=>{req.session={user:role?{id:7,role}:null};Object.assign(res.locals,{user:req.session.user,communityName:'Test',currentPath:'/documents',cookieAccepted:true,unreadNotifications:0});next();});app.use('/documents',require('../src/routes/documents'));app.use((req,res)=>res.sendStatus(404));app.use((e,req,res,next)=>res.status(500).json({error:e.message}));
(async()=>{const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));try{const base='http://127.0.0.1:'+server.address().port;const post=url=>fetch(base+url,{method:'POST',redirect:'manual'});
 for(role of ['applicant','recruit','member','reviewer','department_command','staff']){const before=mutations;for(const action of ['remove','restore'])assert.equal((await post('/documents/1/'+action)).status,403);assert.equal(mutations,before);const html=await(await fetch(base+'/documents')).text();assert(!html.includes('/1/remove'));assert(!html.includes('Removed documents'));}
 role=null;assert.equal((await post('/documents/1/remove')).status,302);
 for(role of ['admin','management','owner']){assert.equal((await post('/documents/1/remove')).status,302);assert.equal(docs.get(1).deleted_by,7);const bytes=docs.get(1).file_data;
  for(const viewer of ['member','admin']){role=viewer;const res=await fetch(base+'/documents/1/download');assert.equal(res.status,404);}role='admin';let html=await(await fetch(base+'/documents')).text();assert(html.includes('/1/restore'));assert(!html.includes('/1/download'));assert(html.includes('Original &lt;file&gt;'));assert.equal((await post('/documents/1/restore')).status,302);assert.strictEqual(docs.get(1).file_data,bytes);
 }
 role='admin';assert.equal((await post('/documents/999/remove')).status,404);const response=await fetch(base+'/documents/1/download');assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),/^attachment/);assert.equal(response.headers.get('x-content-type-options'),'nosniff');
 role='staff';const payload=Buffer.from('any file bytes');function form(name,type,bytes=payload){const f=new FormData();f.append('document',new Blob([bytes],{type}),name);return f;}
 for(const [name,type] of [['scripts.lua','text/x-lua'],['bundle.zip','application/zip'],['movie.mp4','video/mp4'],['tool.exe','application/octet-stream'],['page.html','text/html'],['noextension','application/x-custom']]){const r=await fetch(base+'/documents/upload',{method:'POST',body:form(name,type),redirect:'manual'});assert.equal(r.status,302,name+' rejected');assert(docs.get(nextId-1).file_data.equals(payload));}
 let before=mutations;assert.equal((await fetch(base+'/documents/upload',{method:'POST',body:form('large.bin','application/octet-stream',Buffer.alloc(2048))})).status,413);assert.equal(mutations,before);packet=1;assert.equal((await fetch(base+'/documents/upload',{method:'POST',body:form('limit.zip','application/zip')})).status,413);assert.equal(mutations,before);
 role='member';assert.equal((await fetch(base+'/documents/upload',{method:'POST',body:form('notallowed.bin','application/octet-stream')})).status,403);
 console.log('Passed: admin-only removal/restore, blocked removed downloads, retained bytes, escaped names, all MIME/extension types, upload authorization and size/packet limits.');
 }finally{await new Promise(resolve=>server.close(resolve));}})().catch(e=>{console.error(e);process.exitCode=1;});
