const assert=require('node:assert/strict');
const fs=require('fs');
const vm=require('vm');
const nodes=new Map();
const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',style:{},addEventListener(){},classList:{add(){},remove(){},toggle(){},contains(){return false;}}});return nodes.get(id);};
const listeners=[];const onMessage=event=>listeners.forEach(handler=>handler(event));let request,fail=false;
const context=vm.createContext({document:{getElementById:node,querySelectorAll:()=>[],addEventListener(){},createElement:()=>({textContent:'',innerHTML:''})},window:{addEventListener:(_,handler)=>listeners.push(handler)},setInterval(){},setTimeout(){},Date,JSON,GetParentResourceName:()=> 'communityhub',fetch:async(url,options)=>{request={url,body:JSON.parse(options.body)};if(fail)throw new Error('network');return {ok:true};}});
vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../fivem/communityhub/html/app.js'),'utf8'),context);
(async()=>{
  node('reportSubject').value='Keep this subject';node('reportDetails').value='Keep these details';
  node('submitReport').onclick();await new Promise(resolve=>setImmediate(resolve));
  assert.equal(request.url,'https://communityhub/report');assert.equal(request.body.subject,'Keep this subject');
  assert.equal(node('reportSubject').value,'Keep this subject','callback acknowledgement cleared unsaved report');
  onMessage({data:{type:'reportResult',data:{ok:false,error:'Website unavailable'}}});
  assert.equal(node('reportDetails').value,'Keep these details');assert.equal(node('notice').textContent,'Website unavailable');
  onMessage({data:{type:'reportResult',data:{ok:true}}});
  assert.equal(node('reportSubject').value,'');assert.equal(node('reportDetails').value,'');
  onMessage({data:{type:'profile',data:{ok:false,error:'Authentication rejected'}}});
  assert.equal(node('status').textContent,'Authentication rejected');
  onMessage({data:{type:'profile',data:{ok:true,player:{role:'admin',display_name:'Admin'}}}});
  node('chatMessage').value='Retain chat draft';node('chatSend').onclick();await new Promise(resolve=>setImmediate(resolve));
  assert.equal(request.body.message,'Retain chat draft');assert.equal(node('chatSend').disabled,true);
  onMessage({data:{type:'chatData',data:{ok:true,messages:[]}}});
  assert.equal(node('chatSend').disabled,true,'poll response unlocked pending send');
  onMessage({data:{type:'chatData',data:{ok:false,wasSend:true,error:'Denied'}}});
  assert.equal(node('chatMessage').value,'Retain chat draft');assert.equal(node('chatSend').disabled,false);
  onMessage({data:{type:'chatData',data:{ok:true,wasSend:true,sent:true,messages:[]}}});
  assert.equal(node('chatMessage').value,'');
  onMessage({data:{type:'clockHistory',data:{ok:true,sessions:[{status:'active',duration_seconds:60,clocked_in_at:new Date(),server_name:'Primary'}]}}});
  assert.equal(node('clockIn').disabled,true);assert.equal(node('clockOut').disabled,false);
  onMessage({data:{type:'profile',data:{ok:true,player:{role:'member'}}}});
  request=null;node('chatMessage').value='Forbidden';await node('chatSend').onclick();assert.equal(request,null);
  fail=true;await vm.runInContext("send('link',{code:'123456'})",context);
  assert.match(node('notice').textContent,/Cannot contact/);
  console.log('Passed: NUI callback failures, profile errors and report retention until confirmed API success.');
})().catch(error=>{console.error(error);process.exitCode=1;});
