const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
if(!process.env.REPORT_TEST_PORT)throw Error('Set REPORT_TEST_PORT to a disposable MariaDB instance.');
const name='communityhub_reports_test_'+process.pid;
Object.assign(process.env,{DB_HOST:'127.0.0.1',DB_PORT:process.env.REPORT_TEST_PORT,DB_USER:'root',DB_PASSWORD:'',DB_NAME:name});
async function run(){const admin=await require('mysql2/promise').createConnection({host:'127.0.0.1',port:Number(process.env.DB_PORT),user:'root',multipleStatements:true});const db=require('../src/db');let listener;try{
 await admin.query(`CREATE DATABASE ${name};USE ${name};
 CREATE TABLE users(id BIGINT UNSIGNED PRIMARY KEY,role VARCHAR(40),is_active BOOLEAN,display_name VARCHAR(100),discord_username VARCHAR(100),discord_id VARCHAR(32),fivem_license VARCHAR(100));
 INSERT INTO users VALUES(1,'admin',1,'Admin','Admin',NULL,'license:admin'),(2,'member',1,'Member','Member',NULL,'license:member');
 CREATE TABLE fivem_servers(id BIGINT UNSIGNED PRIMARY KEY,server_key VARCHAR(100),name VARCHAR(100),is_enabled BOOLEAN);
 INSERT INTO fivem_servers VALUES(1,'primary','Test server',1),(2,'other','Other server',1);
 CREATE TABLE fivem_reports(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,reporter_user_id BIGINT UNSIGNED NULL,server_id BIGINT UNSIGNED NULL,report_type VARCHAR(80),subject VARCHAR(160),details TEXT,status ENUM('open','under_review','actioned','closed') DEFAULT 'open',assigned_to BIGINT UNSIGNED NULL,postal_code VARCHAR(16),position_x DOUBLE,position_y DOUBLE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE reports(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,reporter_user_id BIGINT UNSIGNED NULL,report_type VARCHAR(80),description LONGTEXT,status ENUM('open','under_review','actioned','dismissed','closed') DEFAULT 'open',assigned_to BIGINT UNSIGNED NULL,resolution TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE report_comments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,report_id BIGINT UNSIGNED,user_id BIGINT UNSIGNED,comment TEXT,is_internal BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
 INSERT INTO reports(report_type,description) VALUES('Other','Existing web report');
 INSERT INTO fivem_reports(reporter_user_id,server_id,report_type,subject,details,postal_code) VALUES(2,1,'other','Existing game report','Historical details','3001');`);
 const migration=fs.readFileSync(path.join(__dirname,'../sql/migrations/024_report_sync.sql'),'utf8');await admin.query(migration);await admin.query(migration);
 let [[n]]=await db.query('SELECT COUNT(*) n FROM reports');assert.equal(n.n,2);
 const sync=require('../src/services/reportSync'),game=require('../src/services/gameReports');
 const express=require('express'),app=express();app.use(express.json());app.use(express.urlencoded({extended:true}));process.env.FIVEM_API_KEY=crypto.randomBytes(32).toString('hex');
 app.use('/api/fivem',require('../src/routes/fivemApi'),require('../src/middleware/fivemErrors'));
 app.use((req,res,next)=>{req.session={user:{id:1,role:'admin'}};res.render=(view,data)=>res.json({view,...data});next();});app.use('/admin',require('../src/routes/admin'));
 listener=app.listen(0,'127.0.0.1');await new Promise(r=>listener.once('listening',r));const base='http://127.0.0.1:'+listener.address().port;
 const api=(route,data)=>fetch(base+'/api/fivem'+route,{method:'POST',headers:{'Content-Type':'application/json','x-communityhub-key':process.env.FIVEM_API_KEY},body:JSON.stringify({license:'license:member',server_key:'primary',...data})});
 const sample=require('../public/data/badger-postals.json')[0];
 const response=await api('/report',{report_type:'other',subject:'NUI fixture',details:'Reported from the game',position_x:sample.x,position_y:sample.y,postal_code:'FORGED'});assert.equal(response.status,200);const ids=await response.json();
 const website=await fetch(base+'/admin/reports/'+ids.website_report_id);assert.equal(website.status,200);const data=await website.json();assert(data.report.description.includes('Reported from the game'));assert(data.report.description.includes('3001'));assert.equal(data.report.fivem_report_id,ids.report_id);
 assert((await game.read('license:admin','primary')).reports.some(r=>r.id===ids.report_id&&r.website_report_id===ids.website_report_id));
 await game.update('license:admin','primary',{action:'reportStatus',report_id:ids.report_id,status:'under_review'});
 let [[saved]]=await db.query('SELECT status FROM reports WHERE id=?',[ids.website_report_id]);assert.equal(saved.status,'under_review');
 const changed=await fetch(base+'/admin/reports/'+ids.website_report_id+'/status',{method:'POST',body:new URLSearchParams({status:'dismissed',resolution:'Reviewed on website'}),redirect:'manual'});assert.equal(changed.status,302);
 assert.equal((await game.read('license:admin','primary')).reports.find(r=>r.id===ids.report_id).status,'dismissed');
 [[saved]]=await db.query('SELECT status FROM fivem_reports WHERE id=?',[ids.report_id]);assert.equal(saved.status,'dismissed');
 await assert.rejects(game.update('license:admin','other',{action:'reportStatus',report_id:ids.report_id,status:'closed'}),/unavailable/);
 await assert.rejects(game.update('license:member','primary',{action:'reportStatus',report_id:ids.report_id,status:'closed'}),/administrator/);
 assert.equal((await api('/report',{report_type:'other',subject:'Missing details'})).status,400);
 assert.equal((await api('/report',{server_key:'missing',report_type:'other',subject:'x',details:'y'})).status,404);
 const [[before]]=await db.query('SELECT COUNT(*) n FROM fivem_reports');
 await db.query("CREATE TRIGGER reject_sync BEFORE INSERT ON reports FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Test synchronization failure'");
 await assert.rejects(sync.submit({license:'license:member',server_key:'primary',report_type:'other',subject:'Atomic',details:'Rollback'}),/synchronization failure/);
 const [[after]]=await db.query('SELECT COUNT(*) n FROM fivem_reports');assert.equal(after.n,before.n);await db.query('DROP TRIGGER reject_sync');
 console.log('Passed: historical backfill/replay, API submit -> website review, two-way statuses, GPS/postal derivation, permissions, server isolation, validation and atomic rollback.');
 }finally{if(listener)await new Promise(r=>listener.close(r));await db.end();await admin.query(`DROP DATABASE IF EXISTS ${name}`);await admin.end();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
