fx_version 'cerulean'
game 'gta5'
author 'Community Hub'
description 'Community Hub website and FiveM integration'
version '1.0.0'
ui_page 'html/index.html'
shared_script 'config.lua'
client_script 'client/main.lua'
server_script 'server/main.lua'
files {'html/index.html','html/app.js','html/style.css'}