USE communityhub;
CREATE TABLE IF NOT EXISTS email_verification_tokens(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(user_id),
  INDEX(expires_at),
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);