USE communityhub;
ALTER TABLE users ADD COLUMN IF NOT EXISTS department_id BIGINT UNSIGNED NULL AFTER role;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rank_name VARCHAR(100) NULL AFTER department_id;
ALTER TABLE users ADD COLUMN IF NOT EXISTS callsign VARCHAR(50) NULL AFTER rank_name;
ALTER TABLE users ADD COLUMN IF NOT EXISTS member_status ENUM('applicant','recruit','active','loa','inactive','removed') NOT NULL DEFAULT 'applicant' AFTER callsign;
ALTER TABLE users ADD COLUMN IF NOT EXISTS joined_department_at DATETIME NULL AFTER member_status;

ALTER TABLE departments ADD COLUMN IF NOT EXISTS department_head_user_id BIGINT UNSIGNED NULL AFTER discord_role_id;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS recruit_discord_role_id VARCHAR(32) NULL AFTER department_head_user_id;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS member_discord_role_id VARCHAR(32) NULL AFTER recruit_discord_role_id;

CREATE TABLE IF NOT EXISTS department_ranks(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,department_id BIGINT UNSIGNED NOT NULL,name VARCHAR(100) NOT NULL,sort_order INT NOT NULL DEFAULT 0,discord_role_id VARCHAR(32) NULL,is_command BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(department_id) REFERENCES departments(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS recruit_pipeline(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,department_id BIGINT UNSIGNED NULL,stage ENUM('accepted','recruit','training','evaluation','member','failed','removed') NOT NULL DEFAULT 'accepted',notes TEXT NULL,changed_by BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(department_id) REFERENCES departments(id) ON DELETE SET NULL,FOREIGN KEY(changed_by) REFERENCES users(id) ON DELETE SET NULL,INDEX(user_id,stage));
CREATE TABLE IF NOT EXISTS certifications(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,department_id BIGINT UNSIGNED NULL,name VARCHAR(120) NOT NULL,description TEXT NULL,expires_after_days INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(department_id) REFERENCES departments(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS user_certifications(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,certification_id BIGINT UNSIGNED NOT NULL,awarded_by BIGINT UNSIGNED NULL,awarded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at DATETIME NULL,notes TEXT NULL,UNIQUE KEY uq_user_cert(user_id,certification_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(certification_id) REFERENCES certifications(id) ON DELETE CASCADE,FOREIGN KEY(awarded_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS loa_requests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,reason TEXT NOT NULL,status ENUM('pending','approved','denied','cancelled','completed') NOT NULL DEFAULT 'pending',reviewed_by BIGINT UNSIGNED NULL,review_note TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(reviewed_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS disciplinary_records(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,record_type ENUM('verbal_warning','written_warning','strike','suspension','removal','commendation','note') NOT NULL,reason TEXT NOT NULL,action_taken TEXT NULL,issued_by BIGINT UNSIGNED NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(issued_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS notifications(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,title VARCHAR(180) NOT NULL,message TEXT NOT NULL,url VARCHAR(500) NULL,is_read BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX(user_id,is_read,created_at));
CREATE TABLE IF NOT EXISTS discord_role_mappings(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,department_id BIGINT UNSIGNED NULL,mapping_type ENUM('community_role','department','rank','recruit','member') NOT NULL,source_value VARCHAR(120) NOT NULL,discord_role_id VARCHAR(32) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_role_mapping(mapping_type,source_value,department_id),FOREIGN KEY(department_id) REFERENCES departments(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_logs_v2(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,action VARCHAR(120) NOT NULL,entity_type VARCHAR(80) NULL,entity_id BIGINT UNSIGNED NULL,description TEXT NULL,metadata_json JSON NULL,ip_address VARCHAR(45) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(created_at),INDEX(entity_type,entity_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
INSERT INTO certifications(name,description) SELECT 'FTO','Field Training Officer certification' WHERE NOT EXISTS(SELECT 1 FROM certifications WHERE name='FTO');
INSERT INTO certifications(name,description) SELECT 'EVOC','Emergency Vehicle Operations certification' WHERE NOT EXISTS(SELECT 1 FROM certifications WHERE name='EVOC');