ALTER TABLE fivem_calls ADD COLUMN IF NOT EXISTS postal_code VARCHAR(16) NULL;
ALTER TABLE fivem_reports ADD COLUMN IF NOT EXISTS postal_code VARCHAR(16) NULL;
ALTER TABLE fivem_reports ADD COLUMN IF NOT EXISTS position_x DOUBLE NULL;
ALTER TABLE fivem_reports ADD COLUMN IF NOT EXISTS position_y DOUBLE NULL;
