CREATE TABLE IF NOT EXISTS community_gallery (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(160) NOT NULL,
 caption TEXT NULL,
 file_data MEDIUMBLOB NOT NULL,
 mime_type VARCHAR(80) NOT NULL,
 sha256 CHAR(64) NOT NULL,
 sort_order INT NOT NULL DEFAULT 0,
 is_published TINYINT(1) NOT NULL DEFAULT 1,
 is_removed TINYINT(1) NOT NULL DEFAULT 0,
 created_by BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX gallery_listing(is_removed,is_published,sort_order)
);
