-- CommunityHub V3 - LMS courses, lessons, quizzes and enrollments
-- HeidiSQL / MariaDB 10.4 compatible migration.
-- Run after 020_department_readiness.sql.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS lms_courses (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,department_id BIGINT UNSIGNED NULL,title VARCHAR(180) NOT NULL,slug VARCHAR(190) NOT NULL,description TEXT NULL,status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',passing_score DECIMAL(5,2) NULL,estimated_minutes INT UNSIGNED NULL,certification_id BIGINT UNSIGNED NULL,certificate_valid_days INT UNSIGNED NULL,created_by BIGINT UNSIGNED NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_lms_course_slug(slug),KEY idx_lms_course_status(status,department_id),CONSTRAINT fk_lms_course_department FOREIGN KEY(department_id) REFERENCES departments(id) ON DELETE SET NULL,CONSTRAINT fk_lms_course_cert FOREIGN KEY(certification_id) REFERENCES certifications(id) ON DELETE SET NULL,CONSTRAINT fk_lms_course_creator FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS lms_modules (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,course_id BIGINT UNSIGNED NOT NULL,title VARCHAR(180) NOT NULL,description TEXT NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(id),KEY idx_lms_module_course(course_id,sort_order),CONSTRAINT fk_lms_module_course FOREIGN KEY(course_id) REFERENCES lms_courses(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS lms_lessons (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,module_id BIGINT UNSIGNED NOT NULL,title VARCHAR(180) NOT NULL,lesson_type ENUM('content','video','resource','quiz') NOT NULL DEFAULT 'content',content LONGTEXT NULL,resource_url VARCHAR(1000) NULL,estimated_minutes INT UNSIGNED NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 0,is_required TINYINT(1) NOT NULL DEFAULT 1,PRIMARY KEY(id),KEY idx_lms_lesson_module(module_id,sort_order),CONSTRAINT fk_lms_lesson_module FOREIGN KEY(module_id) REFERENCES lms_modules(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS lms_quiz_questions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,lesson_id BIGINT UNSIGNED NOT NULL,question_text TEXT NOT NULL,question_type ENUM('single','true_false') NOT NULL DEFAULT 'single',sort_order INT UNSIGNED NOT NULL DEFAULT 0,points DECIMAL(7,2) NOT NULL DEFAULT 1,PRIMARY KEY(id),KEY idx_lms_question_lesson(lesson_id,sort_order),CONSTRAINT fk_lms_question_lesson FOREIGN KEY(lesson_id) REFERENCES lms_lessons(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS lms_quiz_answers (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,question_id BIGINT UNSIGNED NOT NULL,answer_text TEXT NOT NULL,is_correct TINYINT(1) NOT NULL DEFAULT 0,sort_order INT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(id),KEY idx_lms_answer_question(question_id,sort_order),CONSTRAINT fk_lms_answer_question FOREIGN KEY(question_id) REFERENCES lms_quiz_questions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS lms_enrollments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,course_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,status ENUM('enrolled','in_progress','completed','failed') NOT NULL DEFAULT 'enrolled',progress_percent DECIMAL(5,2) NOT NULL DEFAULT 0,final_score DECIMAL(5,2) NULL,enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,started_at DATETIME NULL,completed_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_lms_enrollment(course_id,user_id),KEY idx_lms_enrollment_user(user_id,status),CONSTRAINT fk_lms_enrollment_course FOREIGN KEY(course_id) REFERENCES lms_courses(id) ON DELETE CASCADE,CONSTRAINT fk_lms_enrollment_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS lms_lesson_progress (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,enrollment_id BIGINT UNSIGNED NOT NULL,lesson_id BIGINT UNSIGNED NOT NULL,status ENUM('not_started','in_progress','completed') NOT NULL DEFAULT 'not_started',score DECIMAL(5,2) NULL,started_at DATETIME NULL,completed_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_lms_lesson_progress(enrollment_id,lesson_id),CONSTRAINT fk_lms_progress_enrollment FOREIGN KEY(enrollment_id) REFERENCES lms_enrollments(id) ON DELETE CASCADE,CONSTRAINT fk_lms_progress_lesson FOREIGN KEY(lesson_id) REFERENCES lms_lessons(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS lms_course_prerequisites (course_id BIGINT UNSIGNED NOT NULL,prerequisite_course_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(course_id,prerequisite_course_id),CONSTRAINT fk_lms_prereq_course FOREIGN KEY(course_id) REFERENCES lms_courses(id) ON DELETE CASCADE,CONSTRAINT fk_lms_prereq_required FOREIGN KEY(prerequisite_course_id) REFERENCES lms_courses(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;