<?php
declare(strict_types=1);
namespace CommunityHub;
final class ApplicationAdmin {
 public static function handle(array $u,string $method,string $path,array $d):void{Domain::role($u,Domain::ADMINS);if($method==='POST'){
  if($path==='/admin/application-builder/forms'){$title=App::text($d['title']??null,'Title',180);$slug=trim(preg_replace('/[^a-z0-9]+/','-',strtolower($d['slug']?:$title)),'-');if(!$slug)throw new HttpError('Provide a valid slug.');App::query('INSERT INTO application_forms(title,slug,description,is_open,cooldown_days,sort_order,department_id) VALUES(?,?,?,?,?,?,?)',[$title,$slug,$d['description']?:null,(int)!empty($d['is_open']),max(0,(int)($d['cooldown_days']??0)),(int)($d['sort_order']??0),!empty($d['department_id'])?App::id($d['department_id']):null]);App::redirect('/admin/application-builder');}
  if(preg_match('~^/admin/application-builder/forms/(\d+)(/questions)?$~',$path,$m)){$id=(int)$m[1];if(!App::row('SELECT id FROM application_forms WHERE id=?',[$id]))throw new HttpError('Application form not found.',404);if(isset($m[2])){$types=['text','textarea','select','radio','checkbox','number','date'];$type=in_array($d['question_type']??'',$types,true)?$d['question_type']:'text';$options=array_values(array_filter(array_map('trim',preg_split('/\R/',(string)($d['options']??'')))));App::query('INSERT INTO application_questions(form_id,label,question_type,options_json,is_required,sort_order) VALUES(?,?,?,?,?,?)',[$id,App::text($d['label']??null,'Question label',500),$type,$options?json_encode($options,JSON_THROW_ON_ERROR):null,(int)!empty($d['is_required']),(int)($d['sort_order']??0)]);}else App::query('UPDATE application_forms SET title=?,description=?,is_open=?,cooldown_days=?,sort_order=? WHERE id=?',[App::text($d['title']??null,'Title',180),$d['description']?:null,(int)!empty($d['is_open']),max(0,(int)($d['cooldown_days']??0)),(int)($d['sort_order']??0),$id]);App::redirect('/admin/application-builder/forms/'.$id);}
  if(preg_match('~^/admin/application-builder/questions/(\d+)/delete$~',$path,$m)){$q=App::row('SELECT form_id FROM application_questions WHERE id=?',[(int)$m[1]]);if(!$q)throw new HttpError('Question not found.',404);App::query('DELETE FROM application_questions WHERE id=?',[(int)$m[1]]);App::redirect('/admin/application-builder/forms/'.$q['form_id']);}throw new HttpError('Application builder action not found.',404);
 }if(preg_match('~^/admin/application-builder/forms/(\d+)$~',$path,$m)){$id=(int)$m[1];$f=App::row('SELECT * FROM application_forms WHERE id=?',[$id]);if(!$f)throw new HttpError('Form not found.',404);View::layout('Application builder',function()use($f,$id){View::heading($f['title'],'Application questions are displayed in the order below.');View::form('/admin/application-builder/forms/'.$id,['title'=>['label'=>'Title','required'=>true],'description'=>['label'=>'Description','type'=>'textarea'],'is_open'=>['label'=>'Open for applications','type'=>'checkbox'],'cooldown_days'=>['label'=>'Submission cooldown days','type'=>'number'],'sort_order'=>['label'=>'Display order','type'=>'number']],'Save form',$f);View::table(App::rows('SELECT * FROM application_questions WHERE form_id=? ORDER BY sort_order,id',[$id]),['label'=>'Question','question_type'=>'Type','is_required'=>'Required','sort_order'=>'Order'],fn($q)=>View::form('/admin/application-builder/questions/'.$q['id'].'/delete',[],'Delete question'));View::form('/admin/application-builder/forms/'.$id.'/questions',['label'=>['label'=>'Question label','required'=>true],'question_type'=>['label'=>'Type','options'=>array_combine(['text','textarea','select','radio','checkbox','number','date'],['Text','Long text','Select','Single choice','Multiple choice','Number','Date'])],'options'=>['label'=>'Options, one per line','type'=>'textarea'],'is_required'=>['label'=>'Required','type'=>'checkbox','default'=>true],'sort_order'=>['label'=>'Order','type'=>'number']],'Add question');});return;}if($path!=='/admin/application-builder')throw new HttpError('Page not found.',404);View::layout('Application builder',function(){View::heading('Application builder');View::table(App::rows('SELECT id,title,slug,is_open,cooldown_days FROM application_forms ORDER BY sort_order,title'),['title'=>'Form','slug'=>'Slug','is_open'=>'Open','cooldown_days'=>'Cooldown days'],function($f){?><a href="/admin/application-builder/forms/<?=(int)$f['id']?>">Edit form</a><?php });View::form('/admin/application-builder/forms',['title'=>['label'=>'Form title','required'=>true],'slug'=>'URL slug','description'=>['label'=>'Description','type'=>'textarea'],'department_id'=>['label'=>'Department ID','type'=>'number'],'is_open'=>['label'=>'Open','type'=>'checkbox','default'=>true],'cooldown_days'=>['label'=>'Cooldown days','type'=>'number'],'sort_order'=>['label'=>'Display order','type'=>'number']],'Create form');});}
}
