<?php
declare(strict_types=1);
namespace CommunityHub;

final class DatabaseSession implements \SessionHandlerInterface, \SessionUpdateTimestampHandlerInterface {
 public function validateId(string $id):bool{return (bool)App::row('SELECT sid FROM php_sessions WHERE sid=? AND expires_at>NOW()',[$id]);}
 public function updateTimestamp(string $id,string $data):bool{App::query('UPDATE php_sessions SET expires_at=DATE_ADD(NOW(),INTERVAL 30 DAY) WHERE sid=?',[$id]);return true;}
 public function open(string $path,string $name):bool{return true;}
 public function close():bool{return true;}
 public function read(string $id):string{return (string)(App::row('SELECT data FROM php_sessions WHERE sid=? AND expires_at>NOW()',[$id])['data']??'');}
 public function write(string $id,string $data):bool{App::query('INSERT INTO php_sessions(sid,data,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 30 DAY)) ON DUPLICATE KEY UPDATE data=VALUES(data),expires_at=VALUES(expires_at)',[$id,$data]);return true;}
 public function destroy(string $id):bool{App::query('DELETE FROM php_sessions WHERE sid=?',[$id]);return true;}
 public function gc(int $lifetime):int|false{return App::query('DELETE FROM php_sessions WHERE expires_at<NOW()')->rowCount();}
}
final class Auth {
 public static function start():void{if(session_status()===PHP_SESSION_ACTIVE)return;ini_set('session.use_strict_mode','1');ini_set('session.use_only_cookies','1');session_name('communityhub_php');session_set_save_handler(new DatabaseSession(),true);session_set_cookie_params(['lifetime'=>2592000,'path'=>'/','secure'=>str_starts_with(App::base(),'https://'),'httponly'=>true,'samesite'=>'Lax']);session_start();}
 public static function user():?array{static $loaded=false,$user=null;if(!$loaded){$loaded=true;$id=$_SESSION['user_id']??null;if($id){$user=App::row('SELECT * FROM users WHERE id=?',[$id]);if(empty($user['is_active'])){$user=null;unset($_SESSION['user_id']);}}}return $user;}
 public static function requireUser(bool $member=false,array $roles=[]):array{$u=self::user();if(!$u)App::redirect('/auth/login');if($member)App::membership($u);if($roles)Domain::role($u,$roles);header('Cache-Control: private, no-store');return $u;}
 public static function token():string{$_SESSION['csrf']??=bin2hex(random_bytes(32));return $_SESSION['csrf'];}
 public static function csrf(array $d):void{if(!isset($_SESSION['csrf'])||!is_string($d['_csrf']??null)||!hash_equals($_SESSION['csrf'],$d['_csrf']))throw new HttpError('Your editing session expired. Reload this page and try again.',403);}
 public static function begin():never{if(!App::env('DISCORD_CLIENT_ID')||!App::env('DISCORD_CALLBACK_URL'))throw new HttpError('Discord OAuth is not configured.',503);$_SESSION['oauth_state']=bin2hex(random_bytes(24));App::redirect('https://discord.com/oauth2/authorize?'.http_build_query(['client_id'=>App::env('DISCORD_CLIENT_ID'),'redirect_uri'=>App::env('DISCORD_CALLBACK_URL'),'response_type'=>'code','scope'=>'identify email','state'=>$_SESSION['oauth_state'],'prompt'=>'consent']));}
 public static function callback(array $d):never{if(!isset($_SESSION['oauth_state'])||!is_string($d['state']??null)||!hash_equals($_SESSION['oauth_state'],$d['state'])||empty($d['code']))throw new HttpError('Discord authentication failed.',403);unset($_SESSION['oauth_state']);$c=curl_init('https://discord.com/api/oauth2/token');curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>10,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query(['client_id'=>App::env('DISCORD_CLIENT_ID'),'client_secret'=>App::env('DISCORD_CLIENT_SECRET'),'grant_type'=>'authorization_code','code'=>$d['code'],'redirect_uri'=>App::env('DISCORD_CALLBACK_URL')]),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]);$raw=curl_exec($c);if($raw===false||curl_getinfo($c,CURLINFO_RESPONSE_CODE)!==200)throw new HttpError('Discord authentication failed.',403);$token=json_decode($raw,true);if(empty($token['access_token']))throw new HttpError('Discord authentication failed.',403);$p=App::discord('GET','users/@me',null,'Bearer '.$token['access_token']);if(empty($p['id'])||empty($p['username']))throw new HttpError('Discord returned an invalid profile.',403);$id=App::transaction(function()use($p){$u=App::row('SELECT * FROM users WHERE discord_id=? FOR UPDATE',[$p['id']]);$email=!empty($p['verified'])?($p['email']??null):null;if(!$u&&$email){$existing=App::row('SELECT * FROM users WHERE email=? FOR UPDATE',[$email]);if($existing&&!empty($existing['discord_id']))throw new HttpError('That email is connected to another Discord account. Contact community staff.',409);$u=$existing;}if($u&&!$u['is_active'])throw new HttpError('Account is inactive.',403);$avatar=!empty($p['avatar'])?'https://cdn.discordapp.com/avatars/'.$p['id'].'/'.$p['avatar'].'.png':null;if($u){App::query('UPDATE users SET discord_id=?,discord_username=?,username=?,display_name=?,avatar_url=?,email=COALESCE(?,email),email_verified=? WHERE id=?',[$p['id'],$p['username'],$p['username'],$p['global_name']??$p['username'],$avatar,$email,(int)!empty($p['verified']),$u['id']]);return (int)$u['id'];}return App::insert('INSERT INTO users(discord_id,discord_username,username,display_name,avatar_url,email,email_verified) VALUES(?,?,?,?,?,?,?)',[$p['id'],$p['username'],$p['username'],$p['global_name']??$p['username'],$avatar,$email,(int)!empty($p['verified'])]);});session_regenerate_id(true);$_SESSION['user_id']=$id;unset($_SESSION['csrf']);App::redirect('/overview');}
}
