<?php
declare(strict_types=1);
namespace CommunityHub;
final class Dashboard {
 public static function member(array $u):void {
 ?><section class="grid two"><article class="panel"><h2>Your training</h2><?php View::table(App::rows("SELECT c.id,c.title,e.status,e.progress_percent FROM lms_enrollments e JOIN lms_courses c ON c.id=e.course_id WHERE e.user_id=? ORDER BY e.enrolled_at DESC LIMIT 10",[$u['id']]),['title'=>'Course','status'=>'Status','progress_percent'=>'Progress'],function($r){?><a href="/lms/courses/<?=(int)$r['id']?>">View course</a><?php });?></article><article class="panel"><h2>Your applications</h2><?php View::table(App::rows('SELECT f.title,a.status,a.submitted_at FROM applications a JOIN application_forms f ON f.id=a.form_id WHERE a.user_id=? ORDER BY a.id DESC LIMIT 10',[$u['id']]),['title'=>'Application','status'=>'Status','submitted_at'=>'Submitted']);?></article></section><section class="panel"><h2>Upcoming community events</h2><?php View::table(App::rows('SELECT title,start_at,location FROM calendar_events WHERE start_at>=NOW() ORDER BY start_at LIMIT 10'),['title'=>'Event','start_at'=>'Starts','location'=>'Location']);?><a href="/calendar">View calendar</a></section><?php
 }
 public static function command():void {
 $queues=[['Applications','SELECT a.id,f.title,a.status FROM applications a JOIN application_forms f ON f.id=a.form_id WHERE a.status IN (\'submitted\',\'under_review\',\'interview\') ORDER BY a.id DESC LIMIT 20',['id'=>'ID','title'=>'Application','status'=>'Status']],['Reports',"SELECT id,report_type,reported_name,status FROM reports WHERE status IN('open','under_review') ORDER BY id DESC LIMIT 20",['id'=>'ID','report_type'=>'Category','reported_name'=>'Reported player','status'=>'Status']],['Probation',"SELECT u.display_name,p.probation_status,p.probation_ends_at FROM staff_profiles p JOIN users u ON u.id=p.user_id WHERE p.probation_status IN('active','extended') ORDER BY p.probation_ends_at LIMIT 20",['display_name'=>'Member','probation_status'=>'Status','probation_ends_at'=>'Ends']],['Expiring certifications',"SELECT u.display_name,c.name,uc.expires_at FROM user_certifications uc JOIN users u ON u.id=uc.user_id JOIN certifications c ON c.id=uc.certification_id WHERE uc.expires_at<DATE_ADD(NOW(),INTERVAL 30 DAY) ORDER BY uc.expires_at LIMIT 20",['display_name'=>'Member','name'=>'Certification','expires_at'=>'Expires']],['Pending leave',"SELECT u.display_name,l.start_date,l.end_date FROM loa_requests l JOIN users u ON u.id=l.user_id WHERE l.status='pending' ORDER BY l.id DESC LIMIT 20",['display_name'=>'Member','start_date'=>'From','end_date'=>'Through']]];
 ?><section class="grid two"><?php foreach($queues as [$title,$sql,$columns]):?><article class="panel"><h2><?=escape($title)?></h2><?php View::table(App::rows($sql),$columns);?></article><?php endforeach?></section><?php
 }
}
