<?php
declare(strict_types=1);
namespace CommunityHub;

final class Domain {
 const STAFF=['department_command','staff','admin','management','owner'];
 const CONTENT_STAFF=['staff','admin','management','owner'];
 const ADMINS=['admin','management','owner'];
 const REPORT_STATUSES=['open','under_review','actioned','dismissed','closed'];
 const TICKET_STATUSES=['open','waiting_on_member','resolved','closed'];
 public static function server(string $key,bool $enabled=true):array{$s=App::row('SELECT * FROM fivem_servers WHERE server_key=?'.($enabled?' AND is_enabled=1':''),[$key]);if(!$s)throw new HttpError('Server not configured or disabled.',404);return $s;}
 public static function linked(string $license):array{if(!$license)throw new HttpError('Linked player license is required.');$u=App::row('SELECT u.*,d.name department_name FROM users u LEFT JOIN departments d ON d.id=u.department_id WHERE u.fivem_license=?',[$license]);if(!$u)throw new HttpError('Account not linked.',404);if(!$u['is_active'])throw new HttpError('Account is inactive.',403);return $u;}
 public static function role(array $u,array $roles):void{if(!in_array($u['role'],$roles,true))throw new HttpError('You do not have permission to access this area.',403);}
 public static function flag(string $key):bool{$r=App::row('SELECT setting_value FROM site_settings WHERE setting_key=?',['tablet_'.$key.'_enabled']);return $r?$r['setting_value']==='1':in_array($key,['hud','hud_logo','hud_name','hud_postals'],true);}
 public static function branding():array{$settings=App::rows("SELECT setting_key,setting_value FROM site_settings WHERE setting_key='community_name' OR setting_key LIKE 'tablet_%_enabled'");$values=array_column($settings,'setting_value','setting_key');$logo=App::row('SELECT file_data,mime_type,sha256 FROM community_branding WHERE id=1');$name=$values['community_name']??App::env('COMMUNITY_NAME','Community Hub');$features=[];foreach(['applications','hud','hud_logo','hud_name','hud_postals'] as $k)$features[$k]=isset($values['tablet_'.$k.'_enabled'])?$values['tablet_'.$k.'_enabled']==='1':$k!=='applications';return ['name'=>$name,'logo'=>!empty($logo['file_data'])?'data:'.$logo['mime_type'].';base64,'.base64_encode($logo['file_data']):null,'logoVersion'=>$logo['sha256']??hash('sha256',$name),'features'=>$features];}
 public static function news(array $d=[],bool $drafts=false):array{$q=App::text($d['q']??'','Search',120,true);$cat=App::text($d['category']??'','Category',80,true);return ['posts'=>App::rows("SELECT id,title,category,tags,summary,status,published_at,updated_at FROM community_news WHERE (?=1 OR status='published') AND (?='' OR category=?) AND (?='' OR INSTR(LOWER(CONCAT(title,' ',summary,' ',COALESCE(tags,''))),LOWER(?))>0) ORDER BY COALESCE(published_at,created_at) DESC,id DESC LIMIT 100",[(int)$drafts,$cat,$cat,$q,$q]),'categories'=>App::rows("SELECT DISTINCT category FROM community_news WHERE status='published' ORDER BY category"),'q'=>$q,'category'=>$cat];}
 public static function post(mixed $id,bool $drafts=false):array{$p=App::row("SELECT * FROM community_news WHERE id=? AND (?=1 OR status='published')",[App::id($id),(int)$drafts]);if(!$p)throw new HttpError('News post not found.',404);return $p;}
 public static function rules(array $d=[],bool $drafts=false):array{$q=App::text($d['q']??'','Search',120,true);return ['rules'=>App::rows("SELECT id,category,title,body,status,sort_order,updated_at FROM community_rules WHERE (?=1 OR status='published') AND (?='' OR INSTR(LOWER(CONCAT(title,' ',body,' ',category)),LOWER(?))>0) ORDER BY category,sort_order,id",[(int)$drafts,$q,$q]),'q'=>$q];}
 public static function tickets(array $u,bool $queue=false,string $status=''):array{if($queue)self::role($u,self::CONTENT_STAFF);if($status&&!in_array($status,self::TICKET_STATUSES,true))throw new HttpError('Invalid ticket status.');return App::rows("SELECT t.id,t.subject,t.category,t.status,t.created_at,t.updated_at,u.display_name FROM support_tickets t JOIN users u ON u.id=t.user_id WHERE (?=1 OR t.user_id=?) AND (?='' OR t.status=?) ORDER BY t.updated_at DESC,t.id DESC LIMIT 100",[(int)$queue,$u['id'],$status,$status]);}
 public static function thread(array $u,mixed $id,bool $ownerOnly=false):array{$staff=in_array($u['role'],self::CONTENT_STAFF,true)&&!$ownerOnly;$t=App::row('SELECT * FROM support_tickets WHERE id=? AND (?=1 OR user_id=?)',[App::id($id),(int)$staff,$u['id']]);if(!$t)throw new HttpError('Ticket not found.',404);return ['ticket'=>$t,'messages'=>array_reverse(App::rows('SELECT m.id,m.message,m.is_staff,m.created_at,u.display_name FROM support_messages m LEFT JOIN users u ON u.id=m.user_id WHERE m.ticket_id=? ORDER BY m.id DESC LIMIT 200',[$t['id']])),'staff'=>$staff];}
 private static function ticketNotify(int $owner,int $id,string $title,string $message):void{App::query("INSERT INTO notifications(user_id,title,message,url) SELECT id,?,?,? FROM users WHERE is_active=1 AND role IN ('staff','admin','management','owner') AND id<>?",[$title,$message,'/support/tickets/'.$id,$owner]);}
 public static function createTicket(array $u,array $d):int{$subject=App::text($d['subject']??null,'Subject',180);$message=App::text($d['message']??null,'Message',10000);$category=$d['category']??'';if(!in_array($category,['question','bug','report','appeal'],true))throw new HttpError('Select a ticket category.');return App::transaction(function()use($u,$subject,$message,$category){$actor=App::row('SELECT is_active FROM users WHERE id=? FOR UPDATE',[$u['id']]);if(empty($actor['is_active']))throw new HttpError('Active account required.',403);$id=App::insert('INSERT INTO support_tickets(user_id,subject,category) VALUES(?,?,?)',[$u['id'],$subject,$category]);App::query('INSERT INTO support_messages(ticket_id,user_id,message) VALUES(?,?,?)',[$id,$u['id'],$message]);self::ticketNotify((int)$u['id'],$id,'New support ticket',$subject);App::audit((int)$u['id'],'support.created','support_ticket',$id);return $id;});}
 public static function replyTicket(array $u,mixed $id,array $d,bool $ownerOnly=false,bool $statusOnly=false):int{return App::transaction(function()use($u,$id,$d,$ownerOnly,$statusOnly){$staff=in_array($u['role'],self::CONTENT_STAFF,true)&&!$ownerOnly;$actor=App::row('SELECT role,is_active FROM users WHERE id=? FOR UPDATE',[$u['id']]);if(empty($actor['is_active'])||$actor['role']!==$u['role'])throw new HttpError('Account changed. Refresh and try again.',403);$t=App::row('SELECT * FROM support_tickets WHERE id=? AND (?=1 OR user_id=?) FOR UPDATE',[App::id($id),(int)$staff,$u['id']]);if(!$t)throw new HttpError('Ticket not found.',404);if($statusOnly){if(!$staff)throw new HttpError('Support staff access required.',403);$status=$d['status']??'';if(!in_array($status,self::TICKET_STATUSES,true))throw new HttpError('Select a ticket status.');}else{if($t['status']==='closed')throw new HttpError('This ticket is closed. Ask support staff to reopen it.',409);$message=App::text($d['message']??null,'Reply',10000);App::query('INSERT INTO support_messages(ticket_id,user_id,is_staff,message) VALUES(?,?,?,?)',[$t['id'],$u['id'],(int)$staff,$message]);$status=$staff?'waiting_on_member':'open';}App::query('UPDATE support_tickets SET status=?,updated_at=NOW() WHERE id=?',[$status,$t['id']]);App::audit((int)$u['id'],$statusOnly?'support.status_changed':'support.replied','support_ticket',(int)$t['id'],['from'=>$t['status'],'to'=>$status]);if($staff&&$t['user_id']!=$u['id'])App::query('INSERT INTO notifications(user_id,title,message,url) VALUES(?,?,?,?)',[$t['user_id'],'Support ticket updated','Your support ticket has been updated.','/support/tickets/'.$t['id']]);elseif(!$staff)self::ticketNotify((int)$u['id'],(int)$t['id'],'Support reply received',$t['subject']);return (int)$t['id'];});}
 public static function postal(mixed $x,mixed $y):?string{if(!is_numeric($x)||!is_numeric($y)||abs((float)$x)>20000||abs((float)$y)>20000)return null;static $points=null;if($points===null){$dataset=['badger'=>'badger-postals','ocrp'=>'ocrp-postals','new'=>'postals'][App::env('POSTAL_DATASET','badger')]??'badger-postals';$path=dirname(__DIR__).'/public/data/'.$dataset.'.json';if(!is_file($path))$path=dirname(__DIR__,2).'/public/data/'.$dataset.'.json';$points=json_decode(file_get_contents($path),true,512,JSON_THROW_ON_ERROR);} $best=null;$distance=INF;foreach($points as $p){$d=((float)$p['x']-(float)$x)**2+((float)$p['y']-(float)$y)**2;if($d<$distance){$distance=$d;$best=(string)($p['code']??$p['postal']??'');}}return $best;}
 public static function submitReport(array $d):array{$subject=App::text($d['subject']??null,'Subject',160);$details=App::text($d['details']??null,'Details',10000);$name=App::text($d['reported_name']??'','Reported player name',150,true);$types=['failrp'=>'FailRP','vdm'=>'VDM','rdm'=>'RDM','player'=>'Player Report','staff'=>'Staff Report','other'=>'Other'];if(!isset($types[$d['report_type']??'']))throw new HttpError('Select a valid report category.');return App::transaction(function()use($d,$subject,$details,$name,$types){$s=self::server((string)($d['server_key']??'primary'));$u=App::row('SELECT id,is_active FROM users WHERE fivem_license=? FOR UPDATE',[$d['license']??'']);if($u&&!$u['is_active'])throw new HttpError('Account is inactive.',403);$postal=self::postal($d['position_x']??null,$d['position_y']??null);$id=App::insert('INSERT INTO fivem_reports(server_id,reporter_user_id,report_type,subject,details,postal_code,position_x,position_y) VALUES(?,?,?,?,?,?,?,?)',[$s['id'],$u['id']??null,$types[$d['report_type']],$subject,$details,$postal,is_numeric($d['position_x']??null)&&is_finite((float)$d['position_x'])&&abs((float)$d['position_x'])<=20000?$d['position_x']:null,is_numeric($d['position_y']??null)&&is_finite((float)$d['position_y'])&&abs((float)$d['position_y'])<=20000?$d['position_y']:null]);$description="In-game report: $subject\n\n$details\n\nServer: {$s['name']}\nPostal: ".($postal??'Unavailable');$web=App::insert("INSERT INTO reports(reporter_user_id,report_type,reported_name,description,status,fivem_report_id) VALUES(?,?,?,?,'open',?)",[$u['id']??null,$types[$d['report_type']],$name?:null,$description,$id]);return ['ok'=>true,'report_id'=>$id,'website_report_id'=>$web];});}
 public static function reportQueue(array $u,int $server):array{self::role($u,self::ADMINS);return App::rows('SELECT r.id,w.reported_name,r.report_type,r.subject,r.details,COALESCE(w.status,r.status) status,w.id website_report_id,r.created_at,r.postal_code,u.display_name reporter_name FROM fivem_reports r LEFT JOIN reports w ON w.fivem_report_id=r.id LEFT JOIN users u ON u.id=r.reporter_user_id WHERE r.server_id=? ORDER BY r.id DESC LIMIT 100',[$server]);}
 public static function reportStatus(array $u,int $server,array $d):array{self::role($u,self::ADMINS);if(($d['action']??'')!=='reportStatus'||!in_array($d['status']??'',self::REPORT_STATUSES,true))throw new HttpError('Invalid report action or status.');return App::transaction(function()use($u,$server,$d){$actor=App::row('SELECT role,is_active FROM users WHERE id=? FOR UPDATE',[$u['id']]);if(empty($actor['is_active']))throw new HttpError('Active account required.',403);self::role($actor,self::ADMINS);$r=App::row('SELECT id FROM fivem_reports WHERE id=? AND server_id=? FOR UPDATE',[App::id($d['report_id']??null),$server]);if(!$r)throw new HttpError('Report unavailable on this server.',404);App::query('UPDATE fivem_reports SET status=?,assigned_to=? WHERE id=?',[$d['status'],$u['id'],$r['id']]);$w=App::row('SELECT id FROM reports WHERE fivem_report_id=?',[$r['id']]);if(!$w)throw new HttpError('Website report is missing. Apply migration 024.',409);App::query('UPDATE reports SET status=?,assigned_to=? WHERE id=?',[$d['status'],$u['id'],$w['id']]);return ['ok'=>true,'website_report_id'=>(int)$w['id']];});}
 public static function clock(array $u,string $action,string $source,string $key):array{return App::transaction(function()use($u,$action,$source,$key){$u=App::row('SELECT id,department_id,callsign,is_active FROM users WHERE id=? FOR UPDATE',[$u['id']]);if(empty($u['is_active']))throw new HttpError('Active account required.',403);$a=App::row("SELECT id FROM patrol_sessions WHERE user_id=? AND status='active' LIMIT 1",[$u['id']]);if($action==='in'&&$a)return ['ok'=>true,'patrol_id'=>(int)$a['id'],'already_active'=>true];if($action==='out'&&!$a)return ['ok'=>true,'already_clocked_out'=>true];if($action==='in'){$s=self::server($key);$id=App::insert('INSERT INTO patrol_sessions(user_id,server_id,department_id,callsign) VALUES(?,?,?,?)',[$u['id'],$s['id'],$u['department_id'],$u['callsign']]);}else{$id=(int)$a['id'];App::query("UPDATE patrol_sessions SET status='completed',clocked_out_at=NOW() WHERE user_id=? AND status='active'",[$u['id']]);}App::query('INSERT INTO patrol_clock_events(patrol_id,user_id,event_type,source) VALUES(?,?,?,?)',[$id,$u['id'],$action==='in'?'clock_in':'clock_out',$source]);return ['ok'=>true,'patrol_id'=>$id];});}
 public static function clockHistory(int $id):array{return ['sessions'=>App::rows('SELECT p.id,p.status,p.clocked_in_at,p.clocked_out_at,p.callsign,u.display_name,u.discord_username,d.name department_name,s.name server_name,TIMESTAMPDIFF(SECOND,p.clocked_in_at,COALESCE(p.clocked_out_at,NOW())) duration_seconds FROM patrol_sessions p JOIN users u ON u.id=p.user_id LEFT JOIN departments d ON d.id=p.department_id LEFT JOIN fivem_servers s ON s.id=p.server_id WHERE p.user_id=? ORDER BY p.clocked_in_at DESC,p.id DESC LIMIT 100',[$id]),'events'=>App::rows('SELECT e.id,e.patrol_id,e.event_type,e.source,e.occurred_at,u.display_name,u.discord_username FROM patrol_clock_events e JOIN users u ON u.id=e.user_id WHERE e.user_id=? ORDER BY e.id DESC LIMIT 100',[$id]),'active'=>App::row("SELECT id,status,clocked_in_at,TIMESTAMPDIFF(SECOND,clocked_in_at,NOW()) duration_seconds FROM patrol_sessions WHERE user_id=? AND status='active' ORDER BY id DESC LIMIT 1",[$id])];}
 public static function learning(array $u,bool $summary=false):array{App::membership($u);$courses=App::rows('SELECT c.id,c.title,c.status course_status,e.status,e.progress_percent,e.final_score,e.completed_at FROM lms_enrollments e JOIN lms_courses c ON c.id=e.course_id WHERE e.user_id=? ORDER BY c.title',[$u['id']]);$certs=App::rows("SELECT c.id,c.name,uc.awarded_at,uc.expires_at,CASE WHEN uc.expires_at<=NOW() THEN 'expired' WHEN uc.expires_at<=DATE_ADD(NOW(),INTERVAL 30 DAY) THEN 'expiring' ELSE 'valid' END validity_status FROM user_certifications uc JOIN certifications c ON c.id=uc.certification_id WHERE uc.user_id=? ".($summary?'':'AND (uc.expires_at IS NULL OR uc.expires_at>NOW())').' ORDER BY c.name',[$u['id']]);$available=self::requirements($u,false);foreach($courses as &$c)$c['website_url']=App::base('/lms/courses/'.$c['id']);unset($c);return ['ok'=>true,'updated_at'=>date(DATE_ATOM),'website_url'=>App::base('/lms'),'courses'=>$courses,'certifications'=>$certs,'available_courses'=>$available];}
 public static function requirements(array $u,bool $check=true):array{if($check)App::membership($u);$courses=App::rows("SELECT c.id,c.title,c.description,c.certificate_valid_days,c.passing_score,c.estimated_minutes,c.certification_id,e.status enrollment_status,e.progress_percent FROM lms_courses c LEFT JOIN lms_enrollments e ON e.course_id=c.id AND e.user_id=? WHERE c.status='published' AND (c.department_id IS NULL OR c.department_id=?) ORDER BY c.title",[$u['id'],$u['department_id']]);foreach($courses as &$c){$c['prerequisites']=App::rows("SELECT c.id,c.title,(e.id IS NOT NULL) completed FROM lms_course_prerequisites p JOIN lms_courses c ON c.id=p.prerequisite_course_id LEFT JOIN lms_enrollments e ON e.course_id=c.id AND e.user_id=? AND e.status='completed' WHERE p.course_id=?",[$u['id'],$c['id']]);$c['required_lessons']=App::rows("SELECT l.id,l.title,l.lesson_type,COALESCE(p.status,'not_started') status,p.score FROM lms_lessons l JOIN lms_modules m ON m.id=l.module_id LEFT JOIN lms_enrollments e ON e.course_id=m.course_id AND e.user_id=? LEFT JOIN lms_lesson_progress p ON p.enrollment_id=e.id AND p.lesson_id=l.id WHERE m.course_id=? AND l.is_required=1 ORDER BY m.sort_order,l.sort_order,l.id",[$u['id'],$c['id']]);$c['can_enroll']=!array_filter($c['prerequisites'],fn($p)=>!(int)$p['completed']);$c['passing_score']=(float)($c['passing_score']??70);$c['website_url']=App::base('/lms/courses/'.$c['id']);}return $courses;}
}
