<?php
declare(strict_types=1);
namespace CommunityHub;

final class FiveM {
 public static function authenticate(array $d,string $path,string $key):void {
  if(!$key){App::limit('api-failed',$_SERVER['REMOTE_ADDR']??'unknown',500);throw new HttpError('Unauthorized',401);}
  $legacy=App::env('FIVEM_API_KEY');
  if(!$legacy||!hash_equals($legacy,$key)){
   $record=App::row('SELECT id,server_id FROM fivem_api_keys WHERE key_hash=? AND is_active=1',[hash('sha256',$key)]);
   if(!$record){App::limit('api-failed',$_SERVER['REMOTE_ADDR']??'unknown',500);throw new HttpError('Unauthorized',401);}
   if($record['server_id']){$server=App::row('SELECT server_key FROM fivem_servers WHERE id=?',[$record['server_id']]);$requested=$d['server_key']??(str_starts_with($path,'/status/')?rawurldecode(substr($path,8)):null); $scoped=str_starts_with($path,'/community/')||str_starts_with($path,'/support/')||str_starts_with($path,'/lms/')||in_array($path,['/heartbeat','/player-event','/active-unit','/report','/game-time','/patrol/clock-in','/patrol/clock-out','/reports/read','/reports/update','/admin-chat/read','/admin-chat/send'],true);if(($requested!==null||$scoped)&&(!$server||($requested??'primary')!==$server['server_key']))throw new HttpError('API key is assigned to a different server. Match Config.ServerKey and its server-bound API key.',403);}
   App::query('UPDATE fivem_api_keys SET last_used_at=NOW() WHERE id=?',[$record['id']]);
  }
  App::limit('api-success',hash('sha256',$key),10000);
 }
 public static function handle(string $method,string $path,array $d):array {
  $key=(string)($d['server_key']??'primary');
  if($method==='GET'&&preg_match('~^/status/(.+)$~',$path,$m)){$s=Domain::server(rawurldecode($m[1]),false);return ['ok'=>true,'server'=>array_intersect_key($s,array_flip(['server_key','name','framework']))];}
  if($method==='POST'&&$path==='/heartbeat'){
   $players=filter_var($d['players']??0,FILTER_VALIDATE_INT);$max=filter_var($d['max_players']??64,FILTER_VALIDATE_INT);if($players===false||$players<0||$max===false||$max<1)throw new HttpError('Invalid heartbeat player counts');
   App::transaction(function()use($d,$key,$players,$max){$s=App::row('SELECT *,NOW(3) observed_at FROM fivem_servers WHERE server_key=? FOR UPDATE',[$key]);if(!$s)throw new HttpError('Server not configured.',404);$p=App::row('SELECT * FROM fivem_status_periods WHERE server_id=? AND open_marker=1',[$s['id']]);$at=$s['observed_at'];if($p&&$p['state']==='online'&&$s['last_heartbeat_at']&&strtotime($at)-strtotime($s['last_heartbeat_at'])>=90){$expired=date('Y-m-d H:i:s',max(strtotime($p['started_at']),strtotime($s['last_heartbeat_at'])+90));App::query('UPDATE fivem_status_periods SET ended_at=?,open_marker=NULL WHERE server_id=? AND open_marker=1',[$expired,$s['id']]);App::query("INSERT INTO fivem_status_periods(server_id,state,started_at) VALUES(?,'offline',?)",[$s['id'],$expired]);$p=['state'=>'offline'];}if(!$p||$p['state']==='offline'){App::query('UPDATE fivem_status_periods SET ended_at=?,open_marker=NULL WHERE server_id=? AND open_marker=1',[$at,$s['id']]);App::query("INSERT INTO fivem_status_periods(server_id,state,started_at) VALUES(?,'online',?)",[$s['id'],$at]);}App::query('UPDATE fivem_servers SET is_online=1,current_players=?,max_players=?,hostname=?,last_heartbeat_at=? WHERE id=?',[$players,$max,mb_substr((string)($d['hostname']??''),0,255),$at,$s['id']]);});return ['ok'=>true];
  }
  if($method==='POST'&&$path==='/game-time'){if(!isset($d['hours'],$d['minutes'])||!is_int($d['hours'])||!is_int($d['minutes'])||$d['hours']<0||$d['hours']>23||$d['minutes']<0||$d['minutes']>59)throw new HttpError('Invalid game clock');$s=Domain::server($key);App::query('UPDATE fivem_servers SET game_hours=?,game_minutes=?,game_clock_at=NOW() WHERE id=?',[$d['hours'],$d['minutes'],$s['id']]);return ['ok'=>true];}
  if($method==='POST'&&$path==='/player-event'){$s=Domain::server($key);$u=App::row('SELECT id FROM users WHERE fivem_license=?',[$d['license']??'']);$type=($d['event_type']??'')==='leave'?'leave':'join';App::query('INSERT INTO fivem_player_events(server_id,user_id,fivem_license,player_name,event_type) VALUES(?,?,?,?,?)',[$s['id'],$u['id']??null,$d['license']??null,$d['player_name']??null,$type]);if($type==='join')App::query('INSERT INTO fivem_player_sessions(server_id,user_id,fivem_license,player_name) VALUES(?,?,?,?)',[$s['id'],$u['id']??null,$d['license']??null,$d['player_name']??null]);else{App::query('UPDATE fivem_player_sessions SET left_at=NOW() WHERE server_id=? AND fivem_license=? AND left_at IS NULL',[$s['id'],$d['license']??'']);App::query('DELETE FROM fivem_active_units WHERE server_id=? AND fivem_license=?',[$s['id'],$d['license']??'']);}return ['ok'=>true];}
  if($method==='POST'&&$path==='/active-unit'){$s=Domain::server($key);$u=App::row('SELECT u.id,u.callsign,u.rank_name,d.name department FROM users u LEFT JOIN departments d ON d.id=u.department_id WHERE u.fivem_license=?',[$d['license']??'']);$xyz=[];foreach(['position_x','position_y','position_z'] as $f)$xyz[]=isset($d[$f])&&is_numeric($d[$f])&&abs((float)$d[$f])<=20000?$d[$f]:null;App::query('INSERT INTO fivem_active_units(server_id,user_id,fivem_license,player_name,department,callsign,rank_name,duty_status,position_x,position_y,position_z,last_seen_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),player_name=VALUES(player_name),department=VALUES(department),callsign=VALUES(callsign),rank_name=VALUES(rank_name),duty_status=VALUES(duty_status),position_x=VALUES(position_x),position_y=VALUES(position_y),position_z=VALUES(position_z),last_seen_at=NOW()',[$s['id'],$u['id']??null,$d['license']??null,$d['player_name']??null,$u['department']??null,$u['callsign']??null,$u['rank_name']??null,$d['duty_status']??'available',...$xyz]);return ['ok'=>true];}
  if($method==='GET'&&$path==='/tablet'){Domain::server($key);$member=false;if(!empty($d['license']))try{App::membership(Domain::linked((string)$d['license']));$member=true;}catch(HttpError $e){if(!in_array($e->status,[403,404,503],true))throw $e;}return ['ok'=>true,'announcements'=>App::rows("SELECT title,message,priority,created_at FROM fivem_announcements WHERE is_active=1 AND (expires_at IS NULL OR expires_at>NOW()) ORDER BY FIELD(priority,'critical','important','info'),created_at DESC LIMIT 20"),'training'=>$member?App::rows('SELECT id,title,start_at,end_at,location FROM training_sessions WHERE start_at>=NOW() ORDER BY start_at LIMIT 20'):[],'calendar'=>$member?App::rows('SELECT id,title,start_at,end_at,event_type FROM calendar_events WHERE start_at>=NOW() ORDER BY start_at LIMIT 20'):[],'units'=>App::rows("SELECT player_name,department,callsign,rank_name,duty_status FROM fivem_active_units WHERE last_seen_at>DATE_SUB(NOW(),INTERVAL 2 MINUTE) ORDER BY department,callsign"),'branding'=>Domain::branding()];}
  if($method==='GET'&&preg_match('~^/player/(.+)$~',$path,$m)){$u=Domain::linked(rawurldecode($m[1]));$p=array_intersect_key($u,array_flip(['id','display_name','discord_id','role','is_active','callsign','rank_name','member_status','department_id','department_name']));$p['can_use_hud']=in_array($u['role'],Domain::STAFF,true)||(in_array($u['role'],['recruit','member','reviewer'],true)&&!empty($u['department_id']));$p['certifications']=array_column(App::rows('SELECT c.name FROM user_certifications uc JOIN certifications c ON c.id=uc.certification_id WHERE uc.user_id=? AND (uc.expires_at IS NULL OR uc.expires_at>NOW())',[$u['id']]),'name');return ['ok'=>true,'player'=>$p];}
  if($method==='POST'&&$path==='/link'){return App::transaction(function()use($d){$code=(string)($d['code']??'');$license=App::text($d['license']??null,'License',100);if(!preg_match('/^\d{6}$/',$code))throw new HttpError('Invalid link request');$r=App::row('SELECT * FROM fivem_link_codes WHERE code_hash=? AND used_at IS NULL AND expires_at>NOW() ORDER BY id DESC LIMIT 1 FOR UPDATE',[hash('sha256',$code)]);if(!$r)throw new HttpError('Link code expired or invalid',404);$u=App::row('SELECT is_active FROM users WHERE id=? FOR UPDATE',[$r['user_id']]);if(empty($u['is_active']))throw new HttpError('Active account required.',403);App::query('UPDATE users SET fivem_license=?,fivem_name=? WHERE id=?',[$license,$d['player_name']??null,$r['user_id']]);App::query('UPDATE fivem_link_codes SET used_at=NOW() WHERE id=?',[$r['id']]);return ['ok'=>true,'user_id'=>(int)$r['user_id']];});}
  if($method==='POST'&&$path==='/report')return Domain::submitReport($d);
  if($method==='POST'&&in_array($path,['/patrol/clock-in','/patrol/clock-out','/patrol/history'],true)){$u=Domain::linked((string)($d['license']??''));return $path==='/patrol/history'?['ok'=>true,...Domain::clockHistory((int)$u['id'])]:Domain::clock($u,$path==='/patrol/clock-in'?'in':'out','game',$key);}
  if($method==='POST'&&in_array($path,['/reports/read','/reports/update'],true)){$u=Domain::linked((string)($d['license']??''));$s=Domain::server($key);return $path==='/reports/read'?['ok'=>true,'reports'=>Domain::reportQueue($u,(int)$s['id'])]:Domain::reportStatus($u,(int)$s['id'],$d);}
  if(($method==='GET'&&in_array($path,['/lms/progress','/lms/requirements'],true))||($method==='POST'&&$path==='/lms/summary')){Domain::server($key);$u=Domain::linked((string)($d['license']??''));return $path==='/lms/requirements'?['ok'=>true,'courses'=>Domain::requirements($u)]:Domain::learning($u,$path==='/lms/summary');}
  if(($method==='POST'&&in_array($path,['/admin-chat/read','/admin-chat/send'],true))){$u=Domain::linked((string)($d['license']??''));Domain::role($u,Domain::ADMINS);$s=Domain::server($key);return App::transaction(function()use($u,$s,$path,$d){ $actor=App::row('SELECT role,is_active FROM users WHERE id=? FOR UPDATE',[$u['id']]);if(empty($actor['is_active']))throw new HttpError('Active account required.',403);Domain::role($actor,Domain::ADMINS);if($path==='/admin-chat/send'){$message=App::text($d['message']??null,'Message',1000);$recent=App::row('SELECT COUNT(*) count FROM fivem_admin_chat WHERE user_id=? AND created_at>DATE_SUB(NOW(),INTERVAL 30 SECOND)',[$u['id']]);if((int)$recent['count']>=10)throw new HttpError('Please wait before sending more admin chat messages.',429);App::query('INSERT INTO fivem_admin_chat(server_id,user_id,message) VALUES(?,?,?)',[$s['id'],$u['id'],$message]);}return ['ok'=>true,'messages'=>array_reverse(App::rows('SELECT c.id,c.message,c.created_at,u.display_name,u.discord_username FROM fivem_admin_chat c JOIN users u ON u.id=c.user_id WHERE c.server_id=? ORDER BY c.id DESC LIMIT 100',[$s['id']]))];});}
  if(str_starts_with($path,'/community/')){Domain::server($key);if(($method==='POST'&&$path==='/community/news/read')||($method==='GET'&&$path==='/community/news'))return ['ok'=>true,...Domain::news($d)];if(($method==='POST'&&$path==='/community/news/read-post')||($method==='GET'&&preg_match('~^/community/news/(\d+)$~',$path,$m)))return ['ok'=>true,'post'=>Domain::post($d['post_id']??$m[1]??null)];if(($method==='POST'&&$path==='/community/rules/read')||($method==='GET'&&$path==='/community/rules'))return ['ok'=>true,...Domain::rules($d)];}
  if(str_starts_with($path,'/support/')){Domain::server($key);$u=Domain::linked((string)($d['license']??''));if($method==='POST'&&$path==='/support/tickets/create'){App::limit('ticket-write',(string)$u['id'],30);return ['ok'=>true,'ticket_id'=>Domain::createTicket($u,$d)];}if($method==='POST'&&$path==='/support/tickets/reply'){App::limit('ticket-write',(string)$u['id'],30);return ['ok'=>true,'ticket_id'=>Domain::replyTicket($u,$d['ticket_id']??null,$d,true)];}if(($method==='POST'&&$path==='/support/tickets/read')||($method==='GET'&&preg_match('~^/support/tickets(?:/(\d+))?$~',$path,$m))){$id=$d['ticket_id']??$m[1]??null;if($id){$thread=Domain::thread($u,$id,true);unset($thread['staff']);$thread['ticket']=array_intersect_key($thread['ticket'],array_flip(['id','subject','category','status','created_at','updated_at']));return ['ok'=>true,...$thread];}return ['ok'=>true,'tickets'=>Domain::tickets($u)];}}
  if($method==='POST'&&preg_match('~^/applications/(catalog|form|submit)$~',$path,$m)){Domain::server($key);$u=Domain::linked((string)($d['license']??''));if(!Domain::flag('applications'))throw new HttpError('In-game applications are disabled by administrators.',403);return Applications::game($m[1],$u,$d);}
  throw new HttpError('FiveM API endpoint not found. Check Config.ApiBase and the installed website version.',404);
 }
}
