<?php
declare(strict_types=1);
namespace CommunityHub;
final class Management {
 public static function handle(array $u,string $method,string $path,array $d):void{if($path==='/admin/management/notifications'||preg_match('~^/admin/management/notifications/(\d+)/read$~',$path,$m)){if($method==='POST'){App::query('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?',[(int)$m[1],$u['id']]);App::redirect('/admin/management/notifications');}View::layout('Notifications',function()use($u){View::heading('Notifications');foreach(App::rows('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 100',[$u['id']]) as $n){?><article class="community-entry"><h2><?=escape($n['title'])?></h2><p><?=escape($n['message'])?></p><?php if(!empty($n['url'])&&str_starts_with($n['url'],'/')&&!str_starts_with($n['url'],'//')&&!preg_match('/[\\\s]/',$n['url'])):?><a href="<?=escape($n['url'])?>">Open</a><?php endif;if(!$n['is_read'])View::form('/admin/management/notifications/'.$n['id'].'/read',[],'Mark read');?></article><?php }});return;}
  if($method==='POST'){
   if($path==='/admin/management/departments'){Domain::role($u,Domain::ADMINS);$name=App::text($d['name']??null,'Department name',150);$slug=trim(preg_replace('/[^a-z0-9]+/','-',strtolower($d['slug']?:$name)),'-');if(!$slug)throw new HttpError('Provide a valid slug.');$id=App::insert('INSERT INTO departments(name,slug,description,is_active,discord_role_id,recruit_discord_role_id,member_discord_role_id) VALUES(?,?,?,1,?,?,?)',[$name,$slug,$d['description']?:null,$d['discord_role_id']?:null,$d['recruit_discord_role_id']?:null,$d['member_discord_role_id']?:null]);App::audit((int)$u['id'],'department.create','department',$id);App::redirect('/admin/management');}
   if(preg_match('~^/admin/management/departments/(\d+)/(update|ranks)$~',$path,$m)){$id=(int)$m[1];if(!App::row('SELECT id FROM departments WHERE id=?',[$id]))throw new HttpError('Department not found.',404);if($m[2]==='update'){Domain::role($u,Domain::ADMINS);App::query('UPDATE departments SET name=?,description=?,is_active=?,discord_role_id=?,recruit_discord_role_id=?,member_discord_role_id=? WHERE id=?',[App::text($d['name']??null,'Department name',150),$d['description']?:null,(int)!empty($d['is_active']),$d['discord_role_id']?:null,$d['recruit_discord_role_id']?:null,$d['member_discord_role_id']?:null,$id]);}else App::query('INSERT INTO department_ranks(department_id,name,sort_order,discord_role_id,is_command) VALUES(?,?,?,?,?)',[$id,App::text($d['name']??null,'Rank',100),(int)($d['sort_order']??0),$d['discord_role_id']?:null,(int)!empty($d['is_command'])]);App::audit((int)$u['id'],'department.'.$m[2],'department',$id);App::redirect('/admin/management');}
   if(preg_match('~^/admin/management/ranks/(\d+)/(update|delete)$~',$path,$m)){if($m[2]==='delete'){Domain::role($u,Domain::ADMINS);App::query('DELETE FROM department_ranks WHERE id=?',[(int)$m[1]]);}else App::query('UPDATE department_ranks SET name=?,sort_order=?,discord_role_id=?,is_command=? WHERE id=?',[App::text($d['name']??null,'Rank',100),(int)($d['sort_order']??0),$d['discord_role_id']?:null,(int)!empty($d['is_command']),(int)$m[1]]);App::redirect('/admin/management');}
   if($path==='/admin/management/certifications'){$days=isset($d['expires_after_days'])&&$d['expires_after_days']!==''?App::id($d['expires_after_days']):null;if($days>36500)throw new HttpError('Select a validity period no more than 36500 days.');App::query('INSERT INTO certifications(department_id,name,description,expires_after_days) VALUES(?,?,?,?)',[!empty($d['department_id'])?App::id($d['department_id']):null,App::text($d['name']??null,'Certification name',150),$d['description']?:null,$days]);App::redirect('/admin/management');}
   if(preg_match('~^/admin/management/certifications/(\d+)/award$~',$path,$m)){$id=(int)$m[1];$target=App::id($d['user_id']??null);$c=App::row('SELECT name,expires_after_days FROM certifications WHERE id=?',[$id]);if(!$c)throw new HttpError('Certification not found.',404);if(!App::row('SELECT id FROM users WHERE id=?',[$target]))throw new HttpError('User not found.',404);App::transaction(function()use($u,$id,$target,$c,$d){App::query('INSERT INTO user_certifications(user_id,certification_id,awarded_by,expires_at,notes) VALUES(?,?,?,IF(? IS NULL,NULL,DATE_ADD(NOW(),INTERVAL ? DAY)),?) ON DUPLICATE KEY UPDATE awarded_by=VALUES(awarded_by),awarded_at=NOW(),expires_at=VALUES(expires_at),notes=VALUES(notes)',[$target,$id,$u['id'],$c['expires_after_days'],$c['expires_after_days'],$d['notes']?:null]);App::query('INSERT INTO notifications(user_id,title,message,url) VALUES(?,?,?,?)',[$target,'Certification awarded: '.$c['name'],'A certification was added to your personnel file.','/personnel/'.$target]);});App::redirect('/personnel/'.$target);}
   if(preg_match('~^/admin/management/discipline/(\d+)$~',$path,$m)){Domain::role($u,Domain::CONTENT_STAFF);$types=['verbal_warning','written_warning','strike','suspension','removal','commendation','note'];if(!in_array($d['record_type']??'',$types,true))throw new HttpError('Select a disciplinary record type.');App::query('INSERT INTO disciplinary_records(user_id,record_type,reason,action_taken,issued_by) VALUES(?,?,?,?,?)',[(int)$m[1],$d['record_type'],App::text($d['reason']??null,'Reason',10000),$d['action_taken']?:null,$u['id']]);App::audit((int)$u['id'],'discipline.create','user',(int)$m[1],['type'=>$d['record_type']]);App::redirect('/personnel/'.$m[1]);}
   throw new HttpError('Management action not found.',404);
  }
  if($path!=='/admin/management')throw new HttpError('Page not found.',404);View::layout('Community management',function()use($u){View::heading('Community management','Departments, ranks, certifications and staff activity.');$departments=App::rows('SELECT * FROM departments ORDER BY name');foreach($departments as $dept){?><section class="panel"><h2><?=escape($dept['name'])?></h2><?php if(in_array($u['role'],Domain::ADMINS,true))View::form('/admin/management/departments/'.$dept['id'].'/update',['name'=>['label'=>'Name','required'=>true],'description'=>['label'=>'Description','type'=>'textarea'],'is_active'=>['label'=>'Active','type'=>'checkbox'],'discord_role_id'=>'Department Discord role ID','recruit_discord_role_id'=>'Recruit Discord role ID','member_discord_role_id'=>'Member Discord role ID'],'Save department',$dept);foreach(App::rows('SELECT * FROM department_ranks WHERE department_id=? ORDER BY sort_order,name',[$dept['id']]) as $r){View::form('/admin/management/ranks/'.$r['id'].'/update',['name'=>['label'=>'Rank','required'=>true],'sort_order'=>['label'=>'Order','type'=>'number'],'discord_role_id'=>'Discord role ID','is_command'=>['label'=>'Command rank','type'=>'checkbox']],'Save rank',$r);if(in_array($u['role'],Domain::ADMINS,true))View::form('/admin/management/ranks/'.$r['id'].'/delete',[],'Delete rank');}View::form('/admin/management/departments/'.$dept['id'].'/ranks',['name'=>['label'=>'New rank','required'=>true],'sort_order'=>['label'=>'Order','type'=>'number'],'discord_role_id'=>'Discord role ID','is_command'=>['label'=>'Command rank','type'=>'checkbox']],'Add rank');?></section><?php }if(in_array($u['role'],Domain::ADMINS,true))View::form('/admin/management/departments',['name'=>['label'=>'Department name','required'=>true],'slug'=>'URL slug','description'=>['label'=>'Description','type'=>'textarea'],'discord_role_id'=>'Department Discord role ID','recruit_discord_role_id'=>'Recruit Discord role ID','member_discord_role_id'=>'Member Discord role ID'],'Create department');?><section class="panel"><h2>Certifications</h2><?php View::table(App::rows('SELECT id,name,description,expires_after_days FROM certifications ORDER BY name'),['name'=>'Name','description'=>'Description','expires_after_days'=>'Valid days']);View::form('/admin/management/certifications',['name'=>['label'=>'Certification name','required'=>true],'description'=>['label'=>'Description','type'=>'textarea'],'department_id'=>['label'=>'Department','options'=>[''=>'Community-wide']+array_column($departments,'name','id')],'expires_after_days'=>['label'=>'Valid days (blank for no expiry)','type'=>'number']],'Create certification');?></section><section class="panel"><h2>Recent audit history</h2><?php View::table(App::rows('SELECT a.*,u.display_name FROM audit_logs_v2 a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 50'),['display_name'=>'Actor','action'=>'Action','entity_type'=>'Entity','entity_id'=>'Record','created_at'=>'When']);?></section><?php });
 }
}
