<?php
declare(strict_types=1);
namespace CommunityHub;
final class PeopleAdmin {
 public static function handle(array $u,string $method,string $path,array $d):void{
  if($path==='/personnel/me/loa'){if($method==='POST'){self::dates($d['start_date']??'',$d['end_date']??'');App::query('INSERT INTO loa_requests(user_id,start_date,end_date,reason) VALUES(?,?,?,?)',[$u['id'],$d['start_date'],$d['end_date'],App::text($d['reason']??null,'Reason',10000)]);App::redirect($path);}View::layout('My leave requests',function()use($u){View::heading('My leave requests');View::table(App::rows('SELECT start_date,end_date,reason,status,review_notes FROM loa_requests WHERE user_id=? ORDER BY created_at DESC',[$u['id']]),['start_date'=>'From','end_date'=>'Through','reason'=>'Reason','status'=>'Status','review_notes'=>'Staff notes']);View::form('/personnel/me/loa',['start_date'=>['label'=>'Start date','type'=>'date','required'=>true],'end_date'=>['label'=>'End date','type'=>'date','required'=>true],'reason'=>['label'=>'Reason','type'=>'textarea','required'=>true]],'Request leave');});return;}
  Domain::role($u,Domain::STAFF);
  if(str_starts_with($path,'/personnel/')){self::personnelActions($u,$method,$path,$d);return;}
  if(str_starts_with($path,'/loa-management')||preg_match('~^/admin/management/loa/~',$path)){self::leave($u,$method,$path,$d);return;}
  if(str_starts_with($path,'/staff-activity')){self::activity($u,$method,$path,$d);return;}
  if(str_starts_with($path,'/command-center')){self::command($u,$method,$path,$d);return;}
  if(str_starts_with($path,'/admin/management')){self::management($u,$method,$path,$d);return;}
  throw new HttpError('People administration page not found.',404);
 }
 private static function dates(string $start,string $end):void{if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$end)||strtotime($start)===false||strtotime($end)===false||$start>$end)throw new HttpError('Select valid start and end dates.');}
 private static function personnelActions(array $u,string $method,string $path,array $d):void{if($method!=='POST'||!preg_match('~^/personnel/(\d+)/(profile|staff-profile|notes|evaluations|pipeline)$~',$path,$m))throw new HttpError('Personnel action not found.',404);$id=(int)$m[1];$target=App::row('SELECT * FROM users WHERE id=?',[$id]);if(!$target)throw new HttpError('User not found.',404);switch($m[2]){case 'profile':$status=$d['member_status']??'active';if(!in_array($status,['applicant','recruit','active','loa','inactive','removed'],true))throw new HttpError('Select a valid member status.');$dept=!empty($d['department_id'])?App::id($d['department_id']):null;if($dept&&!App::row('SELECT id FROM departments WHERE id=?',[$dept]))throw new HttpError('Department not found.');$rank=App::text($d['rank_name']??'','Rank',100,true)?:null;App::query('UPDATE users SET department_id=?,callsign=?,rank_name=?,member_status=? WHERE id=?',[$dept,App::text($d['callsign']??'','Callsign',40,true)?:null,$rank,$status,$id]);if($target['department_id']!=$dept||$target['rank_name']!==$rank)App::query('INSERT INTO staff_actions(user_id,action_type,from_department_id,to_department_id,from_rank,to_rank,reason,performed_by) VALUES(?,?,?,?,?,?,?,?)',[$id,$target['department_id']!=$dept?'transfer':'promotion',$target['department_id'],$dept,$target['rank_name'],$rank,$d['change_reason']?:null,$u['id']]);People::syncDiscord($id);Automation::emit('member_status_changed',['entity_type'=>'user','entity_id'=>$id,'subject_user_id'=>$id,'previous_status'=>$target['member_status'],'status'=>$status],(int)$u['id']);break;
  case 'staff-profile':$probation=in_array($d['probation_status']??'',['none','active','completed','extended'],true)?$d['probation_status']:'none';$activity=in_array($d['activity_status']??'',['active','watch','inactive','exempt'],true)?$d['activity_status']:'active';$minutes=isset($d['activity_requirement_minutes'])&&$d['activity_requirement_minutes']!==''?filter_var($d['activity_requirement_minutes'],FILTER_VALIDATE_INT):null;if($minutes===false||$minutes<0||$minutes>100000)throw new HttpError('Enter valid activity minutes.');App::query('INSERT INTO staff_profiles(user_id,probation_status,probation_started_at,probation_ends_at,activity_status,activity_requirement_minutes,updated_by) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE probation_status=VALUES(probation_status),probation_started_at=VALUES(probation_started_at),probation_ends_at=VALUES(probation_ends_at),activity_status=VALUES(activity_status),activity_requirement_minutes=VALUES(activity_requirement_minutes),updated_by=VALUES(updated_by)',[$id,$probation,$d['probation_started_at']?:null,$d['probation_ends_at']?:null,$activity,$minutes,$u['id']]);break;
  case 'notes':if(!in_array($d['note_type']??'',['general','supervisor','performance','commendation','concern'],true))throw new HttpError('Select a valid note type.');App::query('INSERT INTO staff_notes(user_id,note_type,note_text,created_by) VALUES(?,?,?,?)',[$id,$d['note_type'],App::text($d['note_text']??null,'Note',10000),$u['id']]);break;
  case 'evaluations':$rating=isset($d['rating'])&&$d['rating']!==''?(float)$d['rating']:null;if(!in_array($d['evaluation_type']??'',['probation','routine','promotion','training','performance'],true)||($rating!==null&&($rating<1||$rating>5)))throw new HttpError('Select a valid evaluation type and rating.');App::query('INSERT INTO staff_evaluations(user_id,evaluator_id,evaluation_type,rating,summary,period_start,period_end) VALUES(?,?,?,?,?,?,?)',[$id,$u['id'],$d['evaluation_type'],$rating,App::text($d['summary']??null,'Summary',10000),$d['period_start']?:null,$d['period_end']?:null]);break;
  case 'pipeline':$stage=$d['stage']??'';if(!in_array($stage,['accepted','recruit','training','evaluation','member','failed','removed'],true))throw new HttpError('Select a valid recruit stage.');App::query('INSERT INTO recruit_pipeline(user_id,department_id,stage,notes,changed_by) VALUES(?,?,?,?,?)',[$id,$target['department_id'],$stage,$d['notes']?:null,$u['id']]);if($stage==='recruit')App::query("UPDATE users SET role='recruit',member_status='recruit' WHERE id=?",[$id]);if($stage==='member')App::query("UPDATE users SET role='member',member_status='active',joined_department_at=COALESCE(joined_department_at,NOW()) WHERE id=?",[$id]);People::syncDiscord($id);break;
 }App::audit((int)$u['id'],'personnel.'.$m[2],'user',$id);App::redirect('/personnel/'.$id);}
 private static function leave(array $u,string $method,string $path,array $d):void{if($method==='POST'){if($path==='/loa-management/restore-expired'){Domain::role($u,Domain::ADMINS);People::restoreLeave((int)$u['id']);App::redirect('/loa-management');}if(preg_match('~^/loa-management/(\d+)/(approve|deny)$~',$path,$m)){People::reviewLeave((int)$m[1],(int)$u['id'],$m[2]==='approve',App::text($d['review_notes']??'','Notes',10000,true)?:null);App::redirect('/loa-management');}if(preg_match('~^/admin/management/loa/(\d+)$~',$path,$m)){if(!in_array($d['status']??'',['approved','denied'],true))throw new HttpError('Select a leave decision.');People::reviewLeave((int)$m[1],(int)$u['id'],$d['status']==='approved',$d['review_notes']??null);App::redirect('/admin/management');}throw new HttpError('Leave action not found.',404);}if($path!=='/loa-management')throw new HttpError('Page not found.',404);People::restoreLeave();View::layout('Leave management',function()use($u){View::heading('Leave management');View::table(App::rows("SELECT l.*,u.display_name FROM loa_requests l JOIN users u ON u.id=l.user_id WHERE l.status='pending' ORDER BY l.created_at"),['display_name'=>'Member','start_date'=>'From','end_date'=>'Through','reason'=>'Reason'],function($l){View::form('/loa-management/'.$l['id'].'/approve',['review_notes'=>['label'=>'Notes','type'=>'textarea']],'Approve');View::form('/loa-management/'.$l['id'].'/deny',['review_notes'=>['label'=>'Notes','type'=>'textarea']],'Deny');});?><section class="panel"><h2>Active and recent leave</h2><?php View::table(App::rows("SELECT l.*,u.display_name FROM loa_requests l JOIN users u ON u.id=l.user_id WHERE l.status<>'pending' ORDER BY l.reviewed_at DESC LIMIT 100"),['display_name'=>'Member','status'=>'Status','start_date'=>'From','end_date'=>'Through','restored_at'=>'Activity restored']);if(in_array($u['role'],Domain::ADMINS,true))View::form('/loa-management/restore-expired',[],'Restore expired leave');?></section><?php });}
 private static function activity(array $u,string $method,string $path,array $d):void{$days=(int)($_GET['days']??$d['days']??7);if(!in_array($days,[7,14,30],true))$days=7;if($method==='POST'){if(in_array($path,['/staff-activity/snapshot','/staff-activity/evaluate'],true)){Domain::role($u,Domain::ADMINS);People::activity($days,true,$path==='/staff-activity/evaluate'?(int)$u['id']:null);App::redirect('/staff-activity?days='.$days);}if(preg_match('~^/staff-activity/(\d+)/(status|requirement)$~',$path,$m)){$id=(int)$m[1];if($m[2]==='status')People::activityStatus($id,(string)($d['activity_status']??''),App::text($d['reason']??'','Reason',10000,true),(int)$u['id']);else{$minutes=isset($d['activity_requirement_minutes'])&&$d['activity_requirement_minutes']!==''?filter_var($d['activity_requirement_minutes'],FILTER_VALIDATE_INT):null;if($minutes===false||$minutes<0||$minutes>100000)throw new HttpError('Enter valid activity minutes.');App::query('INSERT INTO staff_profiles(user_id,activity_requirement_minutes,updated_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE activity_requirement_minutes=VALUES(activity_requirement_minutes),updated_by=VALUES(updated_by)',[$id,$minutes,$u['id']]);}App::redirect('/staff-activity');}throw new HttpError('Activity action not found.',404);}if($path!=='/staff-activity')throw new HttpError('Page not found.',404);$board=People::activity($days);View::layout('Staff activity',function()use($u,$board,$days){View::heading('Staff activity',$board['period_start'].' through '.$board['period_end']);?><div class="actions"><a href="/staff-activity?days=7">7 days</a><a href="/staff-activity?days=14">14 days</a><a href="/staff-activity?days=30">30 days</a></div><?php View::table($board['rows'],['display_name'=>'Member','department_name'=>'Department','patrol_minutes'=>'Duty minutes','activity_requirement_minutes'=>'Required minutes','activity_status'=>'Status'],function($r){View::form('/staff-activity/'.$r['id'].'/status',['activity_status'=>['label'=>'Activity status','options'=>array_combine(['active','watch','inactive','exempt'],['Active','Watch','Inactive','Exempt'])],'reason'=>'Reason'],'Update status',$r);View::form('/staff-activity/'.$r['id'].'/requirement',['activity_requirement_minutes'=>['label'=>'Required minutes','type'=>'number']],'Set requirement',$r);});if(in_array($u['role'],Domain::ADMINS,true)){View::form('/staff-activity/snapshot',['days'=>['label'=>'Period','options'=>[7=>'7 days',14=>'14 days',30=>'30 days']]],'Save snapshot',['days'=>$days]);View::form('/staff-activity/evaluate',['days'=>['label'=>'Period','options'=>[7=>'7 days',14=>'14 days',30=>'30 days']]],'Evaluate activity',['days'=>$days]);}});}
 private static function command(array $u,string $method,string $path,array $d):void{if($method==='POST'&&preg_match('~^/command-center/readiness/(\d+)$~',$path,$m)){Domain::role($u,Domain::ADMINS);$min=max(0,min(100,(int)($d['minimum_on_duty']??0)));$super=max(0,min(100,(int)($d['minimum_supervisors']??0)));App::query('INSERT INTO department_readiness_settings(department_id,minimum_on_duty,minimum_supervisors,warning_when_below,critical_when_empty,updated_by) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE minimum_on_duty=VALUES(minimum_on_duty),minimum_supervisors=VALUES(minimum_supervisors),warning_when_below=VALUES(warning_when_below),critical_when_empty=VALUES(critical_when_empty),updated_by=VALUES(updated_by)',[(int)$m[1],$min,$super,(int)!empty($d['warning_when_below']),(int)!empty($d['critical_when_empty']),$u['id']]);People::readiness();App::redirect('/command-center/readiness');}if(!in_array($path,['/command-center','/command-center/updates','/command-center/readiness'],true))throw new HttpError('Page not found.',404);$rows=People::readiness();if($path==='/command-center/updates')App::json(['ok'=>true,'readiness'=>$rows,'updatedAt'=>date(DATE_ATOM)]);View::layout('Community command center',function()use($u,$rows,$path){View::heading('Community command center','Staffing, pending work and integration health.');if($path==='/command-center')Dashboard::command();View::table($rows,['name'=>'Department','on_duty'=>'On duty','minimum_on_duty'=>'Target','supervisors'=>'Supervisors','minimum_supervisors'=>'Target','state'=>'Readiness'],in_array($u['role'],Domain::ADMINS,true)?function($r){View::form('/command-center/readiness/'.$r['id'],['minimum_on_duty'=>['label'=>'Minimum on duty','type'=>'number'],'minimum_supervisors'=>['label'=>'Minimum supervisors','type'=>'number'],'warning_when_below'=>['label'=>'Warn below target','type'=>'checkbox'],'critical_when_empty'=>['label'=>'Critical when empty','type'=>'checkbox']],'Save staffing targets',$r);}:null);?><section class="panel"><h2>Open alerts</h2><?php View::table(App::rows('SELECT title,message,severity,created_at FROM command_alerts WHERE is_resolved=0 ORDER BY created_at DESC'),['title'=>'Alert','message'=>'Details','severity'=>'Severity','created_at'=>'Created']);?></section><?php });}
 private static function management(array $u,string $method,string $path,array $d):void{Management::handle($u,$method,$path,$d);}
}
