<?php
declare(strict_types=1);
namespace CommunityHub;
final class PersonnelView {
 public static function render(array $u,int $id):void{$target=App::row('SELECT * FROM users WHERE id=?',[$id]);if(!$target)return;$staff=App::row('SELECT * FROM staff_profiles WHERE user_id=?',[$id])??[];
  ?><section class="panel"><h2>Personnel management</h2><?php View::form('/personnel/'.$id.'/profile',['department_id'=>['label'=>'Department','options'=>[''=>'Unassigned']+array_column(App::rows('SELECT id,name FROM departments ORDER BY name'),'name','id')],'callsign'=>'Callsign','rank_name'=>'Rank','member_status'=>['label'=>'Member status','options'=>array_combine(['recruit','active','loa','inactive','removed'],['Recruit','Active','On leave','Inactive','Removed'])],'change_reason'=>['label'=>'Change reason','type'=>'textarea']],'Update personnel',$target);?></section>
  <section class="panel"><h2>Probation and activity requirements</h2><?php View::form('/personnel/'.$id.'/staff-profile',['probation_status'=>['label'=>'Probation','options'=>array_combine(['none','active','completed','extended'],['None','Active','Completed','Extended'])],'probation_started_at'=>['label'=>'Probation start','type'=>'datetime-local'],'probation_ends_at'=>['label'=>'Probation end','type'=>'datetime-local'],'activity_status'=>['label'=>'Activity status','options'=>array_combine(['active','watch','inactive','exempt'],['Active','Watch','Inactive','Exempt'])],'activity_requirement_minutes'=>['label'=>'Required duty minutes','type'=>'number']],'Save staff profile',$staff);?></section>
  <section class="panel"><h2>Staff notes</h2><?php View::table(App::rows('SELECT n.*,u.display_name created_by_name FROM staff_notes n LEFT JOIN users u ON u.id=n.created_by WHERE n.user_id=? ORDER BY n.id DESC LIMIT 100',[$id]),['note_type'=>'Type','note_text'=>'Note','created_by_name'=>'Author','created_at'=>'Created']);View::form('/personnel/'.$id.'/notes',['note_type'=>['label'=>'Note type','options'=>array_combine(['general','supervisor','performance','commendation','concern'],['General','Supervisor','Performance','Commendation','Concern'])],'note_text'=>['label'=>'Staff note','type'=>'textarea','required'=>true]],'Add staff note');?></section>
  <section class="panel"><h2>Evaluations</h2><?php View::table(App::rows('SELECT e.*,u.display_name evaluator_name FROM staff_evaluations e LEFT JOIN users u ON u.id=e.evaluator_id WHERE e.user_id=? ORDER BY e.id DESC LIMIT 100',[$id]),['evaluation_type'=>'Type','rating'=>'Rating','summary'=>'Summary','evaluator_name'=>'Evaluator','created_at'=>'Created']);View::form('/personnel/'.$id.'/evaluations',['evaluation_type'=>['label'=>'Type','options'=>array_combine(['probation','routine','promotion','training','performance'],['Probation','Routine','Promotion','Training','Performance'])],'rating'=>['label'=>'Rating (1–5)','type'=>'number'],'summary'=>['label'=>'Summary','type'=>'textarea','required'=>true],'period_start'=>['label'=>'Period start','type'=>'date'],'period_end'=>['label'=>'Period end','type'=>'date']],'Add evaluation');?></section>
  <section class="panel"><h2>Recruit pipeline</h2><?php View::table(App::rows('SELECT stage,notes,created_at FROM recruit_pipeline WHERE user_id=? ORDER BY id DESC',[$id]),['stage'=>'Stage','notes'=>'Notes','created_at'=>'Changed']);View::form('/personnel/'.$id.'/pipeline',['stage'=>['label'=>'Stage','options'=>array_combine(['accepted','recruit','training','evaluation','member','failed','removed'],['Accepted','Recruit','Training','Evaluation','Member','Failed','Removed'])],'notes'=>['label'=>'Notes','type'=>'textarea']],'Update recruit stage');?></section>
  <section class="panel"><h2>Award or renew certification</h2><?php foreach(App::rows('SELECT id,name FROM certifications WHERE department_id IS NULL OR department_id=? ORDER BY name',[$target['department_id']]) as $c){?><h3><?=escape($c['name'])?></h3><?php View::form('/admin/management/certifications/'.$c['id'].'/award',['user_id'=>['label'=>'User ID','type'=>'hidden','default'=>$id],'notes'=>['label'=>'Award notes','type'=>'textarea']],'Award certification');}?></section>
  <section class="panel"><h2>Disciplinary records</h2><?php View::table(App::rows('SELECT d.*,u.display_name issued_by_name FROM disciplinary_records d LEFT JOIN users u ON u.id=d.issued_by WHERE d.user_id=? ORDER BY d.id DESC',[$id]),['record_type'=>'Type','reason'=>'Reason','action_taken'=>'Action','issued_by_name'=>'Issued by','created_at'=>'Created']);if(in_array($u['role'],Domain::CONTENT_STAFF,true))View::form('/admin/management/discipline/'.$id,['record_type'=>['label'=>'Record type','options'=>array_combine(['verbal_warning','written_warning','strike','suspension','removal','commendation','note'],['Verbal warning','Written warning','Strike','Suspension','Removal','Commendation','Note'])],'reason'=>['label'=>'Reason','type'=>'textarea','required'=>true],'action_taken'=>['label'=>'Action taken','type'=>'textarea']],'Add disciplinary record');?></section>
  <section class="panel"><h2>Training history</h2><?php View::table(App::rows('SELECT t.title,r.registration_type,r.status,r.result_status,r.score,t.start_at FROM training_registrations r JOIN training_sessions t ON t.id=r.training_id WHERE r.user_id=? ORDER BY t.start_at DESC LIMIT 50',[$id]),['title'=>'Session','registration_type'=>'Type','status'=>'Attendance','result_status'=>'Result','score'=>'Score','start_at'=>'Date']);?></section>
  <section class="panel"><h2>Leave history</h2><?php View::table(App::rows('SELECT start_date,end_date,reason,status,review_notes FROM loa_requests WHERE user_id=? ORDER BY created_at DESC',[$id]),['start_date'=>'From','end_date'=>'Through','reason'=>'Reason','status'=>'Status','review_notes'=>'Staff notes']);?></section>
  <section class="panel"><h2>Personnel actions</h2><?php View::table(App::rows('SELECT action_type,from_rank,to_rank,reason,created_at FROM staff_actions WHERE user_id=? ORDER BY id DESC LIMIT 100',[$id]),['action_type'=>'Action','from_rank'=>'From rank','to_rank'=>'To rank','reason'=>'Reason','created_at'=>'When']);?></section><?php
 }
}
