<?php
declare(strict_types=1);
namespace CommunityHub;
final class Web {
 public static function handle(string $method,string $path,array $d):void {
  if($method==='POST'){Auth::requireUser();Auth::csrf($d);App::limit('web-write',(string)Auth::user()['id'],100);}
  if($path==='/auth/logout'&&$method==='POST'){$_SESSION=[];session_destroy();App::redirect('/');}
  if(in_array($path,['/auth/discord','/auth/register'],true))Auth::begin();
  if($path==='/auth/discord/callback'&&$method==='GET')Auth::callback($_GET);
  if($path==='/auth/login'){View::layout('Sign in',function(){View::heading('Welcome to Community Hub','Connect your Discord account to access member features.');?><section class="panel narrow"><a class="btn" href="/auth/discord">Sign in with Discord</a></section><?php });return;}
  if($path==='/cookie-notice/accept'){setcookie('communityhub_cookie_notice','accepted',['expires'=>time()+31536000,'path'=>'/','secure'=>str_starts_with(App::base(),'https://'),'httponly'=>false,'samesite'=>'Lax']);App::redirect('/');}
  if(str_starts_with($path,'/branding/')){if(!in_array($path,['/branding/icon','/branding/logo'],true))throw new HttpError('Not found',404);$logo=App::row('SELECT file_data,mime_type FROM community_branding WHERE id=1');if(!empty($logo['file_data'])){header('Content-Type: '.$logo['mime_type']);echo $logo['file_data'];return;}header('Content-Type: image/svg+xml');echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><rect width="48" height="48" rx="10" fill="#dc123b"/><text x="24" y="31" text-anchor="middle" font-size="20" fill="white">CH</text></svg>';return;}
  if($path==='/'||$path==='/home'){if($path==='/'&&Auth::user())App::redirect('/overview');self::home();return;}
  if(in_array($path,['/overview','/overview/updates','/fivem','/fivem/status','/fivem/status/data'],true)){self::operations($method,$path,$d);return;}
  if($path==='/fivem/link-code'&&$method==='POST'){$u=Auth::requireUser(true);$code=(string)random_int(100000,999999);App::transaction(function()use($u,$code){App::query('DELETE FROM fivem_link_codes WHERE user_id=? OR expires_at<NOW()',[$u['id']]);App::query('INSERT INTO fivem_link_codes(user_id,code_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 5 MINUTE))',[$u['id'],hash('sha256',$code)]);});View::message('Link your game account','Enter /link '.$code.' in FiveM within five minutes.');return;}
  if(in_array($path,['/fivem/clock-in','/fivem/clock-out'],true)&&$method==='POST'){$u=Auth::requireUser(true);Domain::clock($u,$path==='/fivem/clock-in'?'in':'out','web',(string)($d['server_key']??'primary'));App::redirect('/fivem');}
  if($path==='/account'||$path==='/account/bio'){$u=Auth::requireUser();if($method==='POST'&&$path==='/account/bio'){$bio=App::text($d['bio']??'','Bio',1000,true);App::query('UPDATE users SET bio=? WHERE id=? AND is_active=1',[$bio,$u['id']]);App::redirect('/account?saved=1');}View::layout('Account settings',function()use($u){View::heading($u['display_name']??$u['username'],'Your account is authenticated through Discord.','ACCOUNT SETTINGS');?><section class="grid two"><article class="panel"><h2>Discord account</h2><div class="account-row"><?php View::avatar($u);?><div><strong><?=escape($u['discord_username'])?></strong><p class="muted">Discord ID: <?=escape($u['discord_id'])?></p></div></div><p class="success-text">Connected</p></article><article class="panel"><h2>Profile information</h2><p>Display name: <?=escape($u['display_name'])?></p><p>Email from Discord: <?=escape($u['email']??'Not provided')?></p><p>Community role: <?=escape($u['role'])?></p></article></section><section class="panel bio-editor"><h2>Your bio</h2><p class="muted">Your bio is visible on your public member profile.</p><?php if(isset($_GET['saved'])):?><p class="success-text" role="status">Your bio has been saved.</p><?php endif;View::form('/account/bio',['bio'=>['label'=>'About me','type'=>'textarea','max'=>1000]],'Save bio',$u);?></section><?php });return;}
  if(preg_match('~^/personnel(?:/(\d+))?$~',$path,$m)){self::personnel(isset($m[1])?(int)$m[1]:null);return;}
  if(str_starts_with($path,'/news')||$path==='/rules'){self::content($path);return;}
  if($path==='/about'){View::layout('About',function(){$c=self::publicContent();View::heading($c['about_title']??'About our community');View::prose($c['about_body']??'');});return;}
  if($path==='/gallery'||preg_match('~^/gallery/image/(\d+)$~',$path,$m)){if(isset($m[1])){$r=App::row('SELECT file_data,mime_type FROM community_gallery WHERE id=? AND is_removed=0 AND is_published=1',[(int)$m[1]]);if(!$r)throw new HttpError('Image not found.',404);header('Content-Type: '.$r['mime_type']);echo $r['file_data'];return;}View::layout('Gallery',function(){$c=self::publicContent();View::heading($c['gallery_title'],$c['gallery_body']);?><section class="community-gallery"><?php foreach(App::rows('SELECT id,title,caption FROM community_gallery WHERE is_removed=0 AND is_published=1 ORDER BY sort_order,id DESC') as $r):?><figure><img src="/gallery/image/<?=(int)$r['id']?>" alt="<?=escape($r['title'])?>"><figcaption><h2><?=escape($r['title'])?></h2><p><?=escape($r['caption'])?></p></figcaption></figure><?php endforeach?></section><?php });return;}
  if(str_starts_with($path,'/applications')){self::applications($method,$path,$d);return;}
  if(str_starts_with($path,'/reports')){self::reports($method,$path,$d);return;}
  if(str_starts_with($path,'/support')){self::support($method,$path,$d);return;}
  if(str_starts_with($path,'/documents')){Members::documents($method,$path,$d);return;}
  if(str_starts_with($path,'/calendar')){Members::calendar($method,$path,$d);return;}
  if(str_starts_with($path,'/training')){Members::training($method,$path,$d);return;}
  if(str_starts_with($path,'/lms')&&!str_starts_with($path,'/lms/admin')){Members::learning($method,$path,$d);return;}
  if(str_starts_with($path,'/admin/management/notifications')){Management::handle(Auth::requireUser(),$method,$path,$d);return;}
  if(str_starts_with($path,'/admin')||str_starts_with($path,'/community/manage')||str_starts_with($path,'/lms/admin')||str_starts_with($path,'/personnel/')||str_starts_with($path,'/command-center')||in_array($path,['/staff-activity','/loa-management'],true)){Admin::handle($method,$path,$d);return;}
  throw new HttpError('Page not found.',404);
 }
 public static function publicContent():array{$row=App::row("SELECT setting_value FROM site_settings WHERE setting_key='public_website_content'");$defaults=json_decode(file_get_contents(dirname(__DIR__).'/public-content-defaults.json'),true);$saved=json_decode($row['setting_value']??'{}',true)?:[];foreach($defaults as $k=>$v)if(array_key_exists($k,$saved)&&gettype($saved[$k])===gettype($v))$defaults[$k]=$saved[$k];return $defaults;}
 private static function home():void{View::layout('Community home',function(){$c=self::publicContent();$brand=Domain::branding();?><section class="public-hero" <?php if(preg_match('~^/(images/community-city-v3\.png|gallery/image/\d+)$~',$c['hero_image'])):?>style="background-image:linear-gradient(var(--panel),transparent),url('<?=escape($c['hero_image'])?>');background-size:cover;background-position:center"<?php endif?>><div class="hero-copy"><div class="eyebrow">WELCOME TO <?=escape($brand['name'])?></div><h1><?=escape($c['hero_title']??'Real roleplay. Real community.')?></h1><p><?=escape($c['hero_body']??'Find your department. Build your skills. Stay connected to your community.')?></p><div class="actions"><a class="btn" href="/applications">Apply to the community</a><a class="btn secondary" href="/auth/login">Member sign in</a></div></div><aside class="public-seal-panel"><h2><?=escape($c['side_title']??'From your first application to your next patrol.')?></h2><ol><?php foreach(explode("\n",$c['highlights']??"Apply and find your place\nTrain with your department\nTake part in live operations") as $i=>$text):?><li><span><?=$i+1?></span><?=escape($text)?></li><?php endforeach?></ol></aside></section><?php if($c['show_stats']):?><section class="stats"><?php $s=App::row('SELECT COALESCE(SUM(max_players),0) capacity,COALESCE(SUM(IF(last_heartbeat_at>DATE_SUB(NOW(),INTERVAL 90 SECOND),current_players,0)),0) players,COUNT(*) servers FROM fivem_servers WHERE is_enabled=1');foreach(['capacity'=>'Server capacity','players'=>'Players online','servers'=>'Configured servers'] as $key=>$label):?><div><span><?=escape($label)?></span><b><?=escape($s[$key])?></b></div><?php endforeach?></section><?php endif;if($c['show_resources']):?><section class="grid"><?php foreach(['/applications'=>['Recruitment','Find your place in the community.'],'/lms'=>['Training','Build your skills and earn certifications.'],'/documents'=>['Resources','Member policies and shared documents.'],'/fivem/status'=>['Server status','Follow our FiveM integrations.']] as $url=>[$title,$text]):?><a class="card" href="<?=escape($url)?>"><h2><?=escape($title)?></h2><p><?=escape($text)?></p></a><?php endforeach?></section><?php endif;Landing::sections($c);});}
 private static function operations(string $method,string $path,array $d):void{$servers=App::rows('SELECT id,name,server_key,max_players,IF(last_heartbeat_at>DATE_SUB(NOW(),INTERVAL 90 SECOND),1,0) live,IF(last_heartbeat_at>DATE_SUB(NOW(),INTERVAL 90 SECOND),current_players,0) current_players,last_heartbeat_at,game_hours,game_minutes,game_clock_at FROM fivem_servers WHERE is_enabled=1 ORDER BY id');if($path==='/fivem/status/data')App::json(['ok'=>true,...Status::snapshot()]);$u=Auth::user();$member=false;if($u)try{App::membership($u);$member=true;}catch(HttpError $e){}View::layout($path==='/fivem/status'?'Server status':'Community overview',function()use($servers,$u,$member,$path){View::heading($path==='/fivem/status'?'Server status':'Community overview','Live community operations and FiveM integration state.');if($member&&$path==='/overview')Dashboard::member($u);?><section class="grid two"><?php foreach($servers as $s):?><article class="panel" data-server-key="<?=escape($s['server_key'])?>"><span data-server-state class="status-badge <?=$s['live']?'online':'offline'?>"><?=$s['live']?'Online':'Offline'?></span><h2><?=escape($s['name'])?></h2><p><span data-server-players><?=(int)$s['current_players']?> / <?=(int)$s['max_players']?></span> players</p><small>Last heartbeat: <?=escape($s['last_heartbeat_at']??'Never')?></small><p>Game time: <?=$s['game_clock_at']?sprintf('%02d:%02d',$s['game_hours'],$s['game_minutes']):'Awaiting game sample'?></p></article><?php endforeach?></section><script src="/js/php-status.js" defer></script><?php if($path==='/fivem/status')Status::history();if($member):?><section class="panel duty-controls"><h2>Your duty clock</h2><?php $history=Domain::clockHistory((int)$u['id']);if($history['active']):?><strong data-duty-running="true" data-duty-seconds="<?=(int)$history['active']['duration_seconds']?>">00:00:00</strong><?php else:?><p>Off duty</p><?php endif;View::form('/fivem/clock-in',['server_key'=>['label'=>'Server','options'=>array_column($servers,'name','server_key')]],'Clock in');View::form('/fivem/clock-out',[],'Clock out');View::form('/fivem/link-code',[],'Generate FiveM link code');?></section><section class="panel"><h2>Recent duty sessions</h2><?php View::table($history['sessions'],['callsign'=>'Callsign','server_name'=>'Server','clocked_in_at'=>'Clock in','clocked_out_at'=>'Clock out','duration_seconds'=>'Seconds']);?></section><?php endif;});}
 private static function personnel(?int $id):void{$rows=App::rows("SELECT id,display_name,avatar_url,bio,callsign,rank_name,department_id FROM users WHERE is_active=1 AND member_status IN('active','recruit','loa','inactive')".($id?' AND id=?':'').' ORDER BY display_name',$id?[$id]:[]);if($id&&!$rows)throw new HttpError('Member not found.',404);View::layout($id?'Member profile':'Member directory',function()use($rows,$id){View::heading($id?'Member profile':'Member directory');?><section class="panel"><div class="admin-list"><?php foreach($rows as $u):?><a class="admin-row" href="/personnel/<?=(int)$u['id']?>"><?php View::avatar($u);?><div><strong><?=escape(($u['callsign']?$u['callsign'].' · ':'').$u['display_name'])?></strong><p class="muted"><?=escape($u['rank_name'])?></p></div></a><?php endforeach?></div><?php if($id&&!empty($rows[0]['bio'])):?><h2>About me</h2><?php View::prose($rows[0]['bio']);endif?></section><?php if($id&&Auth::user()){try{App::membership(Auth::user());}catch(HttpError $e){return;}$u=Auth::user();?><section class="panel"><h2>Certifications</h2><?php View::table(App::rows('SELECT c.name,uc.awarded_at,uc.expires_at FROM user_certifications uc JOIN certifications c ON c.id=uc.certification_id WHERE uc.user_id=?',[$id]),['name'=>'Certification','awarded_at'=>'Awarded','expires_at'=>'Expires']);?></section><?php if(in_array($u['role'],Domain::STAFF,true))Admin::personnel($u,$id);}});}
 private static function content(string $path):void{if($path==='/rules'){$result=Domain::rules($_GET);View::layout('Community rules',function()use($result){View::heading('Community rules');foreach($result['rules'] as $r){?><details class="community-rule"><summary><?=escape($r['title'])?></summary><?php View::prose($r['body']);?></details><?php }});return;}if(preg_match('~^/news/(\d+)$~',$path,$m)){$p=Domain::post($m[1]);View::layout($p['title'],function()use($p){View::heading($p['title'],$p['category']);View::markdown($p['body']);});return;}if($path!=='/news')throw new HttpError('Page not found.',404);$result=Domain::news($_GET);View::layout('News & updates',function()use($result){View::heading('News & updates');foreach($result['posts'] as $p){?><article class="community-entry"><h2><a href="/news/<?=(int)$p['id']?>"><?=escape($p['title'])?></a></h2><small><?=escape($p['category'].' · '.$p['published_at'])?></small><p><?=escape($p['summary'])?></p></article><?php }});}
 private static function applications(string $method,string $path,array $d):void{if($path==='/applications'){$forms=App::rows('SELECT id,title,slug,description FROM application_forms WHERE is_open=1 ORDER BY sort_order,title');View::layout('Community applications',function()use($forms){View::heading('Community applications','Choose an open application.');?><section class="grid"><?php foreach($forms as $f):?><a class="card" href="/applications/<?=escape(rawurlencode($f['slug']))?>"><h2><?=escape($f['title'])?></h2><p><?=escape($f['description'])?></p></a><?php endforeach?></section><?php });return;}$slug=rawurldecode(substr($path,14));$f=App::row('SELECT * FROM application_forms WHERE slug=? AND is_open=1',[$slug]);if(!$f)throw new HttpError('Application not found.',404);if($method==='POST'){$u=Auth::requireUser(true);$result=Applications::submit($u,$slug,$d);View::message('Application submitted','Your application #'.$result['application_id'].' was submitted successfully.');return;}View::layout($f['title'],function()use($f,$slug){View::heading($f['title'],$f['description']??'');$u=Auth::user();$fields=[];foreach(Applications::questions((int)$f['id'],$u) as $q){$fields['q_'.$q['id']]=['label'=>$q['label'],'type'=>$q['question_type']==='textarea'?'textarea':(in_array($q['question_type'],['number','date','url','email'],true)?$q['question_type']:'text'),'required'=>(bool)$q['is_required'],'max'=>10000,'default'=>$q['prefill_value']??''];if(in_array($q['question_type'],['select','radio','checkbox'],true)){$options=json_decode($q['options_json']??'[]',true)?:[];$fields['q_'.$q['id']]['options']=array_combine($options,$options);$fields['q_'.$q['id']]['type']=$q['question_type'];}}if($u){App::membership($u);View::form('/applications/'.rawurlencode($slug),$fields,'Submit application');}else{foreach($fields as $f){?><h3><?=escape($f['label'])?></h3><?php }?><a class="btn" href="/auth/login">Sign in with Discord to apply</a><?php }});}
 private static function reports(string $method,string $path,array $d):void{if($path!=='/reports')throw new HttpError('Page not found.',404);$u=Auth::user();if($method==='POST'){$u=Auth::requireUser();$types=['FailRP','VDM','RDM','NLR','Metagaming','Powergaming','Combat Logging','Player Report','Staff Report','Bug Report','Other'];if(!in_array($d['report_type']??'',$types,true))throw new HttpError('Select a valid report type.');$id=App::insert("INSERT INTO reports(reporter_user_id,report_type,reported_name,occurred_at,description,evidence_url,status) VALUES(?,?,?,?,?,?,'open')",[$u['id'],$d['report_type'],App::text($d['reported_name']??'','Reported player name',150,true)?:null,($d['occurred_at']??'')?:null,App::text($d['description']??null,'Description',10000),App::text($d['evidence_url']??'','Evidence URL',1000,true)?:null]);View::message('Report submitted','Report #'.$id.' has been submitted for staff review.');return;}View::layout('Submit a report',function()use($u){View::heading('Submit a report','Reports are private and reviewed by community staff.');if(!$u){?><a class="btn" href="/auth/login">Sign in to submit a report</a><?php return;}View::form('/reports',['report_type'=>['label'=>'Report category','options'=>array_combine(['FailRP','VDM','RDM','NLR','Metagaming','Powergaming','Combat Logging','Player Report','Staff Report','Bug Report','Other'],['FailRP','VDM','RDM','NLR','Metagaming','Powergaming','Combat Logging','Player Report','Staff Report','Bug Report','Other'])],'reported_name'=>['label'=>'Reported player name','max'=>150],'occurred_at'=>['label'=>'When it happened','type'=>'datetime-local'],'description'=>['label'=>'Incident details','type'=>'textarea','required'=>true,'max'=>10000],'evidence_url'=>['label'=>'Evidence URL','type'=>'url']],'Submit report');});}
 private static function support(string $method,string $path,array $d):void{$u=Auth::user();if($path==='/support'&&!$u){View::layout('Community support',function(){View::heading('Community support','Get help with your account, applications and community questions.');?><a class="btn" href="/auth/login">Sign in to open a ticket</a><?php });return;}$u=Auth::requireUser();if($path==='/support'&&$method==='POST')App::redirect('/support/tickets/'.Domain::createTicket($u,$d));if($path==='/support/new'){View::layout('New ticket',function(){View::heading('New support ticket');View::form('/support',['category'=>['label'=>'Category','options'=>['question'=>'Question','bug'=>'Bug','report'=>'Report','appeal'=>'Appeal']],'subject'=>['label'=>'Subject','required'=>true,'max'=>180],'message'=>['label'=>'Message','type'=>'textarea','required'=>true,'max'=>10000]],'Open ticket');});return;}if(preg_match('~^/support/tickets/(\d+)(?:/(reply|status))?$~',$path,$m)){if($method==='POST'){Domain::replyTicket($u,(int)$m[1],$d,false,($m[2]??'')==='status');App::redirect('/support/tickets/'.$m[1]);}$thread=Domain::thread($u,(int)$m[1]);View::layout($thread['ticket']['subject'],function()use($thread){$t=$thread['ticket'];View::heading('#'.$t['id'].' · '.$t['subject'],str_replace('_',' ',$t['status']));?><a class="btn secondary" href="/support">Back to tickets</a><?php foreach($thread['messages'] as $message){?><article class="community-entry"><strong><?=escape($message['display_name']??'Former member')?></strong><small><?=escape(($message['is_staff']?'Support staff':'Member').' · '.$message['created_at'])?></small><?php View::prose($message['message']);?></article><?php }if($t['status']!=='closed')View::form('/support/tickets/'.$t['id'].'/reply',['message'=>['label'=>'Reply','type'=>'textarea','required'=>true,'max'=>10000]],'Send reply');if($thread['staff'])View::form('/support/tickets/'.$t['id'].'/status',['status'=>['label'=>'Ticket status','options'=>array_combine(Domain::TICKET_STATUSES,Domain::TICKET_STATUSES)]],'Update status',$t);});return;}if($path!=='/support')throw new HttpError('Page not found.',404);$queue=($_GET['queue']??'')==='1';$tickets=Domain::tickets($u,$queue,(string)($_GET['status']??''));View::layout('My tickets',function()use($tickets,$u){View::heading('Support tickets');?><div class="actions"><a class="btn" href="/support/new">New ticket</a><?php if(in_array($u['role'],Domain::CONTENT_STAFF,true)):?><a class="btn secondary" href="/support?queue=1">Staff queue</a><?php endif?></div><?php View::table($tickets,['id'=>'Ticket','subject'=>'Subject','status'=>'Status','updated_at'=>'Updated'],function($t){?><a href="/support/tickets/<?=(int)$t['id']?>">Open conversation</a><?php });});}
}
